### ISSUE TITLE
Extend Scratchpad Sandbox profile to include a full data set.

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2229]
- Original ID: 427
 - Added by **Irina Brake**
 - Scratchpads URL: 

### Description:
Please create a copy of the Milichiidae Scratchpad under the URL http://demo.scratchpads.eu (or something like that) to be used as the "full" sandbox.

**Comment by alycejenni** [comment]
the new sandbox (http://sandbox.scratchpads.eu) has demo content
