### ISSUE TITLE
EOL videos won't expand

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2592]
- Original ID: 824
 - Added by **Eli Sarnat**
 - Scratchpads URL: http://antkey.org/

### Description:
Videos served by EOL won't expand into full screen or larger frames.

http://antkey.org/taxonomy/term/23/media

**Comment by benscott** [comment]
EOL videos can no longer be embedded on sites - hidden the EOL block.
