### ISSUE TITLE
Taxon pages: Specimens don't show on map

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2627]
- Original ID: 860
 - Added by **Irina Brake**
 - Scratchpads URL: http://diptera.myspecies.info/

### Description:
There should be two specimens showing on the map at http://test-carnidae.myspecies.info/taxonomy/term/10/maps but none is visible. Should this map also show the TDWG regions and GBIF?

**Comment by alycejenni** [comment]
fixed in 2015 - also potentially irrelevant w/ new maps work?
