### ISSUE TITLE
Lucid keys in 2.0?

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2644]
- Original ID: 877
 - Added by **Eli Sarnat**
 - Scratchpads URL: null

### Description:
Is it possible yet to add Lucid keys to a 2.0 site?

**Comment by alycejenni** [comment]
Lucid keys are now implemented:
https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Lucid-keys
