### ISSUE TITLE
Make maps publishable

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2664]
- Original ID: 897
 - Added by **Steven Bachman**
 - Scratchpads URL: null

### Description:
Upgrade taxon maps to journal publishing standard e.g. high resolution outputs (TIFF), graticule options, scale, north bar etc. See this for ideas:

http://www.simplemappr.net/

Different journals have different standards so these need to be flexible without overwhelming the user.

**Comment by PaulKiddle** [comment]
Not well defined, probably not particularly important. Can always re-open if someone else wants this.
