### ISSUE TITLE
Ecological relationships (host/parasite, predator/prey etc)

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2673]
- Original ID: 906
 - Added by **Laurence J Livermore**
 - Scratchpads URL: null

### Description:
We need to discuss and implement ecological relationships such as host/parasite, predator/prey and other (user definable?) relationships.

Darwincore has an "associated taxa" field (see http://rs.tdwg.org/dwc/terms/history/index.htm)

**Comment by alycejenni** [comment]
I believe this has been implemented in the ecological interactions module
