### ISSUE TITLE
DELTA import characters and description files

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2719]
- Original ID: 952
 - Added by **BRAET Yves**
 - Scratchpads URL: null

### Description:
Dear Developers,

I am glad to see the huge amount of work you done.
But I would like to add some to this ;-)

Currently, I am looking to develop a characters project with a large dataset of taxa and characters. They are now coded into the DELTA format. And to avoid the waste of time to all reintroduced into Scratchpad, I wish to ask you if it could be possible to realize a module allowing DELTA users to (at least) import into their characters project the Chars and Items files (I have put two as samples here). These seems to me very usefull to improve the coding avoiding mistakes, and to allow the migration to Scratchpads. 
Once this import is done, it could be usefull to realize keys inside Scratchpads (like for the LUCID datasets), I presume.

Moreover, may be you could make some link with the new DELTA project (http://code.google.com/p/open-delta/) to include(but I am not convinced by this) their interactive key?

Thank you for your help

**Comment by alycejenni** [comment]
this is a Java-based format from Atlas of Living Australia
