### ISSUE TITLE
My Favorites feature

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2783]
- Original ID: 1018
 - Added by **Eli Sarnat**
 - Scratchpads URL: null

### Description:
The goal of the ‘favorites’ feature is to allow users to compile and manage lists of various content types.

1. Types of content that can be added to favorites: taxa, specimens/observations, checklists, comparison charts, glossary terms, literature records.
 
2. Favorites are stored on individual user accounts?

3. Maybe a small icon (+ or ‘heart’?) appears next to content items (nodes?) that can be added to favorites.

4. Selected nodes are group according to content type. For example, if user favorites species A, species B, genus C, those get nested within ‘Favorite Taxa’. if user favorites citation A, citation B, citation C, those get nested within ‘Favorite Literature Records’.

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/60/my_collection-7.x-1.2.zip

**Comment by benscott** [comment]
my_collection module was added to Scratchpads back in 2012.
