### ISSUE TITLE
Character Project: Convert Lucid key export to character project

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2795]
- Original ID: 1030
 - Added by **Eli Sarnat**
 - Scratchpads URL: http://antkey.org/

### Description:
I've exported a draft lucid key to xls format and would like to see if I can convert it into a character project. However, it doesn't appear that maintainers have the capacity to this ourselves as a character project import.

I've uploaded the xls file here:
http://antkey.org/sites/antkey.org/files/Antkey_v01.xls

**Comment by benscott** [comment]
SSD import is sufficient, even if not all features are replicated.
