### ISSUE TITLE
Display images from Morphbank (using Remote Stream Wrapper?)

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#2932]
- Original ID: 1180
 - Added by **Laurence J Livermore**
 - Scratchpads URL: null

### Description:
David Maddison/Austin Baker (http://bembidion.info) have requested the ability to display Morphbank images on their site by saving the image URL into a field.

This may be possible using Remote Stream Wrapper (http://drupal.org/project/remote_stream_wrapper) but would not retrieve any metadata, including the CC license, from Morphbank.

Example Morphbank page: http://www.morphbank.net/?id=805626

**Comment by alycejenni** [comment]
external images can now be imported via URL (no metadata/licence - reopen if that's needed); closing
