### ISSUE TITLE
jquery_update breaks multiple file field functionality

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3020]
- Original ID: 1275
 - Added by **Ben Scott**
 - Scratchpads URL: null

### Description:
It doesn't work if there's another file field.

**Comment by alycejenni** [comment]
this now appears to work fine:
![image](https://user-images.githubusercontent.com/23579762/54423340-5bfb0a00-4708-11e9-8287-c315eb06d834.png)
