### ISSUE TITLE
Media Gallery features/issues

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3046]
- Original ID: 1315
 - Added by **Eli Sarnat**
 - Scratchpads URL: null

### Description:
1. Allow the results of the faceted search could be sorted by term name. Right now terms are sorted by number of images.

2. Allow ALL terms to be shown when 'more' link is clicked. Right now max seems to be 50. This is especially important for taxonomic name.

3. Allow media gallery to be searched.

4. Allow colorbox fields to be edited. For example, I want to be able to give attribution for photographs I didn't take.

**Comment by alycejenni** [comment]
these all seem to be implemented or fixed; closing
