### ISSUE TITLE
SPM: descriptions are displayed for ALL related tax. names

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3054]
- Original ID: 1324
 - Added by **Eli Sarnat**
 - Scratchpads URL: http://antkey.org/

### Description:
The 'description' tab of the taxon description pages are displaying the descriptions of ALL associated taxonomic names. For example, my taxon page for Tetramorium simillimum displays the descriptions of: Wasmannia auropunctata, Wasmannia, Tetramorium, Tetramorium caldarium, Tetramorium simillimum. 

http://antkey.org/taxonomy/term/4901/descriptions

Screenshot attached.

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/213/SPM-bug.jpg

**Comment by alycejenni** [comment]
fixed in 2015
