### ISSUE TITLE
Bulk edit of Biblio records

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3156]
- Original ID: 1480
 - Added by **Ruth Bone0**
 - Scratchpads URL: http://eulophiinae.e-monocot.org/

### Description:
Is there a way in which I can apply one change (e.g. publication year) to multiple Biblio records?
And can I sort on other fields in the biblio module, when in Edit mode. I have modified the view in the Biblio module so that I now have 'short title' as one of the fields, but I can't find a way to make this availble to 'sort by'.
I would like to sort by short title (in this case protologue citation), select all relevant records with the check box. Then change the data of publication, and apply to all selected records.
Is this possible?
With thanks.

**Comment by benscott** [comment]
Still no stable release of Biblio 7.x-3.x, and with development on that module apparently ending 6 years ago implementing this feature will not be possible.
