### ISSUE TITLE
Remove "Associated accepted name" field

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3367]
- Original ID: 2071
 - Added by **Laurence Livermore**
 - Scratchpads URL: null

### Description:
The ITIS Data requirements (http://www.itis.gov/submit_guidlines.html) state that Parent names are mandatory if Scientific Name is accepted/valid and that Associated Accepted Names are mandatory if Scientific Name is not accepted/invalid.

Only one term should be used to establish the position in a taxonomy.

**Comment by alycejenni** [comment]
not updated for >5y; closing
