### ISSUE TITLE
Allow some media to not be displayed in gallery.

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3506]
- Original ID: 2241
 - Added by **Simon Rycroft**
 - Scratchpads URL: null

### Description:
Allow some media to not be displayed in gallery. For example, I have a few figures in my 'about' page that I would rather not have displayed in the gallery.

**Comment by alycejenni** [comment]
this is now possible by setting media weight to 100
