### ISSUE TITLE
Access rights management

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3659]
- Original ID: 2419
 - Added by **Alice Heaton**
 - Scratchpads URL: null

### Description:
We need to be able to specify which user, group of users or roles have access to any piece of content (node, publication, taxonomy term, file and so on).

After some discussion, it was suggested a custom module would be needed for this, rather than using Organic Groups.

This is generally needed, and in particular is needed for the Publication module. This will add an extra requirement: there should be hooks to allow to define the list of users who have access to the content. This would allow the publication module to use the author list of a publication as the people who are allowed to access it.

**Comment by benscott** [comment]
Publication module is now retired & #2676 fixes the generic access requirements.
