### ISSUE TITLE
import and handle xper output .xpd files

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3661]
- Original ID: 2421
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: null

### Description:
Xper is exporting a batch of files attached here. 

We should be able to import and visualise .spd files in Scratchpads

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/330/base-dombeyoideae-illus.xpd
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/331/base-dombeyoideae-illus.xpr
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/332/base-dombeyoideae-illus.xpw
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/333/base-dombeyoideae-illus.xpx

**Comment by benscott** [comment]
SSD format is preferable, especially as not sure of status of XPER2/3
