### ISSUE TITLE
Generate keys from a character matrix

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3662]
- Original ID: 2422
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: null

### Description:
We should be able to import .SDD files and generate keys by implementing the Ikey+ applet by Xper

**Comment by benscott** [comment]
SSD export is now a function of the character matrix, so keys can be created outside of Scratchpads. They can be reuploaded & attached to nodes for download and offline viewing.  At this stage of the project, we will not be building a key viewer in Scratchpads.
