### ISSUE TITLE
Consider linking to SimpleMappr

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3782]
- Original ID: 2565
 - Added by **Steve Bachman**
 - Scratchpads URL: null

### Description:
SimpleMappr (http://www.simplemappr.net/) is a neat tool to produce simple publication quality maps. Could this be incorporated into the workflow when creating a publication from scratchpads? e.g. describing a new species. It has an API. thanks. Steve

**Comment by alycejenni** [comment]
duplicate of #2664; closing
