### ISSUE TITLE
Taxonomy terms should not be their own parent

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#38]
An import on ffa.myspecies.info resulted in a taxonomy term which was its own parent. This caused the scheduled cron on the task to enter an infinite loop, and consume system resources. As the task did not finish within a specified period the cron was started again by aegir - resulting in multiple never-ending cron jobs. The Scratchpads data issues page reports loops in the taxonomy as an issue, but something needs to be done to prevent it happening on node import.

**Comment by jrdh** [comment]
Just tried this and couldn't recreate the issue so I assume this has been fixed somewhere in the last 3 years.
