### ISSUE TITLE
Problems when enabling Publication Module on eMonocot site

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#3858]
- Original ID: 2642
 - Added by **Laurence Livermore**
 - Scratchpads URL: null

### Description:
Simon and I tried to enable the Publication Module on the eMoncoot Dioscoreaceae site (http://dioscoreaceae.e-monocot.org/)

We experience a number of issues:
* When I tried to enable it, it failed on enabling a dependency (relations) and I could no longer access the Modules menu
* After Simon tried to enable it there were no obvious problems until I created a "pensoft" content type where there were missing entry fields

We should test the module on other sites (Scratchpads and eMonocot) prior to the Pensoft meeting (3rd April 2013)

**Comment by alycejenni** [comment]
not reproducible, no updates for ~6y; closing
