### ISSUE TITLE
Any objects that are All Rights Reserved need to be indicated as such in exports to EOL

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4149]
- Original ID: 2971
 - Added by **Cyndy Parr**
 - Scratchpads URL: 

### Description:
If no license is indicated in the DWC-A file for EOL, EOL uses one of these defaults, as set by the provider: CC-BY, CC-BY-SA, CC-BY-NC, Public domain.  This is because some providers find it easier to set a blanket license for their entire resource. As eMonocots does not accept any of those as a default, it is necessary for the DWC-A to explicitly declare an object license to be All Rights Reserved. Then EOL can safely ignore it.  

Are all text objects supposed to have licenses on Scratchpads? It didn't seem possible to add the license throught the SP interface, so it seems that the default is CC-BY-NC-SA as indicated in the footer, as shown here  http://cypripedioideae.e-monocot.org/taxonomy/term/8/descriptions

**Comment by alycejenni** [comment]
looks like it was fixed; closing
