### ISSUE TITLE
A combined specimen locality and collectors import via spreadsheet

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4160]
- Original ID: 2985
 - Added by **Katherine Bouton**
 - Scratchpads URL: null

### Description:
A combined speciment locality and collectors import via spreadsheet

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/817/2985.patch

**Comment by benscott** [comment]
This enhancement is out of scope now.
