### ISSUE TITLE
How can I sort media gallery by weight?

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4166]
- Original ID: 2992
 - Added by **Irina Brake**
 - Scratchpads URL: http://diptera.myspecies.info/gallery?f[0]=im_field_smg_galleries%3A10267#

### Description:
I would like to sort my media galleries by weight. How can I do this?

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/447/Screen%20Shot%20.png

**Comment by alycejenni** [comment]
fixed(?) in 2015
