### ISSUE TITLE
Issue with CKEditor counter plugin

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4168]
- Original ID: 2994
 - Added by **Alice Heaton**
 - Scratchpads URL: null

### Description:
I have noticed that there are issues with the CKEditor counter plugin. This is a CKEditor module plugin - but we either need to disable it or workout the issue as this can cause other plugins to fail (Once a plugin has failed, others won't run - possibly because of JS aggregation).

I noticed this while working on the Publication module (I actually disabled the counter plugin when running the Publication module) and more recently in #2894 - in both cases the counter plugin failed under some circumstances, and then that caused my own plugins to not get executed.

The failure appears to be in the Javascript code. It doesn't always happen - it requires a series of gaining/loosing focus events, though I don't have a 100% sure way of reproducing it yet.

I have seen the issue both on FF and Chrome.

**Comment by alycejenni** [comment]
unable to recreate this; assuming irrelevant and closing
