### ISSUE TITLE
Map tab in species overview missing distribution data

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4200]
- Original ID: 3033
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: http://thymus.myspecies.info/taxonomy/term/98/maps

### Description:
The map tab in the species overview page should display all (specimen records and distribution) data. Currently only the specimen records are displayed.

**Comment by PaulKiddle** [comment]
Fixed; taxon had the wrong GBIF key, deleted the taxon->gbif record from the database to get the correct one.
