### ISSUE TITLE
Move ecological relationships editing from taxonomy to taxon descriptions

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4242]
- Original ID: 3084
 - Added by **Katherine Bouton**
 - Scratchpads URL: null

### Description:
The functionality of relating taxa should remain the same, what I am proposing is to move the selection and displaying areas from the taxonomies to the taxon description content type. Would this be possible?

If however this is not possible or requires too much work we should at least consider changing the display area of this information from the nomenclature block to the description block in the species overview page

**Comment by alycejenni** [comment]
the eco interactions module probably makes this obsolete; closing
