### ISSUE TITLE
Add comment box to the bottom of the IUCN Red List assessment page

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4244]
- Original ID: 3086
 - Added by **Steve Bachman**
 - Scratchpads URL: http://threatenedplants.myspecies.info/

### Description:
For our site http://threatenedplants.myspecies.info/ we would like to have the option for users to comment on species pages - in particular the IUCN Red List assessment under the 'Descriptions' tab:

http://threatenedplants.myspecies.info/taxonomy/term/26498/descriptions

It just needs to be a simple comment box - see attached. If this could be ready for the NHM informatics day (24th july) that would be phenomenal. If not, I'll do a mock up.

Thanks team!

Steve

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/495/Capture.JPG

**Comment by benscott** [comment]
Reply module still in alpha 6 years later. I think we may have just missed NHM informatics day and as most enabled comments result in a load of spam, not sure this is worth doing anyway.
