### ISSUE TITLE
Mapping tool mods for introduced species records

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4294]
- Original ID: 3136
 - Added by **Eli Sarnat**
 - Scratchpads URL: antkey.org

### Description:
I would like to modify the current mapping tools to display the native range of taxa differently from their introduced ranges. For example, for specimen records displaying the placemark as black for native range occurrences and red for introduced range occurrences. And for the taxon pages having the TDWG regions display as shaded black for native ranges and shaded red for introduced ranges. 

Would there be a relatively simple way to do this within the confines of DwC standards? If so, I would consider contracting a third party developer to assist.

**Comment by benscott** [comment]
This feature was required for a single site many years ago.
