### ISSUE TITLE
Module specification Requirements for Character matrix - Next phase

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4384]
- Original ID: 3231
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: null

### Description:
The group of the following members 
DK, DR, LL, EB
have discussed and developed a module specification requirement document for the next phase of the Character editor development. 

The file can be found at 
https://docs.google.com/document/d/14TB7t9OoRDuTSxlinEIEgdzbKJXo1kVlowHwozkXrio/edit?disco=AAAAAGUgeA4#

All reported issues covered by these specs should be marked as duplicates

**Comment by benscott** [comment]
Completed along with blocking issues above; closed.
