### ISSUE TITLE
Allow a user to specify the default tab on a taxon page

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4568]
- Original ID: 3419
 - Added by **Laurence Livermore**
 - Scratchpads URL: 

### Description:
Jeremy Miller has suggested an alternative taxon page layout based on the design of his Digital Fauna of Southeast Asian Spiders site (www.digitalspiders.org).

It has the following features:
* A taxonomy than does not require names based on codes of nomenclature (e.g. placeholder names based on molecular data
* Heavy emphasis on images (rather than textual taxon data)
* Distribution map in the sidebar

Screenshot attached

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/563/Alternative%20Taxon%20Page%20Layout.png

**Comment by PaulKiddle** [comment]
Resolved by #6084, just needs review changes & merge
