### ISSUE TITLE
Ensure Help Wiki up to date with Scratchpads 2.6.x

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4607]
- Original ID: 3458
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: null

### Description:
The following new features/changes should be documented in the help wiki site:

Fixed the twitter filter (#3288)
Enable the hiding of PDF attachments associated with biblio nodes (#3404)
Export TID and Name for a taxonomic name field (#3414)

**Comment by benscott** [comment]
Help wiki has been retired in favour of https://scratchpads.readthedocs.io/en/latest/, which was updated March 2019, since when there have been limited functional changes.
