### ISSUE TITLE
Content translation: allow translation of Glossary page

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4645]
- Original ID: 3500
 - Added by **Eli Sarnat**
 - Scratchpads URL: antkey

### Description:
The Glossary page is not currently translatable. Also, when the glossary page is selected by a user using a non-default language, then the language for the site reverts to the default language. For example, if the site is being viewed in Indonesian and the 'Glossarium' link is selected from the main menu, the site reverts to English.

http://antkey.org/lexicon/43

(This is relatively low priority for antkey site)

**Comment by alycejenni** [comment]
part 2 seems to be resolved; the site no longer reverts to the default language
