### ISSUE TITLE
Enable the publication tool

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4647]
- Original ID: 3502
 - Added by **Alice Heaton**
 - Scratchpads URL: null

### Description:
For soft release tomorrow. Then Pensoft end is not working yet (see https://github.com/pensoft/dev/issues) however people have been asking about this so we decided to release it anyway.

Things to check before release:
- CKEditor works with the publication html format ;
- Citation (reference, image, table) buttons work ;
- Publication preview looks correct
  (order,field labels, author names, institutions, etc.) ;
- Treatments work ;
- Permissions work as expected (only maintainers access for now)

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/603/Add%20Taxonomic%20paper%20(Pensoft%20Writing%20Tool)%20%20Thyme%20plants%20of%20SE%20Europe%202013-10-09%2010-37-01.png
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/604/Publishing%20Biodiversity%20%20Thyme%20plants%20of%20SE%20Europe%202013-10-09%2010-41-15.png
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/605/Publishing%20Biodiversity%20Thyme%20plants%20of%20SE%20Europe%202013-10-09%2010-46-04.png
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/606/Publishing%20Biodiversity%20Thyme%20plants%20of%20SE%20Europe%202013-10-09%2010-52-05.png
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/607/My%20publication%20title%20%20Thyme%20plants%20of%20SE%20Europe%202013-10-09%2011-08-34.png

**Comment by alycejenni** [comment]
unable to recreate last issue; all others fixed so closing
