### ISSUE TITLE
Content translation: untranslated pages should display use default language

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4685]
- Original ID: 3542
 - Added by **Eli Sarnat**
 - Scratchpads URL: http://antkey.org/th/node/4628 

### Description:
There are Pages that have been translated into Chinese but not into Thai (default language is English). When viewing in Thai, these pages are using the Chinese translation instead of the English translation. I think it would be better if they displayed in English, in this case.

http://antkey.org/th/node/4628

**Comment by alycejenni** [comment]
appears to still be an issue.
may be using the first language (alphabetically?) instead of the default language:

![image](https://user-images.githubusercontent.com/23579762/54381703-4c3ae180-4686-11e9-888e-e7a4c7513152.png)

**Comment by PaulKiddle** [comment]
I've set the language order to English first, I don't think this really needs a code fix. I might add a doc to the wiki.
