### ISSUE TITLE
Species page error

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4690]
- Original ID: 3548
 - Added by **Eli Sarnat**
 - Scratchpads URL: http://antkey.org/taxa/solenopsis-invicta

### Description:
I receive the Error message when attempting to view the species page of Solenopsis invicta: http://antkey.org/taxa/solenopsis-invicta. This occurred after making edits to the Map by using the region select tool.

**Comment by alycejenni** [comment]
seems to have been fixed (#4699)
