### ISSUE TITLE
Image tagging based on associated specimen data

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4706]
- Original ID: 3566
 - Added by **lukas.scharer lukas.scharer**
 - Scratchpads URL: null

### Description:
Hi all,
given that the specimens dialog allows batch uploading of media files, I would have expected it to batch annotate the media files with the specimen code, the species name, and the location data, if set. Moreover, changing any of these later should of course automatically update the annotation of all those files that were jointly uploaded from within the specimen dialog.
Cheers, Lukas

**Comment by alycejenni** [comment]
please re-open if this is still relevant
