### ISSUE TITLE
Ecological relationships exports incorrectly as |host_parasite|xxxx|array|array|

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4728]
[Phthiraptera](http://phthiraptera.info)

 - Original ID: 3590
 - Added by **Vince Smith**
 - Scratchpads URL: 

### Description:
Under Checklists / Louse-Host associations go back to the original MDB file and pull out the type host associations. Each louse-host association would have an additional field (yes or no) as to whether a host species is the type host for a particular louse. THis data is held with the association as the same host can be a type host for one louse species but not the type host for another louse. The field should be added to the view after the host name and can be shown as a simple "X" if yes and blank if no.

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/641/Taxa%20with%20type.xlsx

**Comment by benscott** [comment]
Lice/host associations exist on phthiraptera so I assume this was fixed.
