### ISSUE TITLE
Publication add form fails first time

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4761]
- Original ID: 3623
 - Added by **Alice Heaton**
 - Scratchpads URL: null

### Description:
If a maintainer does the following:

- Enable Publication module in the tools page in the overlay ;
- Navigate directly to the 'content' page (in the overlay) ;
- Click on 'Publicaton -> Add'

Then the form appears in the main frame, not the overlay, with an added fragment '#overlay-context='.
The fragement causes JQuery to crash, which in turns means the form doesn't work as expected.

Why JQuery crashes is not important here - the form should not have breaken out of the overlay.

The reason this is happening is that the list of admin paths is stored in the parent frame, and is not refreshed. So the Javascript code that decides whether to open links in the overlay or not does not know of the newly created publication paths.

Drupal issue https://drupal.org/node/2129815

**Comment by alycejenni** [comment]
this no longer appears to be an issue; closing
