### ISSUE TITLE
Add 'Other material' section under taxon treatments

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4806]
- Original ID: 3668
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: null

### Description:
Under 'treatments' apart from the Holotype and Paratypes users should be able to select a list (unlimited number of values) of specimens (preferably in the same way they create specimen tables).

The specimens should populate the element "type_status" in Pensoft's XML schema as 'Other material'

**Comment by benscott** [comment]
Publication module is now retired.
