### ISSUE TITLE
OG Notifications for all content

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4825]
- Original ID: 3687
 - Added by **----PSG_Webmaster ----**
 - Scratchpads URL: null

### Description:
Hi there,

Info on organic groups is very limited on your help pages, so I have a few questions and would be grateful if you could help.

1. How can I edit roles and permissions on this, please?  It says they are read-only and I cannot find anywhere where I can edit them: http://phasmid-study-group.org/node/5416/group

2. If you look at my user, I have a "group audience" value that it seem sonly admins have: http://phasmid-study-group.org/users/psgwebmaster

What does the "groups audience" value mean and how can I edit it/assign to other users?

3. Where can I control what update alerts get emailed out to members of this group?: http://phasmid-study-group.org/group?f[0]=im_group_audience%3A1

Thank you.

**Comment by alycejenni** [comment]
only outstanding issue is a feature request - please make a separate issue if this is still required.
