### ISSUE TITLE
Upgrade OG to 7.x-2.x (currently 7.x-2.5)

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4869]
- Original ID: 3733
 - Added by **Simon Rycroft**
 - Scratchpads URL: null

### Description:
In order to resolve some issues, including #4825, with the OG module, we should upgrade it to the 7.x-2.x branch/version.

**Comment by benscott** [comment]
Will be upgraded as part of #5617
