### ISSUE TITLE
Loading pages often very slow

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4888]
- Original ID: 3752
 - Added by **----PSG_Webmaster ----**
 - Scratchpads URL: http://phasmid-study-group.org/

### Description:
Loading pages onour site can often take several minutes, when at other times they load fine.  The slow response gives a very bad impression to users - anything we can do to address this, please?

**Comment by alycejenni** [comment]
fixed in 2015
