### ISSUE TITLE
anymals+plants documentation

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4930]
- Original ID: 3794
 - Added by **Simon Rycroft**
 - Scratchpads URL: null

### Description:
The anymals+plants tool needs sufficient documentation to enable a normal user to create a new anymals+plants group, and to start posting observations to that group using a Scratchpads form.  The documentation should link to the anymals+plants app and website.

**Comment by alycejenni** [comment]
I don't think this even exists anymore
