### ISSUE TITLE
Order of images in gallery

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4934]
- Original ID: 3860
 - Added by **----PSG_Webmaster ----**
 - Scratchpads URL: phasmid-study-group.org

### Description:
Morning :-)

Is it possibel to change the order of the images displayed here: http://phasmid-study-group.org/gallery ?  They seem to be date ascending, I'd like decsending so newest show first, please.

Thank you!
Natalie

**Comment by alycejenni** [comment]
For anyone who finds this later: Media Gallery and the various media types can be found under Content in the admin toolbar.
