### ISSUE TITLE
Cannot flag UK on Distribution map

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5037]
- Original ID: 3968
 - Added by **Stuart Ball**
 - Scratchpads URL: http://scathophagidae.myspecies.info

### Description:
Trying to indicate European distribution on the Google map under "Map" on Edit Taxon Description
Select "Region" - Selecting by country/subcountry (Level 4)
Click away on countries including "United Kingdom" (which actually selects GB - Northern Ireland has to be selected separately!). Map appears OK and as I want it.
Save

View the page via Scathophagid checklist - select species - Whilst the other countries I selected are indicated, Britain is *not* shown as grey.

Try to edit the taxon description, go to map, select Britain, save - Britain is still not shown!

**Comment by benscott** [comment]
This now works.
