### ISSUE TITLE
Slickgrid does not load next page when moving by editing

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5044]
- Original ID: 3975
 - Added by **Alice Heaton**
 - Scratchpads URL: 

### Description:
It's possible to scroll down the slickgrid by editing cell after cell. When this happens, the slickgrid does not load the next page of data, so the user gets to the end, waits for the data to be saved and reloaded, and then has to move the scroll bar to trigger the next page of data to load.

**Comment by alycejenni** [comment]
> Comment by **Alice Heaton**
> I think this might be working now

close enough; closing
