### ISSUE TITLE
Add fields to taxonomy

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5051]
[Ciliates](http://ciliateguide.myspecies.info)

 - Original ID: 3982
 - Added by **Katherine Bouton**
 - Scratchpads URL: 

### Description:
The main purpose of this site will be to refine the quality of the taxonomy and the version entered is definitely draft.  That makes it an edge-case because most Scratchpad users work with stable, preferred taxonomies.  To help with this there are a few additional fields that we need for this phylum.  Specifically:

Placement - to accomodate status terms like 'incertae sedis'.  Not much used in the big things, but I did discuss this with Dimitris towards the end of the year.

Fossil - to indicate fossil taxa.

Comment - to include snippets of information that cannot be immediately resolved.

**Comment by benscott** [comment]
New taxonomy fields can be added through the UI for individual sites.
