### ISSUE TITLE
Split GM3 fields into constituant parts in import file

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5102]
- Original ID: 4033
 - Added by **---- jcoliver ---- jcoliver**
 - Scratchpads URL: null

### Description:
In the Location content type, are latitude and longitude only stored in the Map field?  Is there any way these could be split into two fields (at least for point locations), corresponding to one of the two Darwincore terms (e.g. verbatumLatitude or decimalLatitude)?  (We could just add fields to the Content Type in our instance, but we would like to avoid mucking around with Scratchpads content types, if possible).

This is primarily a concern for import/export; we could format/parse data to deal with the POINT:(52.3542,-113.7556) format, but it would be nice to avoid such a step.

**Comment by benscott** [comment]
GM3 has been replaced now.
