### ISSUE TITLE
multiplication of media

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5147]
- Original ID: 4078
 - Added by **Yves BRAET**
 - Scratchpads URL: http://insectafgseag.myspecies.info/taxonomy/term/12427/media

### Description:
Sorry it is me again.
After to have enabled the species page I show a weird display.
At the high level (familly) http://insectafgseag.myspecies.info/taxonomy/term/11942/media
in the media tab, all the photos are diplayed in triplicate
At the level of subfamily and the genus, all photos are displayed in duplicate
http://insectafgseag.myspecies.info/taxonomy/term/12427/media
At the level of species, all is ok in the media tab.

Please could you fix this weird situation?

Thank you very much!!

**Comment by alycejenni** [comment]
this no longer appears to be an issue; closing
