### ISSUE TITLE
Media Gallery suddenly is displaying facets for "Terms" and "Taxonomic name"

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5150]
- Original ID: 4081
 - Added by **Nicholas Williams**
 - Scratchpads URL: http://ethoikos.myspecies.info/

### Description:
The Gallery Tab. As of this afternoon the list of facets in the right menu bar displays two new facets placed above the facet "Gallery" pushing our links to customized galleries way down on the menu. The two new facets display identical lists of taxonomic terms from our taxonomies. If this is a permanent solution, how do I remove or move the two new facets? I think it is much easier to use the normal "Search" if you are looking for media tagged with a taxonomic term.
Regards
Nicholas

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/746/New%20gallery.jpg

**Comment by alycejenni** [comment]
this appears to have been done; closing
