### ISSUE TITLE
Unexpected opening of the window download

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5189]
- Original ID: 4121
 - Added by **yves BRAET**
 - Scratchpads URL: http://doryctinaekey.myspecies.info/taxonomy/term/349#overlay=node/1765/edit%3Fdestination%3Dadmin/content/spm

### Description:
Dear team,

On the Taxon description page, when creating a new taxon desciption, I enter the taxonomic in the field Taxonomic name. But each time when I validate (by enter, e.g.) the choice the download window open. So I need to cancel this new window before to continue the edition of the new taxon description.
This seems recent as comportment.
You can also simply put the cursor in the field Taxonomic name and push on enter. The window appear again.

Please could you make something to avoid this?

Thank you very much for your help!

**Comment by alycejenni** [comment]
this is still relevant

**Comment by PaulKiddle** [comment]
2 issues here:
 - Taxonomic name select should not let the enter propagate while the dropdown is open
 - Media select button should not be input type=submit
