### ISSUE TITLE
DwC-A export includes duplication of authority

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5193]
- Original ID: 4125
 - Added by **Simon Rycroft**
 - Scratchpads URL: 

### Description:
Solanum dulcamara in http://solanaceaesource.org/dwca.zip has 'L., L., L., L., and L., “Sp. Pl. 185. 1753.”, 1753.' as the authority - this is clearly wrong.

**Comment by PaulKiddle** [comment]
Due to a bug in feeds module which is since fixed. Just need to update biblios to remove duplicate authors.
