### ISSUE TITLE
Add XML export of Publication

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5195]
- Original ID: 4127
 - Added by **---- jcoliver ---- jcoliver**
 - Scratchpads URL: bembidion.info

### Description:
Would it be possible to allow registered users to download the XML file that would normally be sent to Pensoft when using the 'Publish' option for a Taxonomic Paper (assuming it _is_ an XML file that is sent to Pensoft)?

**Comment by benscott** [comment]
Publication module is now retired.
