### ISSUE TITLE
Visualise uncertainty of occurrence records

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5203]
- Original ID: 4135
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: null

### Description:
Many specimen record geographical coordinates are entered with relevant uncertainty levels. This is captured in the corresponding field in the specimen/observation content type. 

It would be great if we could visualise this uncertainty as a circle around the specimen point using the google.maps.Circle function.

**Comment by PaulKiddle** [comment]
Use L.CircleMarker with radius instead of Marker https://github.com/Leaflet/Leaflet.markercluster/issues/148
