### ISSUE TITLE
Unable to edit locality in location slickgrid view

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5238]
- Original ID: 4171
 - Added by **lukas.scharer lukas.scharer**
 - Scratchpads URL: http://macrostomorpha.info

### Description:
Now that I have 'discovered' the nicer slickgrid view I seem to be unable to edit some, but not all. of the entries in the locality field in location slickgrid view (i.e. here http://macrostomorpha.info/#overlay=admin/content/slickgrid/location). Although all the rows have text in that field, when I click on some of them the dialog 'pretends' that the field is empty, while in others it shows me and lets me edit the correct text. I initially thought it was linked to the duplication issue, but it does not seem evidently so. Any ideas what's going on?

**Comment by alycejenni** [comment]
still an issue

**Comment by PaulKiddle** [comment]
Appears this might be linked to translation.
Grid items that work correctly are entered as "und" language, whereas ones that don't have "en".
