### ISSUE TITLE
Increase region resolution for all countries

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5281]
- Original ID: 4215
 - Added by **Simon Rycroft**
 - Scratchpads URL: null

### Description:
The current region selection we have allows the selection of relatively small areas for some countries (especially the UK), but not for others (e.g. Russia).  We should look at including an alternative source of political boundaries, such as http://www.gadm.org/.

**Comment by PaulKiddle** [comment]
Probably not worth doing for the energy we'd put in. Can always reopen this if someone wants it.
