### ISSUE TITLE
Biblio - taxonomic name

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5291]
- Original ID: 4225
 - Added by **nieukerken nieukerken**
 - Scratchpads URL: http://nepticuloidea.info/

### Description:
When I import biblio, I can import keywords longer than 1000 characters, which automatically translate into taxonomic names and thus link to these taxa.

However, whenever I want to edit such a record I get an error regarding the keyword length.
This is also the case when manually entering a reference, and then I get the same error for taxonomic name.

This is unfortun ate,. since many publications refer to many species, and I woulsd like to link those all, even if the names exceed 1000 characters. 
Is it possible to mend this? 

Erik

**Comment by alycejenni** [comment]
fixed in 2015
