### ISSUE TITLE
Error trying to import names

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5296]
- Original ID: 4230
 - Added by **---\n- millerse\n ---\n- millerse\n**
 - Scratchpads URL: http://mormyrids.myspecies.info/

### Description:
I have been unable to import taxon names from the lifedesk classification to Scratchpad.  It gets to a certain point and then stops.  The error message that I get is this: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'revision_id

I might have brought this to you guys before but I could use all the help I can get. 

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/794/TEMPLATE-import_into_mormyridae_xls%20(4).xls
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/795/20140818_1559_mormyrids_1_export.xls

**Comment by jrdh** [comment]
Just retried this, seems to be working fine now.
