### ISSUE TITLE
Cron is failing to run on solanaceaesource.org

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5305]
- Original ID: 4239
 - Added by **Simon Rycroft**
 - Scratchpads URL: 

### Description:
Cron is failing to run completely on the solanceaesource.org website.  This is possibly as a result of the size of the site (number of terms and number of nodes).

**Comment by alycejenni** [comment]
"fixed" is concerning but closing anyway
