### ISSUE TITLE
Pensoft writing tool in eMonocot scratchpad

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5307]
- Original ID: 4241
 - Added by **Lauren Gardiner**
 - Scratchpads URL: http://pong.e-monocot.org/publication/1#overlay-context=

### Description:
Hi team, 

I'm trying to play around with the Pensoft Writing Tool in my Palms of New Guinea scratchpad to see how it works, what info you need and can include, how flexible it is, and what the 'product' looks like during the process and at the end, and if you can export it in different formats. 

I am currently getting the message 'It is not currently possible to publish this to the Pensoft Writting Tool. We hope to have this working in the near future.' - is it not possible to use this at the moment? I really hoped to do so!

**Comment by benscott** [comment]
Publication module is now retired.
