### ISSUE TITLE
Terms link to the zh-hans term page

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5328]
- Original ID: 4262
 - Added by **Eli Sarnat**
 - Scratchpads URL: http://antkey.org/taxa/anergates-atratulus

### Description:
By Scratchpads Team on behalf of Eli Sarnat.

Currently all of the terms on the http://antkey.org/taxa/anergates-atratulus page link to the Chinese version of the taxonomy term page, when they obviously should link to the English versions.

**Comment by alycejenni** [comment]
unable to recreate + very old issue; closing
