### ISSUE TITLE
Broken link to run Taverna workflow on taxon pages

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5340]
- Original ID: 4281
 - Added by **Edward Baker**
 - Scratchpads URL: http://bio.acousti.ca/taxonomy/term/247/descriptions#

### Description:
The 'Run a workflow' link on taxon page descriptions gives a 404 error.

**Comment by benscott** [comment]
Link no longer present - appears fixed.
