### ISSUE TITLE
Empty type status value created in imported specimens

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5392]
- Original ID: 4338
 - Added by **Nicholas Williams**
 - Scratchpads URL: http://ethoikos.myspecies.info

### Description:
I have imported a few new specimen records. Links to these now appear on the taxon overview page.  
Example: http://ethoikos.myspecies.info/fauna-checklist-la-selva/operophtera-brumata

**Comment by alycejenni** [comment]
fixed in 2015
