### ISSUE TITLE
Latest CKEditor does not support Media plugin

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5397]
- Original ID: 4343
 - Added by **Gontran Sonet**
 - Scratchpads URL: jemu.myspecies.info

### Description:
Dear Scratchpad team,
All images are missing when I try to edit the pages of all three scratchpads jemu.myspecies.info, bebol.myspecies.info and ecbol3.myspecies.info. All images are present on the normal display but they disappear on the editable views. If I save a clone of the editable version, then the new page lacks all pictures. 

I tested different internet browsers, computers, scratchpads (v2 and v1) and I always face the same problem.

Examples from all three scratchpads:
http://jemu.myspecies.info/node/4550#overlay=node/4550/edit
http://bebol.myspecies.info/node/103#overlay=node/103/edit
http://ecbol3.myspecies.info/content/general-information#overlay=node/15/edit

Could you help me? 
Thank you for your help!

**Comment by alycejenni** [comment]
this no longer appears to be an issue; closing
