### ISSUE TITLE
Testing of morphbank_harvest module

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5398]
- Original ID: 4344
 - Added by **Simon Rycroft**
 - Scratchpads URL: null

### Description:
"Jeff Oliver":http://ib.oregonstate.edu/faculty/oliverj/Jeffrey-C-Oliver has created a module which imports images from Morphbank for taxon names. The module will be useful for all Scratchpads, so should be tested prior to making it available to all. The module can be enabled (by an admin) on any Scratchpad.

**Comment by alycejenni** [comment]
this module has been included for 4y now so assuming this is no longer needed; closing
