### ISSUE TITLE
DwC-A export does not include taxonomic name GUID?

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5407]
- Original ID: 4353
 - Added by **---- jcoliver ---- jcoliver**
 - Scratchpads URL: bembidion.info

### Description:
It appears the DwC-A export of the taxonomy of our Scratchpad uses different identifiers for the classification.txt file.  All the identifiers appear to be Scratchpads-generated, but we are generating GUIDs ourselves, and importing them to Scratchpads.  Compare the identifiers between an excel file export (derived via the 'Import' mechanism) and the DwC-A classification.txt:

Taxonomic name: Bembidion festivum
Taxonomic name GUID: bembidion.info:taxon-concepts:000419
ID in classification.txt: 2582b6d2-2a36-4c81-84cc-044a2e100abf

Are the identifiers in the excel file referring to different objects from those in the classification.txt?

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/853/classification.txt
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/854/taxonomy_importer_bembidiina_xls.xls

**Comment by alycejenni** [comment]
fixed in 2015
