### ISSUE TITLE
Include taxonomic name GUID in taxon description importer file?

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5420]
- Original ID: 4366
 - Added by **---- jcoliver ---- jcoliver**
 - Scratchpads URL: bembidion.info

### Description:
The Excel file with taxon descriptions includes a Taxonomic name (GUID) field, but no values are included in that field (the field Taxonomic name (Name) does contain information though).  Is it possible to fill in the taxonomic name guid field - we would like to use this as a source of information and would like to avoid having to search through all the term names to identify the corresponding term in the taxonomy import file.

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/864/node_importer_specimen_observation_xls.xls

**Comment by alycejenni** [comment]
fixed in 2015
