### ISSUE TITLE
unable to import a biological classification

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5426]
- Original ID: 4372
 - Added by **Lynne Forster**
 - Scratchpads URL: http://lissotes.myspecies.info/#

### Description:
Hi!
Apologies if you are receiving this issue a second time. Last time when I tried to send it wanted me to log in again but wouldn't accept my details, then vanished.

I am trying to import a biological classification from EOL so I can get something ready for the group. I get the following message:
'The EOL classification service (http://services.eol.org/lifedesk/service.php) does not appear to be running. Please try again later.' 
I get the same message if I try the GBIF option and have been trying for a couple of weeks, icluding deleting the page and creating a new one in case I had introduced a bug somehow.

I searched your help pages but found no clue for solving this
problem.

I appreciate any help you may offer - or a help link that I have missed.

Regards,
Lynne

**Comment by alycejenni** [comment]
fixed in 2015
