### ISSUE TITLE
Statistical and graphic capacities of Scratchpads

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5432]
- Original ID: 4378
 - Added by **test test**
 - Scratchpads URL: null

### Description:
Dear Team,

I wonder if it could be possible to realize some basic stats of graphics using build-in fonctions/module in Scratchpad?

For example, from a table of specimens, to produce a pie chart (linked to a specific page or taxa level) or to calculate a % each taxa among the whole database.

If not, I presume that it is always possible to export the specimen database in XLS sheet, make some calculation outside, produce graphic outside and import this graphic as a image file on the desired page. Am I right?

Best wishes
Yves

**Comment by alycejenni** [comment]
this was completed & released in 2015
(presumably the Views::Charts module)
