### ISSUE TITLE
Resizing of field columns should persist

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5436]
- Original ID: 4382
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: 

### Description:
It is very frustrating when a user needs to resize every time the field columns to edit or view the matrix. The default width of the columns is very small and does not allow any meaningful overview of the matrix. When a user resizes a column this needs to persist on all subsequent views/edits.

Also, at a view mode columns are not resizable at all. 

If persistent resizing is not possible, at least we should make the columns by default wider or at the minimum size to present all contents.

This issue should be consider important as it heavily minimizes the functionality of the editor.   

see:
http://dev-3231-nextphase-new.taxon.name/character-editor-project/1#overlay-context=character-editor-project/1&overlay=character-editor-project/1/edit
and
http://dev-3231-nextphase-new.taxon.name/character-editor-project/1#overlay-context=character-editor-project/1

**Comment by alycejenni** [comment]
duplicate of #5204
