### ISSUE TITLE
Addition of Access Database (.accdb) to permitted file extensions

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5440]
- Original ID: 4386
 - Added by **Paul Sokoloff**
 - Scratchpads URL: http://arcticplants.myspecies.info/

### Description:
Currently, Access Databases are not on the list of permitted extensions allowed for upload to Scratchpads.  Is it possible to add the .accdb extension to the list of permitted uploads - we use Access to create herbarium specimen labels, and would like to make this utility available to our collaborators.

**Comment by benscott** [comment]
ZIP workaround is sufficient if not ideal.
