### ISSUE TITLE
Image bulk editor: change title without changing filename

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5458]
- Original ID: 4404
 - Added by **Eli Sarnat**
 - Scratchpads URL: antkey.org

### Description:
It would be very useful to be able to change the title of an image without changing the filename. That would allow for the filename to remain constant even if the title needs to be changed.

**Comment by alycejenni** [comment]
excel file doesn't have separate fields for filename and title so they both get changed.
