### ISSUE TITLE
spammers

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5459]
- Original ID: 4405
 - Added by **Rita Adele Steyn**
 - Scratchpads URL: http://sami.myspecies.info/

### Description:
Is anyone else getting spammed with user requests from email addresses ending with drupaler.org? I have had 3 such requests in the last week, no reply to follow up emails, no real information given in terms of names etc. I have blocked and then deleted their user accounts, and have done a little research and see that the same problem is popping up on the actual Drupal site. Just an FYI for anyone experiencing the same problem, but any advice is appreciated. Thanks.

**Comment by alycejenni** [comment]
see #5687
