### ISSUE TITLE
Spaming..? 

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5466]
- Original ID: 4412
 - Added by **Chris Georgiadis**
 - Scratchpads URL: http://greekants.myspecies.info/

### Description:
I received a request for membership from a completely unknown 'source' with minimal, dodgy information. Is there a possibility that this is a malware request? 

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/881/people.jpg

**Comment by alycejenni** [comment]
duplicate of #5520 and #5687
