### ISSUE TITLE
Excel imports are attempted even when no local file is selected, returning 'no new nodes'

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5469]
- Original ID: 4415
 - Added by **Aubrey Moore**
 - Scratchpads URL: guaminsects.myspecies.info

### Description:
If one forgets to select a local file by pressing the 'Browse...' button,but presses the 'Import' button instead, an import is attempted and the message 'no new nodes' is returned by the server. Would be best if the local web page checks for a valid local file before sending request to server.

**Comment by alycejenni** [comment]
a 'please upload a file' message is now displayed if no file has been selected.
