### ISSUE TITLE
missing specimens under specimens tab on taxon page

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5470]
- Original ID: 4416
 - Added by **Aubrey Moore**
 - Scratchpads URL: guaminsects.myspecies.info

### Description:
I tagged 31 specimens with the taxon term "Rhyparida". However, only one of these is listed under the specimens tab on the taxon page (http://guaminsects.myspecies.info/taxonomy/term/4150/specimens)

**Comment by scratchpads** [comment]
Comment by ****

Test reply
