### ISSUE TITLE
LucidKey

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5474]
- Original ID: 4420
 - Added by **Azzah Al Jabri**
 - Scratchpads URL: http://omanflora.myspecies.info/content/acanthaceae-key

### Description:
I uploaded file from lucid key builder and when I open it I got an error!!!

Also, I lost the language switcher on the front page!!!

**Comment by alycejenni** [comment]
fixed in 2015
