### ISSUE TITLE
Editing front page returns a blank screen

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5475]
- Original ID: 4421
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: http://iczn.org/

### Description:
Trying to edit the home page of the site returns a blank screen. Clearing the caches did not seem to correct the issue

http://iczn.org/scratchpads-front/edit

**Comment by alycejenni** [comment]
¯\_(ツ)_/¯
