### ISSUE TITLE
Webform placeholders broken

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5481]
- Original ID: 4427
 - Added by **----PSG_Webmaster ----**
 - Scratchpads URL: http://phasmid-study-group.org/

### Description:
It's only just been brought to my attention, but has apparently been an issue since 7th July.  The default values for logged-in user name and surname are not translating to their values (just showing the placeholder text) and same for one of our group_additional_info fields.  Please see links below for examples, although ALL our forms are affected:

You need to be logged-in to see the second link, but place-holders show whether you are logged in or not, which is bizzare.

Shows place holders instead of values for names:
http://phasmid-study-group.org/content/submit-question-faqs

Shows USERNAME not actual name/surname and additional info field shows place holder:
http://phasmid-study-group.org/content/e-mail-livestock-co-ordinators

Please can you advise fix ASAP?

Thank you very much,
Natalie

**Comment by alycejenni** [comment]
this is still an issue, though the forms now do not display if you're not logged in.
as a logged in user:
![image](https://user-images.githubusercontent.com/23579762/54528686-8e5d6f00-4975-11e9-956a-847baae147f6.png)
