### ISSUE TITLE
Add option to always show maps on species pages if GBIF overlay is enabled.

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5485]
- Original ID: 4431
 - Added by **Jen Hammock**
 - Scratchpads URL: mormyrids.myspecies.info

### Description:
This was posted originally during v1, I think, by Irina: http://support.scratchpads.eu/issues/1084

John Sullivan (mormyrids.myspecies.info) and I are both having the same problem now in v2. GBIF points sometimes appear but only after a polygon has been added to a map. Then they sometimes disappear if the polygon is edited.

I think what we want is simply the functionality described in http://help.scratchpads.eu/w/What%27s_new_in_Scratchpads_2.0%3F

If GBIF is activated as a data provider in the Tools section, then the GBIF data should display by default. If zooming the map appropriately is too much work, that can be left to the user, but the capability to fetch GBIF data clearly exists. It just doesn't seem to behave consistently.

**Comment by PaulKiddle** [comment]
Part of #6084 - pending review changes & merge
