### ISSUE TITLE
Update the Lucid applet to the new signed version.

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5492]
- Original ID: 4438
 - Added by **Azzah Al Jabri**
 - Scratchpads URL: http://omanflora.myspecies.info/en

### Description:
I have a problem to during opining the lucid key that I uploaded to the website. Can you help me fix this problem as soon as possible? 

### Attachments:
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/890/Screen%20Shot%201436-10-10%20at%2013.02.05.png
 - https://github.com/NaturalHistoryMuseum/scratchpads2/blob/issue-attachments/892/Screen%20Shot%201436-10-10%20at%2017.12.25.png

**Comment by alycejenni** [comment]
probably fixed as related issues were raised later (e.g. #5505); closing
