### ISSUE TITLE
updates and new pages lost

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5497]
- Original ID: 4443
 - Added by **Gontran Sonet**
 - Scratchpads URL: http://jemu.myspecies.info/

### Description:
Dear Scratchpad team,
In early July I updated some pages on http://jemu.myspecies.info/ and create one or two new pages but all this seems to be lost. Only the uploaded pictures are still in the library...
Is there an explanation for this?
Thank you very much.

**Comment by alycejenni** [comment]
was already closed in redmine
