### ISSUE TITLE
Display points from GBIF on Species maps

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5508]
- Original ID: 4454
 - Added by **Simon Rycroft**
 - Scratchpads URL: null

### Description:
We should display actual points from GBIF on the species page maps. Each point should be clickable, which is not possible using the GBIF overlay. When clicking on a point, information specific to that point should be displayed. This could perhaps work by interfacing with GBIF from the client side, dynamically adding the points to the map (this would prevent any additional load on our servers), although this would require investigation.

**Comment by PaulKiddle** [comment]
Instead of rendering all of the points, could do a reverse search on map click for the area around the clicked coordinate - occurrence search + taxonKey and geometry params

https://api.gbif.org/v1/occurrence/search?geometry=POLYGON((30.1%2010.1,%2040%2040,%2020%2040,%2010%2020,%2030.1%2010.1))

**Comment by benscott** [comment]
Rendering actual points would need server-side rendering, a lot of work and server load for limited gain.
