### ISSUE TITLE
images uploaded to species pages show up as doubles

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5518]
- Original ID: 4464
 - Added by **John P. Sullivan**
 - Scratchpads URL: mormyrids.myspecies.info

### Description:
This has been an issue for some time and I thought I saw someone else post this, yet the problem persists.

When you upload an image and link it to a species, two thumbnails of it appear in the media window.

E.g. http://mormyrids.myspecies.info/en/taxonomy/term/285/media#

**Comment by PaulKiddle** [comment]
Closing in favour of #5737
