### ISSUE TITLE
error message when editing information on names

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5521]
- Original ID: 4467
 - Added by **Jens G. Rohwer**
 - Scratchpads URL: http://lauraceae.myspecies.info/category/lauraceae-taxonomy/lauraceae/mezilaurus/mezilaurus-itauba/mezia-itauba#overlay=admin/structure/taxonomy/lauraceae_taxonomy/

### Description:
When I click on "Save" after having edited the information on a name in my taxonomy, it takes a while and then the following error message appears:

An AJAX HTTP error occurred

or

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Internal Server Error
ResponseText:

Apparently the information has been saved, though.

**Comment by alycejenni** [comment]
unable to recreate; assume this has resolved itself as it is an old issue
