### ISSUE TITLE
Closing down a scratchpad

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#5585]
- Original ID: 4533
 - Added by **Richard James Burkmar**
 - Scratchpads URL: http://tombio.myspecies.info/

### Description:
Hello,

This is a request to close down a scratchpad that I created: http://tombio.myspecies.info/

Thanks for the opportunity to create and use a scratchpad on this platform - it was a great help to our project.

Rich Burkmar

**Comment by edwbaker** [comment]
Completed.
