### ISSUE TITLE
Disappearing content for non-auth users

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5598]
Mosquito Taxonomic Inventory

"The first page of Culicidae was missing content, and so was the page for subgenus Culicinae".  

Content was available for maintainers.

**Comment by NeonPaul** [comment]
I assume this refers to these pages:
 - http://mosquito-taxonomic-inventory.info/simpletaxonomy/term/6045
 - http://mosquito-taxonomic-inventory.info/simpletaxonomy/term/6060
?

Appears to be fixed now?
