### ISSUE TITLE
Missing links between literature and taxonomy

### ISSUE THREAD

**Issue by essvee** [NaturalHistoryMuseum/scratchpads2#5599]
The literature module in British Fleas isn't showing the taxonomic name filter:

http://britishfleas.myspecies.info/biblio

It's also not aggregating references above the interaction level, i.e., can't see all references for interactions involving a particular species without going into every interaction record.

**Comment by benscott** [comment]
The taxonomic name filter isn't displaying as none of the literature items are tagged with a term. If I tag an item, it does display properly.  Maybe the data has got corrupted - where these records ever tagged?

For the ecological interactions, you can filter by taxonomic term e.g. http://britishfleas.myspecies.info/interactions?f%5B0%5D=im_field_taxonomic_name%3A413

Is that what you were after? There does seem to be another bug stopping the search submitting automatically (raised another issue #5828) so it seemed like it wasn't working.
