### ISSUE TITLE
No error when importing invalid DOI...

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5605]
.... just a messy page.

![screenshot 2018-08-15 at 13 39 08](https://user-images.githubusercontent.com/929684/44148543-b7aa2ab2-a090-11e8-94ff-c1dc5c51bb56.png)

**Comment by benscott** [comment]
This seems to be working - correctly fails validation if it's not a proper DOI.  

<img width="731" alt="image" src="https://user-images.githubusercontent.com/81690/52644939-b3267880-2ed7-11e9-9018-08ccebaf8a41.png">

Could you have another try and see if it works now?

**Comment by edwbaker** [comment]
Yes - seems fine now.


On 12 Feb 2019, at 15:07, Ben Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems to be working - correctly fails validation if it's not a proper DOI.

[image]<https://user-images.githubusercontent.com/81690/52644939-b3267880-2ed7-11e9-9018-08ccebaf8a41.png>

Could you have another try and see if it works now?
