### ISSUE TITLE
Plans on updating 3rd party modules

### ISSUE THREAD

**Issue by cwchong** [NaturalHistoryMuseum/scratchpads2#5617]
Hi, any plans on updating 3rd party modules such as the CKEditor/CKFinder modules?

They are very dated at the moment and possibly vulnerable.

In particular, scanning the repo via Avast threw a Trojan malware alert on this file: 
sites/all/modules/contrib/ckeditor/ckfinder/core/connector/php/php5/CommandHandler/Init.php

That file itself doesn't seem to be a problem, so it probably matches the signature of a vulnerable version that has since been patched (my guess).

**Comment by benscott** [comment]
:thumbsup:
