### ISSUE TITLE
Enable utf8mb4 database support

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5619]
Status report error in 2.9.2

**Comment by NeonPaul** [comment]
Drupal guide: https://www.drupal.org/node/2754539
Drush command: https://www.drupal.org/project/utf8mb4_convert

**Comment by benscott** [comment]
utf8mb4 tested locally & have added the script to convert tables to utf8mb4.  I will convert a few sites first after the release, before doing a full roll out.

**Comment by jrdh** [comment]
@benscott what's the status with this one? Did the sites you tested work? Did it get deployed to all sites or is that still left to do?

**Comment by jrdh** [comment]
Seems like all sites on 2.9.11 have `utf8mb4` in their settings.php files so they must be using it. Gonna close this.

**Comment by PaulKiddle** [comment]
This doesn't necessarily mean the databases themselves are utf8mb4. There is a warning in the status report that we currently mask (107e93d4c9eb082618cc6b778da7ca5ec9383adc)

Though not sure how much of a priority this as as everything seems to function ok with utf8mb3
