### ISSUE TITLE
HTTPS on bioacoustica

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5627]
Enable HTTPS on this site.

**Comment by edwbaker** [comment]
Even getting spam about this now!

![IMG_2007](https://user-images.githubusercontent.com/929684/103366556-e027a880-4aba-11eb-8c4a-5d66ad883715.jpeg)

**Comment by Archilegt** [comment]
Sounds like someone joking and trying to help at the same time. Good one! ;-)
