### ISSUE TITLE
Taxonomy search should only show autocomplete results from biological classifications?

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5631]
At present shows results from all vocabularies.

**Comment by Archilegt** [comment]
@PaulKiddle , hi. Could you please take a look at this issue again? Maybe it is already solved?

**Comment by PaulKiddle** [comment]
I'm not sure - @alycejenni is up next to work on scratchpads so maybe she might take a look
