### ISSUE TITLE
Default zoom on maps with single point 

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5635]
The default zoom is generally too deep, and does not show any geographic context, e.g. http://bio.acousti.ca/taxonomy/term/6097/maps

![screenshot 2018-10-12 at 12 44 52](https://user-images.githubusercontent.com/929684/46867365-a0624100-ce1c-11e8-9769-4eee40942f67.png)

**Comment by PaulKiddle** [comment]
Done as part of  #6093
