### ISSUE TITLE
Issues tab - show recently opened & recently closed issues

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5645]
Update issues tab so it shows:

Recent open issues
Recently closed issues.

Maybe add two tabs? - Colour closed issues green & show close date - raises awareness project is active & being worked on.

**Comment by therobyouknow** [comment]
Moved to Scratchpads Evolution, see https://github.com/NaturalHistoryMuseum/scratchpads-evolution/issues/15#issuecomment-1339193925 for reason.
