### ISSUE TITLE
Map region selection

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5652]
Region selection in maps editing interface no longer works, as the Google Geocode API is no longer available for free.  Replace lookup with free / open source API as part of the google maps replacement work.

**Comment by marcogaiani** [comment]
> Region selection in maps editing interface no longer works, as the Google Geocode API is no longer available for free. Replace lookup with free / open source API as part of the google maps replacement work.

Ben could the polygons be stored in the database and have users select the geographical units form a dropdown or similar and then show the maps accordingly. I have done it before with Leaflet and Views

**Comment by PaulKiddle** [comment]
Fixed in latest release
