### ISSUE TITLE
Open street map tile language

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5653]
Open street map tiles use local language. 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/81690/47850024-b9329680-ddcb-11e8-81e4-6bcd245f244e.png">

**Comment by PaulKiddle** [comment]
Doesn't appear to be configurable using OSM tiles, might consider switching to [Open Map Tiles](https://openmaptiles.org/languages).

**Comment by PaulKiddle** [comment]
Probably makes sense to do this alongside #5890 
https://openmaptiles.org/docs/website/leaflet/
https://www.maptiler.com/cloud/plans/
https://cloud.maptiler.com/maps/hybrid/
https://github.com/mapbox/mapbox-gl-leaflet

**Comment by PaulKiddle** [comment]
Done in #6093
