### ISSUE TITLE
Allow cc licence change/ownership change to be reflected in updated DwCA file

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#5666]
The person who set up aracnids.myspecies.info has left, the ownership has changed hands. GBIF citation/author is listed as the original user and needs to be updated.

Also we need to prevent submitting `ShareAlike` licences, GBIF doesn't allow them.

**Comment by benscott** [comment]
Added option to select maintainer to use in DwC-A.  

GBIF license selections should be a separate configurable as part of #5600, so a maintainer can create a DwC-A with whichever licence they want, that's not shared with GBIF.

**Comment by PaulKiddle** [comment]
This is all rolled into the PR #6110
