### ISSUE TITLE
Upgrade to Drupal 8

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#5672]
Drupal 7 reaches [end of life](https://www.drupal.org/core/release-cycle-overview#drupal-7-eol) in November 2021.
Drupal 9 will be released 2020 but will be [an easier upgrade](https://www.drupal.org/node/2941566) than 7->8, so worth not waiting too long.

**Comment by benscott** [comment]
Scratchpads upgrade to Drupal 8/9 will be a huge task. Future upgrades will be part of the VRE alignment proposals, but not moving to a new version of Drupal.
