### ISSUE TITLE
Scratchpads Classification Service doesn't work?

### ISSUE THREAD

**Issue by s-bolshakov** [NaturalHistoryMuseum/scratchpads2#5674]
I try to import taxonomy from Catalogue of Life via Scratchpads Classification Service.
But the service doesn't search nothing for the requested taxon.
Does the service from [Issue 5429](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5429) work?
![image](https://user-images.githubusercontent.com/36799292/48798906-d09fd800-ed16-11e8-8fee-c686a7ae3ac8.png)
![image](https://user-images.githubusercontent.com/36799292/48798971-0b097500-ed17-11e8-993b-16094ce339ad.png)

**Comment by NeonPaul** [comment]
Thanks for highlighting this. The classifications server has stopped working at some unknown point in time and will need to be restored.

**Comment by RPO45** [comment]
Hello,
same issue for me ! Any idea to restore it ? (Have I to change any configuration or do it depends only on internal functions ?)

**Comment by NeonPaul** [comment]
I'm afraid this is work the Scratchpads team has to do - although it may be a little while before we get around to this as there are a number of bugs that came from the server move.

**Comment by RPO45** [comment]
OK, thanks for your answer. I will wait, no problem.
Also I have seen that EOL recently change its website (and probably some backend). It's maybe a supplementary reason ?

**Comment by NeonPaul** [comment]
Thanks, I think this is unrelated though.

**Comment by RPO45** [comment]
Hello, is there any news about this bug correction ? (currently unable to work on my Scratchpad website project without this option...).
Best

**Comment by benscott** [comment]
I have just started investigating the bug & will post updates here.

**Comment by RPO45** [comment]
OK many thanks for your help !

**Comment by benscott** [comment]
The catalogue of life classification service is operational again.  It's been restored to its previous state so the data is from 2015, but we will update it to the latest 2018 snapshot soon - See #5817.
