### ISSUE TITLE
Some images not showing

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5679]
Some images are suddenly not showing on the home page and other pages.

On Contents list their icons have ? on them.
![images](https://user-images.githubusercontent.com/44700406/48937959-66ef1c00-ef18-11e8-9621-f31f5b2d4f84.jpg)

**Comment by benscott** [comment]
Sorry about that - it's working for me now.  Could try it again please?

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/81690/48938446-1f14c880-ef09-11e8-80fc-809ce90425b0.png">

**Comment by annanc14** [comment]
Yes, thanks. It seems to be working again. Must have been temporary....

**Comment by benscott** [comment]
This should be working now - could you test again please?

<img width="817" alt="image" src="https://user-images.githubusercontent.com/81690/48939666-e5de5780-ef0c-11e8-9a31-d038c7078d7f.png">

**Comment by annanc14** [comment]
Thanks very much. That page is fine now too...

**Comment by gsonet** [comment]
dear Scratchpad team,
I have the same problem with nearly all pages of the website: http://jemu.myspecies.info/ and the one of my colleagues: http://bopco.myspecies.info/services
Is it possible to fix this?
Thank you very much!

**Comment by benscott** [comment]
Both sites fixed - apologies for the bug.

**Comment by gsonet** [comment]
Thank you for your fast reaction!

**Comment by Morjens123** [comment]
Seems we have the same problem with disappearing images with our site: http://pistiaistyoryhma.myspecies.info

**Comment by benscott** [comment]
@Morjens123 - Sorry about that. Your site is now fixed as well.

**Comment by Morjens123** [comment]
Thank you, sir!

**Comment by Paul-Cannon** [comment]
I have had this issue with http://fungi.myspecies.info also (and with descriptions too). I think that I've re-input all of the affected data now but thought you should know. 

A related matter may be that the counter for uploaded files on the Content page doesn't seem to be working any more.....

Best wishes
Paul

**Comment by Paul-Cannon** [comment]
Counter is now working again...

**Comment by benscott** [comment]
@Paul-Cannon - Our apologies, yours was one of a few sites that had file links corrupted in the transfer to new servers.  We have rolled out a fix for this on all affected sites now, so if there's any more on your site you haven't fixed manually let us know and we'll apply it.

**Comment by gsonet** [comment]
dear Scratchpad team,
Also on this page: http://jemu.myspecies.info/jemu-1
Some pictures are not displayed. Is it possible to fix this?
Thank you very much!

**Comment by alycejenni** [comment]
All images now appear to be displayed; closing.
(If this is incorrect please re-open the issue)
