### ISSUE TITLE
Species Descriptions Disappeared

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5681]
Two species descriptions that I uploaded yesterday and on the 21st have disappeared.

The species no longer exist in the species taxonomy terms either. It's like the terms have been deleted, but I definitely didn't do that.

Buteo rufinus
Ardea alba

Is there any way to go back to a previous version of the site, while still saving the work I did today?

Thanks

**Comment by benscott** [comment]
Sorry, your site should have been in read only mode yesterday to prevent this.  I'll see if I can sync across those two species description.

**Comment by annanc14** [comment]
Thanks very much... that would be great....

**Comment by annanc14** [comment]
Hello. Do you think it will be possible to sync those two species description back into the site? Or should I upload them again? 

Thanks

**Comment by benscott** [comment]
Those have both been copied across, along with the Buteo genus.

**Comment by annanc14** [comment]
The species names have appeared in the taxonomy again, but the Descriptions are still empty. Do you think they will update in time, or has something gone wrong? Thanks....

**Comment by alycejenni** [comment]
descriptions appear to be visible again; closing
