### ISSUE TITLE
Remove libraries & contrib modules from source control

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#5686]
Libraries should be downloaded with composer (which is automatically run by aegir for new platforms).

Contrib modules can be downloaded using drush make  - add them to the scratchpads2.make.yaml file and run `drush make --no-core scratchpads2.make.yml .` inside the platform directory. Could even remove core files if we so desire.

This will need the scratchpads-create-platform task to be updated and the docker install script.

This will also resolve #5617

**Comment by benscott** [comment]
This is a much nicer way of doing things, every release becomes more complex as we'll have to test every updated contrib modules and all dependencies.  At this stage of the project, best to keep the process we have. But yep we do need to update all contrib modules - keeping #5617 to track the updates.
