### ISSUE TITLE
Big increase in spam user registrations in the last week

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5687]
Across a range of sites.

**Comment by NeonPaul** [comment]
This is a continuing problem #5520 #5466 #5550
The current captcha system must be pretty old, a more modern system like Google's reCaptcha v3 might help stem this problem.

**Comment by benscott** [comment]
Added the Spamicide module, see if that has better results.

**Comment by alycejenni** [comment]
no point in having two of these spam registration issues open; closing this one in favour of the older one (#5520)
