### ISSUE TITLE
Species pages - cannot access EOL service

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5688]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/81690/49151138-00e30a00-f307-11e8-8535-9cb733da40a4.png">

**Comment by benscott** [comment]
Possibly due to change to EOL service, mentioned in #5674.

**Comment by PaulKiddle** [comment]
Presumably resolved by #5822
