### ISSUE TITLE
Reenable GBIF integration

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5694]
Currently GBIF integration module is disabled, so no datasets are being published to GBIF. Need to renable the module.

**Comment by benscott** [comment]
Following on from #56 , stop scratchpads from spamming useless data sets, test with the gbif testing api (api.gbif-uat.org), then contact GBIF (Marie Grosjean <mgrosjean@gbif.org>, helpdesk <helpdesk@gbif.org>) to get our production api access restored

**Comment by benscott** [comment]
Contacted GBIF for reactivation of our API access.

**Comment by PaulKiddle** [comment]
@benscott This is completely working again now?

**Comment by jrdh** [comment]
Going to assume this is working now given @benscott signaled that it was done.
