### ISSUE TITLE
File upload data/time on BioAcoustica resetting

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5700]
All reset at 3am every day to the current time

**Comment by benscott** [comment]
The date/time reset happens on every cron run, and is being caused by the wildsound module:

`  // Correct filesizes (these are sometimes not written).
   $fids = db_query('SELECT fid FROM {file_managed}')->fetchCol();
   foreach (file_load_multiple($fids) as $file) {
    file_save($file);
   }`

One for @edwbaker - and maybe a good time to split the bio.acousti.ca-only modules into their own repo?

**Comment by edwbaker** [comment]
Intriguing it only happened when it moved to the new server - was cron not
run at all for a year? This code can be deleted now we can upload larger
files.
