### ISSUE TITLE
Page CSS not loading

### ISSUE THREAD

**Issue by marcogaiani** [NaturalHistoryMuseum/scratchpads2#5703]
CSS for several of my Scratchpads are not loading properly. Gives me the following error:

net::ERR_ABORTED 429 (Too Many Requests)

Pages are:
http://triatominae.miza-ucv.org.ve/
http://neotropicalcicadellidae.myspecies.info/
http://tipos.miza-ucv.org.ve/
http://lepidoptera.miza-ucv.org.ve/
http://cerambycidae.miza-ucv.org.ve/

Strangely http://odonata.miza-ucv.org.ve/ works fine.

Any ideas?

Marco Gaiani

<img width="1270" alt="screen shot 2018-12-03 at 5 04 44 pm" src="https://user-images.githubusercontent.com/45576960/49404489-96263a00-f71d-11e8-90f5-ed260685702e.png">

**Comment by NeonPaul** [comment]
Hi Marco, do you know if you've disabled the referrer header in your browser?

We send the 429 response if there are too many requests without that header under the assumption these are bots, but perhaps this policy needs to be revisited if it's causing problems.

**Comment by benscott** [comment]
Hi Marco, I have enabled CSS & JS aggregation on your sites which should fix this problem.  How are they looking for you now?

**Comment by marcogaiani** [comment]
Hi NeonPaul and benscott,
NeonPaul the referrer header has not been disabled.

benscott now the sites are working normally, Thank you.
