### ISSUE TITLE
Species Page Blank

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5704]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

This species page is blank white. I've tried deleting the species and adding it again, but the same thing. 

http://icgf.myspecies.info/ειδη-species/aquila-chrysaetos

**Comment by NeonPaul** [comment]
I think this could be related to #5688

**Comment by benscott** [comment]
This species page is now working correctly.  

The page is currently redirecting to its parent term, which will need to be removed before the page can be viewed.
