### ISSUE TITLE
Greek Letter M

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5705]
...and this is a very old problem.

The Greek letter m (μΜ) doesn't show up in titles. 
![ms](https://user-images.githubusercontent.com/44700406/49435574-99720200-f7bf-11e8-88e6-e61830bec675.jpg)

Also it puts tones on the capital letter of the subtitles, which it shouldn't...

**Comment by NeonPaul** [comment]
Thanks for raising this, Anna. Can you provide links to pages that show these problems so we can investigate further?

**Comment by annanc14** [comment]
There are many pages, unfortunately, too many to send all the links. It's every page that has a greek μ in the title. Here are some examples:
http://icgf.myspecies.info/nontaxonomy/term/269
http://icgf.myspecies.info/nontaxonomy/term/272
http://icgf.myspecies.info/nontaxonomy/term/273
http://icgf.myspecies.info/nontaxonomy/term/278
http://icgf.myspecies.info/nontaxonomy/term/345

**Comment by NeonPaul** [comment]
Thanks. Looks like the character is missing from the font ([Fontin Sans](https://www.exljbris.com/fontinsans.html)) - hopefully we can just update the font version.

You also mention the tones on capital letters - does that mean diacritics/accents on the letters, or something else?

**Comment by annanc14** [comment]
Thank you very much.

Yes, when Greek is written in all capitals, there should be no accents at all.

**Comment by jrdh** [comment]
Hi @annanc14, I've just resolved the other part of this issue regarding the capital letters and the accents that shouldn't be there. Please see https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5714 for more details!
