### ISSUE TITLE
Access to one page changed

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5709]
- Added by [Gontran Sonet](http://jemu.myspecies.info/user/2)
- Scratchpad: [Joint Experimental Molecular Unit (JEMU)](http://jemu.myspecies.info)

### Description:

Dear Scratchpad team,
Recently, visitors of the website who did not log in cannot see the following page anymore:http://jemu.myspecies.info/jemupublications.
This page is an adaptation of the default view of the biblio but I do not find how I can check the publishing options. I do not find this view in the list of views available in the Structure of the website. Could you fix this or help me to fix it?
Thank you very much!

**Comment by benscott** [comment]
It seems there are two pages for the view "jemuprojectpublications", with different filters. 

http://jemu.myspecies.info/jemupublications1#overlay=admin/structure/views/view/jemuprojectpublications/edit/

So a different view is included in the menu depending on if you are logged in or not (URLs: http://jemu.myspecies.info/jemupublications1 and http://jemu.myspecies.info/jemupublications).  

If an anonymous user visits the page http://jemu.myspecies.info/jemupublications1 they can see all the biblio records. So could you delete or edit one of the page views, and ensure the filters are correct for users to view the content?
