### ISSUE TITLE
Correctly transform Greek to all-caps

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#5714]
In Greek grammar, all-caps text should not have accents.

The solution is to apply the `lang="el"` attribute to the page content.
Do we track what language a site/page uses? If not there is probably a module for this.

See https://stackoverflow.com/questions/28783259/how-do-i-make-text-transformuppercase-work-properly-with-greek

See https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5705#issuecomment-444435020

**Comment by jrdh** [comment]
By enabling the `locale` modules you can set a default language which will then alter the `lang` attribute in the `html` tag. I've added Greek to the icfg site and set it as the default so this is now fixed. The language configuration is here: http://icgf.myspecies.info/#overlay=admin/config/regional/language and here an example page showing the fix: http://icgf.myspecies.info/nontaxonomy/term/269.
