### ISSUE TITLE
Error import WoRMS

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5719]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

Not possible to import from WoRMS. It displays the error message:

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Internal Server Error
ResponseText:

**Comment by PaulKiddle** [comment]
Thanks for raising this, we'll investigate further to see if we can find the problem
