### ISSUE TITLE
Can't attach file to biblio node

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5723]
Node: http://bio.acousti.ca/content/analysis-and-visualisation-very-long-duration-acoustic-recordings-natural-environment
File: http://bio.acousti.ca/sites/default/files/Yvonne_Phillips_Thesis.pdf

**Comment by edwbaker** [comment]
Also this one:

Node: http://bio.acousti.ca/content/smart-sampling-environmental-audio-recordings-biodiversity-monitoring
File: 
http://bio.acousti.ca/sites/default/files/Philip_Eichinski_Thesis.pdf

**Comment by edwbaker** [comment]
http://bio.acousti.ca/content/acoustic-classification-australian-frogs-ecosystem-surveys
http://bio.acousti.ca/sites/default/files/Jie_Xie_Thesis.pdf

**Comment by edwbaker** [comment]
http://bio.acousti.ca/content/acoustic-monitoring-wildlife-inaccessible-areas-and-automatic-detection-bird-songs
http://bio.acousti.ca/sites/default/files/Acoustic%20monitoring%20of%20wildlife%20in%20inaccessible%20areas%20and%20automat.pdf

**Comment by edwbaker** [comment]
http://bio.acousti.ca/content/iot-platform-soundscape-monitoring-colombia
http://bio.acousti.ca/sites/default/files/IoT_platform_soundscape.pdf

**Comment by edwbaker** [comment]
http://bio.acousti.ca/content/listening-whales-tying-acoustics-ecology
http://bio.acousti.ca/sites/default/files/Burnham_Rianna_PhD_2018.pdf

**Comment by edwbaker** [comment]
http://bio.acousti.ca/content/coral-reef-soundscapes-use-passive-acoustic-monitoring-long-term-ecological-survey
http://bio.acousti.ca/sites/default/files/McWilliam%20J%202018.pdf

**Comment by edwbaker** [comment]
http://bio.acousti.ca/content/influence-bat-predation-calling-behavior-neotropical-forest-katydids-insecta-orthoptera
http://bio.acousti.ca/sites/default/files/influenceofbatpr00belw.pdf#overlay-context=content/influence-bat-predation-calling-behavior-neotropical-forest-katydids-insecta-orthoptera

**Comment by edwbaker** [comment]
This is still happening on:
http://bio.acousti.ca/content/divergent-selection-and-reproductive-isolation-empirical-study-reed-buntings
fid=34987

**Comment by alycejenni** [comment]
Still the same fix (increasing `max_input_vars`); the env var just wasn't available in bioacoustica.
