### ISSUE TITLE
Strip html tags when italics not used

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5724]
Currently, HTML tags are shown in the page title (used in browser tabs) where they are not rendered. These should be removed.

They also occur unrendered in the view used for the 'Reference' field in biological taxonomy terms.

**Comment by jrdh** [comment]
Hi @edwbaker, I've resolved the first part of this in https://github.com/NaturalHistoryMuseum/scratchpads2/pull/5734 but no entirely sure what you mean by the second part. Can you give more details/an example?

**Comment by edwbaker** [comment]
As an example: 

http://bio.acousti.ca/#overlay=admin/structure/taxonomy/orthoptera - search for Horatosphaga raggei

![image 18-12-2018 at 18 43](https://user-images.githubusercontent.com/929684/50175526-ed6b0380-02f4-11e9-9b94-635c43668bd8.jpg)
