### ISSUE TITLE
Theme Settings

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5729]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

Can anyone tell me how I access the Theme Settings? 

There are no Theme options at all when I click on Appearance on the Admin Panel. 
 
There is a link for them on the Status Report page, but it says "Access Denied" when I click on it. 

Thank you.....

**Comment by PaulKiddle** [comment]
Hi Anna, we've disabled the theme settings for Scratchpads as a lot of the Scratchpad functionality is dependent on the default Scratchpads theme.

Was there any particular setting you wanted to change?

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

I was trying to fix the problem with the Greek Mμ. #5705. 
I thought if I could change the title font to something other than Fontin Sans......

**Comment by annanc14** [comment]
Okay, great. Thanks very much....
