### ISSUE TITLE
Editing Terms

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5730]
For the last 3 days, I've been getting this Error message when trying to edit the information on Term pages....
![untitled](https://user-images.githubusercontent.com/44700406/49989734-e4400680-ff83-11e8-9129-c3c9f362d4a8.jpg)

**Comment by PaulKiddle** [comment]
Thanks for raising this. We've been having issues with high traffic for the past week so it could be related to that. I'll investigate a little more.

Aside from that, obviously this is not a helpful error so that's something we should look at changing.

**Comment by jrdh** [comment]
Just an extra bit of info: the message and functionality are all provided by core Drupal, there is however at least one extension that could provide us with a way to override the default error message functionality: https://www.drupal.org/project/ajax_error_behavior. It's worth considering adding this or a similar extension as an improvement in the future.

**Comment by annanc14** [comment]
Thanks. It seems to be working again today....
