### ISSUE TITLE
Tab Order on Species Pages

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5731]
Does anybody know how to put the Description tab first in the row of tabs on the species pages?

I would like the Descriptions to be the first pages seen when a species is clicked on.

At the moment the Overview tab opens first and it has hardly any info on it. 

Is it possible to delete the Overview tab, or decrease its weight so it is put in another position?

Thank you.....

**Comment by PaulKiddle** [comment]
I'm afraid this isn't possible at the moment, but I think it's something that would be nice for the future

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Okay thanks anyway......

In that case, would it be possible to put the info from the Species Descriptions on the Overview tab? 
I tried adding all that content to the Summary block today using the Edit View option but it didn't show up for some reason.  I was probably doing something wrong though.... Are there any instructions for doing that?

Thank you.....

**Comment by PaulKiddle** [comment]
I think the closest solution is for you to create a taxon description for each species, which will then show in the overview tab.

**Comment by benscott** [comment]
In the next release species tabs are now sortable, with the top most tab the default.
