### ISSUE TITLE
Backup of Scratchpad

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5739]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

The Backup function does not seem to be working on the Wallace Memorial Fund website..

**Comment by jrdh** [comment]
Thanks for reporting this, I'm looking into it now.

**Comment by benscott** [comment]
Hi George,  Apologies if you tried again to request a download, the previous fix wasn't working but is now & the backups on your site are available for download.
