### ISSUE TITLE
Sitemap not visible

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5741]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

I generated a Sitemap for my Scratchpad http://wallacefund.info but when I go to http://wallacefund.info/sitemap it says Access Denied! Why?

**Comment by jrdh** [comment]
Dupe of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5742
