### ISSUE TITLE
Scratchpads incredibly slow

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5743]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

Why are the Scratchpad so incredibly slow considering they are on a new super duper server? They are frustrating to use and it isn't very professional!

**Comment by jrdh** [comment]
Hi George, we're looking into the performance issues right now and I'll update this issue once I have more information. Apologies for the inconvenience.

**Comment by jrdh** [comment]
We believe we have now got to the bottom of the performance problems though we will confirm this tomorrow after more testing to be sure. Apologies for the inconvenience and thank you for your patience.

**Comment by benscott** [comment]
Performance issues are now fixed.
