### ISSUE TITLE
Add a biological classification: Error

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5744]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

According to the video "Add a biological classification: Import your own classification". once a classification has been successfully created, closing the editor results in a new page containing the classification.
Not so. I do not get a page (everything works fine in the Taxonomy editor btw)
Is there another way of putting that classification on a page?

**Comment by jrdh** [comment]
Hi Darwyn, thanks for reporting this. I've resolved the problem by clearing the caches (http://micropezids.myspecies.info/#overlay=admin/config/development/clearcache). Although I can't update the video I can update the wiki with information about this step.
