### ISSUE TITLE
Long URLs cause display to extend beyond viewport

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5746]
e.g.: http://bio.acousti.ca/content/bird-vocalizations-seven-different-types-great-tit-parus-major-vocalizations

<img width="1301" alt="screenshot 2019-01-02 at 23 35 35" src="https://user-images.githubusercontent.com/929684/50617869-3e7b1a00-0ee7-11e9-8831-f996d51875ea.png">

**Comment by PaulKiddle** [comment]
We can probably just add the `word-break: break-all;` css rule here

**Comment by benscott** [comment]
Already fixed in #5765.
