### ISSUE TITLE
Confusing breadcrumbs on search results page

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5749]
e.g. Site is listed twice with differnet link locations

<img width="556" alt="screenshot 2019-01-03 at 14 07 32" src="https://user-images.githubusercontent.com/929684/50641856-39f34780-0f61-11e9-9589-240341764ae8.png">

**Comment by jrdh** [comment]
Fixed in https://github.com/NaturalHistoryMuseum/scratchpads2/commit/566f49429f21ea1e49fc2097203cbd15bbfe7caf
