### ISSUE TITLE
Mendeley BibTex export

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5751]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

Elsevier's Mendeley is a popular free citation manager. It has a simple method of exporting to BibTex format required by Scratchpads.
How come it adds double curly brackets to the Title of each paper? Does anyone have a solution that doesn't involve Find&Replace via a text editor?

**Comment by edwbaker** [comment]
These issues are well known and old. There's some code here that fixes them: https://github.com/adamjgnoel/mendeleyBibFix

**Comment by edwbaker** [comment]
Some further things to be aware of in this blog post: https://ramblingacademic.com/2016/06/19/fixing-bibtex-files-mendeley/

**Comment by scratchpads** [comment]
Comment by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)

Thanks Ed

**Comment by jrdh** [comment]
Thanks @edwbaker
