### ISSUE TITLE
I cannot edit existing pages!

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5752]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

When I try to do so the box which should display the existing text is blank!

**Comment by jrdh** [comment]
Hi George, I expect this is due to the ongoing performance issues, I'll check once those problems are resolved.

**Comment by jrdh** [comment]
Is this still an issue now that the sites are working better?

**Comment by benscott** [comment]
Tested and page editing is functional again - closing this issue as it was most likely caused by the performance issue, but reopen if it's still a problem.
