### ISSUE TITLE
Edit image grid refresh issues

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5755]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

Edit a field within the Edit image grid (Content - Image - Grid) and the item being edited disappears.
The contents of the grid changes in other ways too, some items appear as duplicates.
The items that have disappeared are gone long enough for bulk updates (e.g. Licence changes) to omit them.

**Comment by jrdh** [comment]
Hi Darwyn,

I just had a quick look at this and couldn't replicate the behaviour you've described. I'm wondering if the odd behaviour was a side effect of the server issues we've been experiencing that are now resolved. Could you check again and see if you can still recreate the problems and if so reply? Many thanks.
