### ISSUE TITLE
.tiff allowed in image upload but not .tif

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5757]
Probably should allow both

**Comment by jrdh** [comment]
Will be closed when released.

**Comment by edwbaker** [comment]
It might also be worth adding (some of) wav, mp3, ogg, flac. These are used by BioAcoustica and I currently add them manually. I should add them to the wildsound module, but some (e.g. the compressed formats) might be more generally useful?

**Comment by jrdh** [comment]
Sounds reasonable though I agree just adding mp3 and ogg to the main list makes sense. @benscott / @vsmithuk thoughts?

**Comment by jrdh** [comment]
Opened a new issue for the additional work so that this bug can be closed, see: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5959
