### ISSUE TITLE
Performance issues again

### ISSUE THREAD

**Issue by Paul-Cannon** [NaturalHistoryMuseum/scratchpads2#5759]
I'm sorry to pester when you are probably well aware of the issue, but my site (http://fungi.myspecies.info) is still running very slowly indeed - it's been almost unusable since Christmas. There has been some improvement recently, but intermittently - the site works fine for a minute or two but then slows right down again. Are you still working on the problem, and do you have any thoughts on when it might be finally resolved?

All good wishes
Paul

**Comment by jrdh** [comment]
Hi @Paul-Cannon. We completed fixing the issues as far as we were aware yesterday so it's interesting that you're still experiencing performance problems. Are there any particular parts of the site that you're navigating or actions that you're taking that are particularly slow?

**Comment by Paul-Cannon** [comment]
Thank you for the quick response. The issue happens mostly transitioning from the home page to the content tab, and then adding content (especially images) and editing the metadata is very slow. Everything works fine and then almost stops... The site has a rather complex main taxonomy, and that is very slow to load sometimes as well.

**Comment by jrdh** [comment]
I've tried the pages you stated over the past day and most of the time they have loaded normally but yes, every so often they are very slow. For example, I tried the homepage -> content page route this morning and the first 3 times it was very slow but on the 4th attempt it was fast. I'll take a look and see if there's anything we can do.

**Comment by benscott** [comment]
I have made a few more changes to the servers which should have fixed this issue - could you take another look please and see if that's fixed it for you.

**Comment by benscott** [comment]
Hi @Paul-Cannon - Our apologies, the last release broke a few things, but these are all now fixed and the sites should be working properly again.
