### ISSUE TITLE
Large uploads fail on Bioacoustica

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5763]
Large file uploads are regularly failing, these were working fine before Christmas. Any ideas?

**Comment by jrdh** [comment]
Once the AJAX bug fix has been released to Bioacoustica we can check to see if the problem is still present.

**Comment by edwbaker** [comment]
This is still happening frequently:

An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /file/ajax/field_recording/und/0/form-HnIzbOFSHBQJtDasUC6TnxbjK7C5wRDvKe1Sdf_aEeI
StatusText: n/a
ResponseText: 
Technical difficulties
Site is experiencing technical difficulties.  Please try again later.

ReadyState: ,

**Comment by edwbaker** [comment]
I have checked that the other AJAX issues are fixed, which they are. This seems to be a new bug.

**Comment by benscott** [comment]
This is possibly related to the server issues we were having - I've tried uploading images (jpg & tif, 100MB+) to your site and staging without error.  Was it a particular image / file size that was failing?

**Comment by edwbaker** [comment]
Yes - seems to be OK now.

Thanks!

On 18 Feb 2019, at 16:16, Ben Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


This is possibly related to the server issues we were having - I've tried uploading images (jpg & tif, 100MB+) to your site and staging without error. Was it a particular image / file size that was failing?
