### ISSUE TITLE
site came back online

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5768]
- Added by [Mark Pajak](http://bns.myspecies.info/user/2)
- Scratchpad: [Bristol Naturalists' Society](http://bns.myspecies.info)

### Description:

I need to delete this site but not sure how. it was in maintanance mode but soemhow it came back online

**Comment by benscott** [comment]
Sorry about that - the site came back online erroneously in our recent server migration.  I have now disabled the site - just to confirm: you'd like the site completely deleted and all content removed?  Once deleted the site data will not be recoverable.

**Comment by PaulKiddle** [comment]
Deleted the site
