### ISSUE TITLE
Greek Letters Again

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5769]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

The issue with the Greek M has been fixed, thank you very much.

But now there seems to be a problem with Δ and Π. They have been replaced by triangle symbols.

http://icgf.myspecies.info/nontaxonomy/term/524

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Actually it's the small case π, not Π

**Comment by PaulKiddle** [comment]
Looks like we might have to combine the new font and the old font for a short-term fix..

We can try using the `unicode-range` css property:
https://css-tricks.com/almanac/properties/u/unicode-range/
Use the old font and just pick the μ from the new one.

**Comment by jrdh** [comment]
We've had to roll back the original change we made to resolve the issues with μ as the updated font had more missing characters as you reported in this issue. We're going to look at switching to a new font for scratchpads which supports all the characters we need to support so for the moment http://icgf.myspecies.info is back on the old font with the missing μ. Sorry about this Anna.

**Comment by scratchpads** [comment]
Comment by [](http://icgf.myspecies.info/user/0)

Thank you for your help anyway. I'll wait and see what happens....
