### ISSUE TITLE
Thumbnails should not cut off important parts of the image

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5775]
- Added by [Charles Perez](http://coleopteraofgibraltar.myspecies.info/user/2)
- Scratchpad: [Coleoptera of Gibraltar ](http://coleopteraofgibraltar.myspecies.info)

### Description:

Images uploaded have the top and bottom of image cut off.  have used same image on another ScratchPad Flora of Gibraltar and comes out perfectly.  have used flora image on Coleoptera site and it cuts off the top and bottom; so this new scratchPad version is not uploading and resizing photos properly

**Comment by PaulKiddle** [comment]
Hi Charles, thanks for this - can you upload an example image and post a link to it?

**Comment by PaulKiddle** [comment]
The thumbnails are cropped into 4:3 landscape rectangles, which cuts off the top and bottom in this case, however if you click on them you'll see the full image.

**Comment by CPerez132** [comment]
Hi Paul,

 

So you say that there is no possibility of inputting a 4:3 photo, as it would cut off top and bottom.  I know that when you click on image it displays ok, but it should also appear properly on the home and species pages too, as well as the media page.

 

Well as an example I have loaded the same photo on the Flora of Gibraltar website and it displays normally.  4:3 photos on this site display properly.

 

See http://floraofgibraltar.myspecies.info/joint-pines/anthaxia-scutellaris-gen%C3%A9-1839

 

There must be something wrong surely, with the new ScratchPad version.

 

Appreciate if you could please look at this.

 

Kind regards,

 

Charlie

 

 

Charles Perez

Technical Officer

Gibraltar Botanic Gardens

 

cperez@gibraltargardens.gi

 

Tel:  54021473

Gardens Logo small

**Comment by alycejenni** [comment]
This appears to be fixed, closing
