### ISSUE TITLE
Issue with rendering taxonomic names with quotes

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5778]
Mecopoda "S" : http://bio.acousti.ca/classification/mecopoda-s

http://bio.acousti.ca/content/synchronous-alternating-and-phase-locked-stridulation-tropical-katydid is tagged with this term but the name is not rendered on the node

**Comment by edwbaker** [comment]
This seems to also include items with subgenera, e.g.: http://bio.acousti.ca/content/bryodemella-tuberculata-tuberculata-published-recording-germany-upper-bavaria-near-bad-tölz

**Comment by PaulKiddle** [comment]
Name should show in `Taxonomic name` field at the bottom of the page

**Comment by alycejenni** [comment]
Unable to recreate - may be something specific to bioacoustica

**Comment by edwbaker** [comment]
I had a very quick look at this, it seems to render on recording nodes, but not biblio nodes, even though they both use the 'Formatted taxon name' formatter.

**Comment by edwbaker** [comment]
Ignore that, it's more complex. There is nothing in the wildsound or wavesurfer modules on GitHub that would modify this. Does the code on the BioAcoustica server match this repo? I can't log in to check at the moment.

**Comment by alycejenni** [comment]
I've finally tracked this down - it's nothing to do with the quotes. The language for the term and the node do not match: the language for the `Mecopoda "S"` term is set to `und` (i.e. undefined), and the page language is set to `en` so it's trying to display the English translation for the term (which does not exist).
Another example (without the quotes):
http://bio.acousti.ca/content/global-cicada-sound-collection-i-recordings-south-africa-and-malawi-b-w-price-m-h-villet-and

There are ~250 other pages with this issue on bioacoustica.
