### ISSUE TITLE
"Notice: Trying to get property of non-object in _block_render_blocks() (line 911 of /var/aegir/platforms/scratchpads-2.9.4/modules/block/block.module)"???

### ISSUE THREAD

**Issue by Morjens123** [NaturalHistoryMuseum/scratchpads2#5780]
Our myspecies website http://pistiaistyoryhma.myspecies.info/  is accessible but gives numerous error messages like the following:
 "Notice: Trying to get property of non-object in _block_render_blocks() (line 911 of /var/aegir/platforms/scratchpads-2.9.4/modules/block/block.module)." 

What could be the cause of this "little" problem

**Comment by benscott** [comment]
This is now fixed - apologies for the bug.
