### ISSUE TITLE
The Specimen list is not visible under the Specimen tab

### ISSUE THREAD

**Issue by poospiza** [NaturalHistoryMuseum/scratchpads2#5781]
Hello,
The Specimen list is not visible under the Specimen tab. It was displayed correctly earlier in january. See attached screengrab of error messages. The rest of the site seems to be working ok including list display of specimens under a taxon page.
![specimens](https://user-images.githubusercontent.com/46485179/51670911-05a30200-1fc8-11e9-85e2-91a851c06191.jpeg)
Thanks Nicholas Williams
Site: http://ethoikos.myspecies.info/

**Comment by PaulKiddle** [comment]
Some technical info: Chasing one of these errors down, the file properties appear to get lost in the `advanced_render` function in `sites/all/modules/contrib/views/handlers/views_handler_field.inc` - they are passed in to the function nested in a big object, but don't get passed into the call to `render_item` on line 1085

**Comment by poospiza** [comment]
Hi Paul,
The Specimen list is visible today. Filtering and linking seems to be working as expected. Yesterday it wasn't working. Thanks!

**Comment by PaulKiddle** [comment]
Wonderful
