### ISSUE TITLE
Error with DOI import

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5783]
DOI 10.16373/j.cnki.ahr.180025 resolves using the crossref resolver, however on Scratchpads the import gives this unhelpful error.

![screenshot 2019-01-24 at 12 18 25](https://user-images.githubusercontent.com/929684/51677638-2cfecc80-1fd2-11e9-974f-a9ec263fca67.png)

**Comment by edwbaker** [comment]
@edwbaker You didn't enter this manually after raising the bug - in case you forget.

**Comment by jrdh** [comment]
The reason this is failing is because the response from crossref is unresolved:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<crossref_result xmlns="http://www.crossref.org/qrschema/3.0" version="3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.crossref.org/qrschema/3.0 http://www.crossref.org/schemas/crossref_query_output3.0.xsd">
  <query_result>
    <head>
      <doi_batch_id>none</doi_batch_id>
    </head>
    <body>
      <query status="unresolved" fl_count="0">
        <doi>10.16373/j.cnki.ahr.180025</doi>
      </query>
    </body>
  </query_result>
</crossref_result>
```

Not sure why that would happen given that the DOI itself resolves fine when you follow it. Even going through their main search page gives no results: https://search.crossref.org/?q=10.16373%2Fj.cnki.ahr.180025

**Comment by jrdh** [comment]
And the reason we show a pretty useless error is because we're just showing what crossref are returning to us, which is also a useless error, see [here](https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/sites/all/modules/contrib/biblio/modules/crossref/biblio.crossref.client.php#L78).
