### ISSUE TITLE
Additional link on Structure page

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5784]
"Automatic label" has just appeared - no icon, and was not there previously.

![screenshot 2019-01-24 at 13 36 35](https://user-images.githubusercontent.com/929684/51681628-21fd6980-1fdd-11e9-861e-7684050ad04a.png)

**Comment by alycejenni** [comment]
@PaulKiddle is this not an intentional consequence of commit cf2a6b3?
