### ISSUE TITLE
Where is my Scratchpad?

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#5785]
All I see is date and time when I go to what should be my Scratchpad address at http://poissongabon.info.  Please fix or advise.

**Comment by PaulKiddle** [comment]
Hello, apologies for the problem. The site is still available but it looks like the domain name `poissongabon.info` is pointing to the wrong IP address - do you know who owns and/or controls the domain name?

**Comment by jpsullivan65** [comment]
I own the domain, but I didn't change anything with regard to where it's pointing. It just stopped working about a year ago.  To what address should it point?

**Comment by benscott** [comment]
Looking at the DNS records, it doesn't seem to be forwarding to the Scratchpad server - could you try adding an ANAME record to 157.140.2.32.

**Comment by PaulKiddle** [comment]
There should be an option to add an `A` record on GoDaddy, you should use that and point it to `157.140.2.32`.

The reason that 157.140.2.32 only shows the date is that all of the scratchpads are hosted on this server, and without a domain name it's impossible to tell which site to serve. This is why the right DNS configuration is important. Currently the IP address your domain is pointing to seems to be some kind of third-party proxy service, which Scratchpads is not designed to deal with.

**Comment by jpsullivan65** [comment]
Thanks, Paul.  Looks like I have it sorted now.   ~ John
