### ISSUE TITLE
Page editing error

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5790]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

I am getting the error message:
The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved.
How do I fix this (there are no other users)

**Comment by benscott** [comment]
Is this happening on a particular page - or all pages?  And does it occur every time you save?

**Comment by scratchpads** [comment]
Comment by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)

All pages except for the Home page I think. Just tried it on another page and that won't edit either.

**Comment by benscott** [comment]
I just tried editing both a page and taxon description and both update without errors for me.  

What browser are you using?  And can you describe what you were editing - was there a particular field you were changing?

**Comment by benscott** [comment]
Thanks for the info - I can now recreate the bug and will update as soon as I have a fix.

**Comment by benscott** [comment]
This is now fixed & editing should be working properly again.

**Comment by scratchpads** [comment]
Comment by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)

Thanks Ben
