### ISSUE TITLE
Interactive Table in Page content type

### ISSUE THREAD

**Issue by Quote2106** [NaturalHistoryMuseum/scratchpads2#5791]
Hello,
I was wondering if it would be possible to make tables included in the Body of a content type Page more interactive.
I would for example like to filter search or custom sort on column headers. (http://bopco.myspecies.info/content/overview-processed-requests)
Would this be possible in future versions of scratchpad or is there an alternative content type to choose (e.g. the Biblio tables have a similar buildup)?

All the best,
Kenny

**Comment by benscott** [comment]
I'm afraid it's not possible with a table embedded within a page.  

It is possible to do this within a Scratchpad, but the content would need to be restructured:

1) Create new content type (http://bopco.myspecies.info/content/overview-processed-requests#overlay=admin/structure/types) for each processed request, with the fields: Policy Concern, Taxon, Organisation and Outcome.

2) Create a new item of content for every row in the table.

3) Create a table view of the new content items - http://bopco.myspecies.info/content/overview-processed-requests#overlay=admin/structure/views. You can customise table headers to be sortable.

**Comment by Quote2106** [comment]
Hello Ben,

I followed your steps, but some things remain unclear.

Would I have to add the top row (with titles to sort on) as a content type too? Or are these later defined as titles for the table view?

In building the table view I cannot find how to select content types (each processed request) to include?
Is it via the menu as seen in a below picture?

![display](https://user-images.githubusercontent.com/47144980/51919248-5610ca00-23e3-11e9-9078-2ab0fdda5ed7.PNG)

**Comment by benscott** [comment]
You only need to create one new content type - and then create new instances of that content for each row.  So not a content type per row.

For example - I have created a new content type called "Processed request", with two fields "Policy concern" and "Taxon". (Do replace this content type with your own / add the other two fields as you prefer)

You would then create new items of content at: http://bopco.myspecies.info/tableview2#overlay=node/add/processed-request, filling in the "Policy concern" and "Taxon" fields, corresponding to each row in your existing table.

In your view, you would then select "Processed request" as the content type filter - as you have now for "tabletest-toprow"
