### ISSUE TITLE
Phthiraptera - Weird comments

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5793]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

For some data records created in 2017 there were weird unpublished comments. e.g. of one:
Title of the data record - Insectes Ectoparasites (Mallophages, Anoploures, Siphonaptères) by Seguy, E.
URL: http://phthiraptera.info/node/94276

**Comment by benscott** [comment]
I have deleted the spam comments and the new Spamicide modules #5687 should help prevent so many coming through.
