### ISSUE TITLE
I cannot edit existing pages!

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5799]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

I am still unable to edit the existing content on my site. When I click the Edit tab, the Body text box is blank...

**Comment by benscott** [comment]
Hi George, Sorry for the delay fixing this bug - took a while to track down the bug, but editing should all be working properly now.
