### ISSUE TITLE
Character handling in Literature

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5803]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

There's a fault in the way that foreign characters are handled in Literature.
Koçak, Ahmet Ömer finishes up as Koçak, AÖmer 
it omits a space after shortening the Turkish professor's first forename then adds all of his second name, though the details are correct in the edit field.

**Comment by benscott** [comment]
Updated biblio to use CiteProc author style - https://github.com/NaturalHistoryMuseum/scratchpads2/commit/841203bbb9c79ca5f5378a25cb7680b205e4bdfb.
