### ISSUE TITLE
Images not embedding on pages

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5804]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

The Add Media function on the Page Edit hangs and does not add the image. The last stage before hanging is a window showing the image and a non-functional button titled SubmitCancel. Nothing happens after this and no functioning button can be located, even after a 30 mins wait.

**Comment by benscott** [comment]
This is now working - tested with an example page and image, but let us know if the problem reoccurs.
