### ISSUE TITLE
Phthiraptera - Phthirapterists Tab

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5810]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi

The Phthirapterists tab is still not working. If one click onto it , a blank page with the message Forbidden - you don't have permission to access/ phthirapterists on this sever. Apache Server at Phthiraptera.info Port 80. Also another weird tab has appeared - PHTHIRAPTERISTSSS. Also this does the same as above - blank page with Forbidden message.  Thanks

**Comment by benscott** [comment]
Sorry Sam - that was the test page I created to try and track down what was going wrong. It's all fixed now.
