### ISSUE TITLE
Public list of all scratchpads

### ISSUE THREAD

**Issue by klausriede** [NaturalHistoryMuseum/scratchpads2#5814]

**Comment by klausriede** [comment]
sorry for a stupid outsider question: I vaguely remember a website with thumbnails for many scratchpads, probably maintained by the Vibrant project (does it still exist?). I cannot find it anymore, in any case I think such a list or entry point is useful! Greetings Klaus Riede

**Comment by poospiza** [comment]
It used to be here: http://scratchpads.eu/explore/sites-list

**Comment by klausriede** [comment]
...but evidently it is not there anymore...only a few left?

**Comment by benscott** [comment]
Sorry, that's a part of the old system we haven't got onto fixing yet.  It'll be something we get working soon, but at the moment we're still focused on the backlog of bugs and getting the sites running smoothly again.  

We actually have over 1000 Scratchpads now - was there something you particularly wanted to find out?

**Comment by benscott** [comment]
There is also this list of all Scratchpads - http://stats.scratchpads.eu. It's unstyled but up-to-date. (Thumbnails aren't functional yet unfortunately).
