### ISSUE TITLE
Images not dispalying

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5819]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

I have no images at all

**Comment by PaulKiddle** [comment]
Hi Darwyn, apologies for this - this was due to a minor Scratchpads update. Your images have been restored now.
