### ISSUE TITLE
The images on the front page are gone

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5820]
- Added by [N. M. Williams](http://ethoikos.myspecies.info/user/2)
- Scratchpad: [Ethoikos Biodiversity Database](http://ethoikos.myspecies.info)

### Description:

The top right section of the front page is empty. Usually one large image and four thumbnails are shown
Nicholas

**Comment by PaulKiddle** [comment]
Apologies for this problem. I have restored the images.
