### ISSUE TITLE
Images on home page - a thumbnail problem

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5821]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

The thumbnail images on the Home pages of various sites are not displaying properly. They have shrunk.

**Comment by benscott** [comment]
@PaulKiddle - is this a result of #5819/#5820 or a separate bug?

**Comment by PaulKiddle** [comment]
This is a consequence of updating the slideshows module, new css rules restricting the thumbnails. I'll add something to scratchpads_front to override them.

**Comment by benscott** [comment]
Thanks @PaulKiddle

**Comment by scratchpads** [comment]
Comment by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)

It's the same on all the species pages
