### ISSUE TITLE
Back Up

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5824]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

How do we get a back up?

I've tried requesting a back up many times, but it never shows up on the back up page.

Thanks.....

**Comment by benscott** [comment]
We have had this issue before #5739, which seems to have been fixed for some sites. I will investigate why it's not working on yours.

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Thanks........There's an awful lot of pdf files on our site. It might be that it takes too long to make the back up, because the site is so large.

**Comment by benscott** [comment]
I don't think it's that unfortunately - the backups aren't downloadable on the Wallace site either.  

@jrdh - did your release in #5739 fix the backups?  Any idea what's up with this?

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Looks like its working again..... thanks

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Anyway it lists the old back ups now. They aren't actually there when I click on them, but I've requested a new one, and I'll wait and see if I can download that......

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

No, when I click on the latest backup, well, all the backups, it says, "page not found".

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

If the backup won't work, would it be possible to arrange for you to send us copies on a disk sometimes? We'd pay something for it of course. Thanks......

**Comment by benscott** [comment]
Sorry, this wasn't working before but it is fixed now & your backups can be downloaded through the interface.
