### ISSUE TITLE
How to assign own domain name to an existing site.myspecies.info?

### ISSUE THREAD

**Issue by s-bolshakov** [NaturalHistoryMuseum/scratchpads2#5827]
I would like to transfer an existing site from subdomain.myspecies.info to my own domain name.
In the settings of the domain zone, I assigned my domain to A-record with the address 157.140.2.32.
![image](https://user-images.githubusercontent.com/36799292/52711309-8db27100-2fa2-11e9-93c3-19f3ffafb2a5.png)
This was clearly insufficient, since the message "Not Found. The requested URL / was not found on this server." was now displayed at this address.
What else should I do for my purpose?

**Comment by benscott** [comment]
Adding an ANAME should be sufficient - what subdomain are you doing this for?
