### ISSUE TITLE
Author names in Literature

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5831]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

Doesn't handle
Horace St John Kelly Donisthorpe
correctly
Correct display is H.St.J.K. Donisthorpe
if you just use his initials it displays as
H Donisthorpe St.J.K
listed under "H", not "D"
My usage works correctly in Mendeley.

**Comment by benscott** [comment]
See also #5803

**Comment by benscott** [comment]
This will be fixed by #5803
