### ISSUE TITLE
Can't upload Images 2

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5833]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

This is the error message I get "An AJAX HTTP error occurred. HTTP Result Code: 503 Debugging information follows...<<TRIMMED>>

**Comment by benscott** [comment]
How large is the file?
