### ISSUE TITLE
Status report tells me to run a script

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5836]
- Added by [N. M. Williams](http://ethoikos.myspecies.info/user/2)
- Scratchpad: [Ethoikos Biodiversity Database](http://ethoikos.myspecies.info)

### Description:

Hi,
The status report for our Scratchpads urges me to run a database update script. I have attached a screenshot. Thought I would run it by you first. Should I execute the script? 
Thanks Nicholas

**Comment by poospiza** [comment]
![status report](https://user-images.githubusercontent.com/46485179/53008600-0fd6e580-343a-11e9-8c8d-d847a1779535.jpeg)

**Comment by benscott** [comment]
Apologies, that was a hangover from the previous release and should have been run automatically. It's now been run.

**Comment by poospiza** [comment]
Great, thanks!
