### ISSUE TITLE
Efficiently deleting bogus comments?

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5840]
- Added by [lukas.scharer](http://macrostomorpha.info/user/2)
- Scratchpad: [Macrostomorpha](http://macrostomorpha.info)

### Description:

I have over 6000 unapproved bogus comments on my site (probably created by bots), and it seems I can only delete them in batches of 50 given the current interface.Is there a mere efficient way?
I am aware that there may be a few bona fide comments among them, but I am willing to lose those.
Cheers, Lukas

**Comment by benscott** [comment]
I'm afraid there's not at the moment - I've just had the same issue with another site.  I have created an issue #5841 for us to build this functionality. In the meantime, I can delete the comments directly within the database if you'd like?

**Comment by scratchpads** [comment]
Comment by [lukas.scharer](http://macrostomorpha.info/user/2)

Thanks for looking into this. Yes, I would be grateful if you could delete all the unpublished comments. I doubt there are any useful ones. Thanks! Lukas

**Comment by benscott** [comment]
Sure thing - all done.
