### ISSUE TITLE
Phthiraptera - Access Denied

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5843]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

This is a recent phenomenon - Users of the Lice Scratchpad, unless they are login, will not be given access to the data records - Message came up as ACCESS DENIED.- You are not authorized to access this page. If the user knows the title and using the search engine and enter the title the datarecord does appear but if click onto it, the Acess Denied will appear. Even if the user were to enter the URLs of the data record, same thing happen.

**Comment by benscott** [comment]
This is now fixed: biblio settings was restricting access to the author of the biblio entry only.

**Comment by therobyouknow** [comment]
released 2.10.1 to https://phthiraptera.myspecies.info/ which should fix this, please advise.
