### ISSUE TITLE
Literature link to authors broken again

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5844]
[Phthiraptera](http://phthiraptera.info)

- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

all newly created data record no longer linked with the authors and cannot be found via search engine. i.e. in CONFIGURATION -BIBLIO-Setting, the no. of data records is noted to be changed but when click into it - the publication is not listed. Same as if search via LITERATURE (Tag) search engine  or any other search engine, the newly created data record is missing. Unless one knows the URLs or unless the author is listed under PHTHIRAPTERISTS then the publication is listed

**Comment by benscott** [comment]
The publications page comes from the SOLR index, and it takes a few minutes for a new record to be indexed and be displayed on the page. The count of data records is retrieved from the database and reflects the change immediately - hence the discrepancy. 

You can speed up the process of getting a new record into the search index by going to http://phthiraptera.info/admin/config/search/apachesolr and selecting "Index Queued Content (50)" button.
