### ISSUE TITLE
synonyms?

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5848]
- Added by [Peter Hovenkamp](http://diplazium.myspecies.info/user/2)
- Scratchpad: [Diplazium in Malesia](http://diplazium.myspecies.info)

### Description:

Is it possible to have all synonyms listed on the taxonomy page for a name - i.e., all names that have that name as "associated accepted name"?

**Comment by Chrisis21** [comment]
Indeed that would be useful. And also, it would be nice to show on a synonyms page a link with the valid name of that species...

**Comment by PeterHovenkamp** [comment]
There is a way to approach this. I have configured a view that lists names and accepted names, filtered by a user-selected Associated accepted name. See: http://diplazium.myspecies.info/synonym-selection#overlay=admin/structure/views/view/synonym_selection/edit/page%3Fdestination%3Dsynonym-selection.

There is one problem: if the selected name has a homonym (occurs with literally the same combination of unit name 1 and 2 in two nodes), the selection is empty.

**Comment by benscott** [comment]
Yes, it's possible to create a synonym block to display on the taxon pages - you can see an example here: http://solanaceaesource.org/solanaceae/solanum-amblophyllum.

If you'd like me to create a similar view for your Scrarchpad let me know.
