### ISSUE TITLE
Map data lost on failed form validation

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5852]
If you've added shapes to a map and the form submission fails validation, all the map data disappears.

**Comment by PaulKiddle** [comment]
Fixed by f6282bc5651cc94c6d29eabb61d7e611b141897a

**Comment by PaulKiddle** [comment]
Not fixed - reverted and created new branch/PR

**Comment by PaulKiddle** [comment]
Finally fixed 😌
