### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5856]
- Added by [brechtverstraete](http://taxonomytraining.eu/user/1219)
- Scratchpad: [Taxonomy Training](http://taxonomytraining.eu)

### Description:

I'm unable to upload any files, no image, no video, no audio. The "media browser" opens but only shows a blank pop-up. I tried different browsers but no change. It worked before. Anyone ideas?

**Comment by benscott** [comment]
Sorry about that - this is now fixed.
