### ISSUE TITLE
Unable to create content (from a custom content type)

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5857]
- Added by [L Livermore](http://ihs.myspecies.info/user/2)
- Scratchpad: [The International Heteropterists' Society](http://ihs.myspecies.info)

### Description:

I have an announcement content type (very simple custom content) and I am unable to save new content. When I click save it appears to reload the content creation overlay but without saving any data.

**Comment by benscott** [comment]
This is now fixed.
