### ISSUE TITLE
Literature link to authors when name changed

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5859]
[Phthiraptera](http://phthiraptera.info)

- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Authors Volko & Zarubina
Originally for these two author there were two variations of their name input. As it is only one data record, instead of merging I have edited the names for this data record URL( http://phthiraptera.info/content/myopus-schisticolor-lill-rodentia-myao-chan-ridge-and-its-parasites) to the options that were commonly used. For Volko it was Volko V.J. (3253) which is wron to VOLKO V.I. (1859) AND FOR ZARUBINA it was from Zarubina V (3254) to Zarubina V.N. (1753).  However after doing that Scratchpad does not seem to link this data record back to these two authors

**Comment by scratchpads** [comment]
Comment by [Yokb](http://phthiraptera.info/user/29)

Hi I have checked the authors mentioned and it seems to have resolved itself. Both Volko & Zarubina now have the correct no. of data record in their LITERATURE listing

From Sam 5/3/2019

**Comment by benscott** [comment]
Fixed by #6031 - all author merge/link updates will be updated in SOLR index.
