### ISSUE TITLE
Update status Broken link between LITERATURE and Authors

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5860]
[Phthiraptera](http://phthiraptera.info)

- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

This was reported on 21-2-2019 as an issue. However, I have noticed that it seems that there is a time delay say one or two days before the newly uploaded data record is link to the authorships. Hence I have to keep a note everytime I uploaded a new datarecord to make sure they are linked

**Comment by scratchpads** [comment]
Comment by [Yokb](http://phthiraptera.info/user/29)

Last update the link of data record to authors in their LITERATURE Listing - time delay was a day but it seemed to be getting longer. Data records that were uploaded yesterday have still not been linked to the authors. Example of authors are Stepanova O.N. (ID 9656) should have 4 data record as in CONFIGURATION-BIBLIO SETTING and not 3 in LITERATURE LISTING. Others are Campos-Munoz (10083), Fueyo-Casado, A. (10084), Carranza-Romero, C. (10085), Gonzalez-Guerra, E. (10086), López-Bran, E. (10087). I will be continuously creating more data records and will continue to keep a record of them and monitor them.

**Comment by benscott** [comment]
Duplicate - see #5844
