### ISSUE TITLE
Node importer shows odd behavior

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5861]
- Added by [lukas.scharer](http://macrostomorpha.info/user/2)
- Scratchpad: [Macrostomorpha](http://macrostomorpha.info)

### Description:

When I export the specimens on my site for offline editing there is some odd formatting that emerges in the resulting Excel sheet, with the "Title" column having spurious spaces between the "Institution code" and the "Collection code". It seems that earlier records do not have that, and there the "Institution code is followed by a "pipe" character. 
Generally, I would be grateful for some feedback on whether you recommend using the node importer to update entries, or whether editing things online is safer.
Cheers, Lukas

**Comment by jrdh** [comment]
Hi Lukas,
I've removed the additional spaces and the pipes as well so your exports should be clean now. Not sure why they got in there in the first place, but they were in the field values themselves so perhaps there were some issues with the import system previously which had caused problems and then left your data in a bad state. Regardless, the problems are gone now.
In terms of using the importer or editing them online, the importer is stable and should produce the results you expect but I'd only recommend using it for bulk updates/additions. We are currently working through the backlog of reported issues that had built up on Scratchpads so as we release fixes in the coming weeks the stability of the import process and the overall sites should increase.
