### ISSUE TITLE
Database update script does not run

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5862]
- Added by [lukas.scharer](http://macrostomorpha.info/user/2)
- Scratchpad: [Macrostomorpha](http://macrostomorpha.info)

### Description:

Under "Configuration" I get the message "One or more problems were detected with your Drupal installation. Check the status report for more information", but when I try to "run the database update script immediately" I get a "Page not found" error. Any ideas?
Cheers, Lukas

**Comment by PaulKiddle** [comment]
Hi Lukas, these updates are meant to be run by the Scratchpads team. We are currently updating all sites so this message will be resolved in the next few days.

**Comment by scratchpads** [comment]
Comment by [lukas.scharer](http://macrostomorpha.info/user/2)

Thanks!
