### ISSUE TITLE
Can't Edit Terms

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5878]
We are having this problem again. Can't save terms. Thanks....
![untitled](https://user-images.githubusercontent.com/44700406/54030415-30ca6500-41b4-11e9-9d90-a8835d56b7b2.png)

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

It's working ok today, thanks.....
