### ISSUE TITLE
Taxonomic data access denied 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5883]
- Added by [Monica Pramatarova](http://psylloidea-bg.myspecies.info/user/2)
- Scratchpad: [Psylloidea of Bulgaria](http://psylloidea-bg.myspecies.info)

### Description:

Hello,
I have a problem with seeing or editing the terms and following information of taxonomic data on my homepage. Despite that I am administrator of http://psylloidea-bg.myspecies.info/psylloidea/ my access is denied.

**Comment by jrdh** [comment]
Hi, sorry for the delay in getting this resolved, I have now however fixed the issue.

For future maintainers, it was the same problem as https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5935.
