### ISSUE TITLE
Sticky at top of lists not working

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5884]
- Added by [username](http://training-ury-01.myspecies.info/user/2)
- Scratchpad: [Scratchpad training site](http://training-ury-01.myspecies.info)

### Description:

If I change stickiness for new content types, it won't add them to the top if lists.

**Comment by alycejenni** [comment]
This is an additional sort criteria that you can enable/disable yourself - it's not enabled by default.
Enable it by editing the view and adding `Content: Sticky (desc)` as the first sort criteria, e.g.:
![image](https://user-images.githubusercontent.com/23579762/72251858-5acf8d80-35f6-11ea-94c6-b3071481baf4.png)
