### ISSUE TITLE
map expansion

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5891]
- Added by [Laboratorio de Botánica](http://parquefagro.myspecies.info/user/2)
- Scratchpad: [Parque Fagro](http://parquefagro.myspecies.info)

### Description:

If it is possible to see the map the nearest to the marked points when you open it.

**Comment by PaulKiddle** [comment]
The maps already centre on points that have been added, but perhaps the default zoom level could be increased - it was changed to fix issue #5635 but maybe I set it too low.

**Comment by PaulKiddle** [comment]
I've added a [little more information](https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Adjust-Maps-Settings) in the wiki.
