### ISSUE TITLE
Rearranging blocks

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5892]
- Added by [Ary Mailhos](http://coreopsideaeuy.myspecies.info/user/2)
- Scratchpad: [Coreopsideae en Uruguay](http://coreopsideaeuy.myspecies.info)

### Description:

Issue trying to rearrange a block on a taxon overview page using the context tool so that it is below the nomenclature and media blocks.

**Comment by alycejenni** [comment]
Hi,
Would you be able to provide some more information about the issue? e.g. did you see an error message?

**Comment by alycejenni** [comment]
Got more info from @benscott.

Add a new block to the `species_overview` page using the Context Layouts module:
![list of pages](https://user-images.githubusercontent.com/23579762/54540609-308a5080-4990-11e9-8f23-fa8e8037e689.png)
![editing the page](https://user-images.githubusercontent.com/23579762/54540640-413ac680-4990-11e9-97aa-6ac80eb2681e.png)

On saving, the blocks do not layout correctly - the new block overlaps the existing blocks:
![overlapping blocks](https://user-images.githubusercontent.com/23579762/54540762-76dfaf80-4990-11e9-8192-39056aa74658.png)

The new block does not have the `grid` classes needed to make it layout correctly.
