### ISSUE TITLE
delete account

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5894]
- Added by [umagali](http://cephbase.eol.org/user/45992)
- Scratchpad: [CephBase](http://cephbase.eol.org)

### Description:

i cant receive an email to delete my account. Please fix asap

**Comment by alycejenni** [comment]
Hi,
Are you trying to delete the 'umagali' user account? Do you get any errors when trying to delete it, or are you just not receiving the email?

**Comment by alycejenni** [comment]
nearly a month without a response; closing
