### ISSUE TITLE
Contact us link on top right

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5902]
- Added by [brechtverstraete](http://taxonomytraining.eu/user/1219)
- Scratchpad: [Taxonomy Training](http://taxonomytraining.eu)

### Description:

Someone tried to contact our page by sending a message by clicking on the "contact us" link on the top right of the page. However, they were unable to send the message. How can this be fixed?

We get this error:

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /antibot
StatusText: OK
ResponseText: 
Submission failed | Taxonomy Training
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-2428547-2', 'auto');
ga('send', 'pageview');
Skip to main content
You must have Javascript enabled to use this form.
Username *
Password *
Log in using OpenID 
What is OpenID?
Remember me 
Create new accountRequest new password
feed me 
To prevent automated spam submissions leave this field empty.
Log in using OpenIDCancel OpenID login    
Log in  
Contact usReport abuse
Taxonomy Training
Search form
Search 
All 
Taxonomy 
Main menuHomeAboutCoursesCourse providersThird-party coursesNewsletter    
You are hereHome » Submission failed
Submission failed        
You have reached this page because you submitted a form that required Javascript to be enabled on your browser. This protection is in place to attempt to prevent automated submissions made on forms. Please return to the page that you came from and enable Javascript on your browser before attempting to submit the form again.
Click here to go back
Home
About
Courses
Course providers
Third-party courses
Newsletter
Scratchpads Policies
Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution CC BY Licence.    
Scratchpads developed and conceived by (alphabetical):
Ed Baker,
Katherine Bouton
Alice Heaton
Dimitris Koureas,
Laurence Livermore,
Dave Roberts,
Simon Rycroft,
Ben Scott, 
Vince Smith

**Comment by alycejenni** [comment]
Hello,
Could you please check that this person has JavaScript enabled on their browser?
This page may help:
https://www.enable-javascript.com

**Comment by scratchpads** [comment]
Comment by [brechtverstraete](http://taxonomytraining.eu/user/1219)

I've tested it myself, my javascript is enabled but it still gives the same error.

**Comment by alycejenni** [comment]
You're right, this is actually a bug - we'll look into it.
