### ISSUE TITLE
AlkCarb - Missing map data

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#5904]
No map data is rendering for Emma Humphreys-Williams when she loads her scratchpad's maps. The map itself works but no data points (see screenshot).

<img width="320" alt="Screenshot 2019-03-28 at 09 34 10" src="https://user-images.githubusercontent.com/1755184/55170804-16f6bf00-516f-11e9-84f2-41bc17a6b8a1.png">

http://alkcarb.myspecies.info/map

This works fine in my browser (FF on Ubuntu) - could be a problem with Safari on Mac? - find a machine to check on

**Comment by benscott** [comment]
Yep, looks like a browser thing: not working on Safari/Mac for me, but does in FF & Chrome. I'll take a look.
