### ISSUE TITLE
exporting

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5908]
- Added by [Darren Davidson](http://treeplantae.myspecies.info/user/2)
- Scratchpad: [Local Tree Plant Database](http://treeplantae.myspecies.info)

### Description:

cannot export data

**Comment by alycejenni** [comment]
Hi Darren,
Would you be able to give us some more information about the problem you're having?
1. What data are you trying to export?
2. What happens when you try to export it (i.e. do you get an error message)?
