### ISSUE TITLE
Taxon map broken

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5912]
- Added by [Ulf Jondelius](http://acoela.myspecies.info/en/user/3)
- Scratchpad: [The Stylet - ](http://acoela.myspecies.info)

### Description:

Since the upgrade the mapping of specimens is broken on my scratchpad acoela.myspecies.info. The specimen markers, the "dots" show up on the map now (they didn't immediately after the upgrade), but all the links to specimen data are gone. There was a link to Species name, specimen identifier, photos etc for each specimen that could be displayed by clicking on the marker. Now all that functionality is gone and that map is not that useful anymore..

**Comment by poospiza** [comment]
I just noticed the same bug on our site and found this open issue. However I observe a slightly different behaviour; the speech bubble with specimen metadata do appear when there is just one specimen recorded at the locality. If there are more than one specimen recorded at a locality it does not appear. The specimen records used to appear as a set of tabbed, numbered speech bubbles. This is an example of the current behaviour: http://ethoikos.myspecies.info/taxonomy/term/9265/maps   The westernmost locality has only one specimen. 
![Untitled](https://user-images.githubusercontent.com/46485179/60890930-9ca10500-a25c-11e9-8f70-71a84d594ebb.jpeg)

**Comment by PaulKiddle** [comment]
Hi Ulf and @poospiza, you should find this working better now. Where there are multiple specimens at the same location you will have multiple tabs in the bubble.

**Comment by poospiza** [comment]
Yes it looks fine on my site. Thank you.
