### ISSUE TITLE
Phthiraptera - Literature Page - Publication year nos.

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5915]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi

As I upload the more papers, the number of publication of that year should I presumed changed. However, it has remain the same since the Literature/author link has broken. So may be everything in that page of the website is affected.

Thanks

**Comment by benscott** [comment]
Error on search indexing.

**Comment by benscott** [comment]
Caused by the same error as #5918 - indexing is working correctly again.
