### ISSUE TITLE
Thumbnail images incorrectly scaled

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5916]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

On the taxon page the thumbnail images are still scaled incorrectly in the Media section. This was fixed for the Home page but still persists here.

**Comment by jrdh** [comment]
This was fixed in https://github.com/NaturalHistoryMuseum/scratchpads2/pull/5873
