### ISSUE TITLE
First time login - access denied

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5917]
Access denied when using the first time login link

**Comment by PaulKiddle** [comment]
We had this problem before, I fixed it in https://github.com/NaturalHistoryMuseum/hosting_scratchpads/commit/c9bed5619d4d54578b2e96c63f41b0ecc7475187 - could be something else unrelated though

**Comment by benscott** [comment]
Thanks @PaulKiddle, I'll look there first.

**Comment by benscott** [comment]
System time was out of sync, so timestamp check was failing if clicked soon after creation. Synced system clock to fix.
