### ISSUE TITLE
Phthiraptera - Literature Page - Major problem discovered

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5918]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

If one goes to LITERATURE, all the numbers in the caterogies e.g. Taxonomic Name, Author, Publication Year, Publication Type, Journal, Filter by Contributor remains the same even though new papers have been uploaded to it or I have made changes to exiting article. Although in the search box for each of these categories, if we type the key word and it appears as a choice, but if we pressed enter to select this, No LiTERATURE CONTENT HAS BEEN ADDED TO THIS SITE. 

Also using the general search engine on the top right hand corner of the website, the newly uploaded paper cannot be found, irrespective of whether I checked ALL, TAXONOMY or LITERATURE or BIBLIOGRAPHY.  The only way I can find that paper if one of the author is listed in the PHTHIRAPTERISTS or I know the URL.

**Comment by benscott** [comment]
Hi Sam - there as a literature item with an odd title blocking the search index from running.  I've fixed it and the search is now running properly again.

**Comment by scratchpads** [comment]
Comment by [Yokb](http://phthiraptera.info/user/29)

Hi Ben

Threes cheers to you everything in Literature site and the general search engine is back to normal. Numbers are increasing and new papers are linked to authors now.
 Thanks

**Comment by benscott** [comment]
Great - thanks for checking & glad it's all working again!
