### ISSUE TITLE
Backup Still Not Working

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5920]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

This is still a problem.

I requested a backup yesterday:

icgf.myspecies.info-20190502.233839.tar.gz

But when I click on the link it says "Not Found"

I'd really like to be able to get a backup. Is there any way to fix this? 

Thanks....

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Still the same.....

This message 

Not Found

The requested URL /icgf.myspecies.info-20190502.233839.tar.gz was not found on this server.

Apache Server at backup.scratchpads.eu Port 80

Would there be any other way to get hold of a backup? Would you be able to send me a copy somehow?

**Comment by benscott** [comment]
This bug is now fixed and you can download the backups through your SP.
