### ISSUE TITLE
Phthiraptera - Selection function malfunction

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5923]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi,
For the last two days, I have come across a problem when I type something in and select a choice, something strange happen. In the first case - during the process of editing or creating a new data record, after in the TAXANOMIC NAME entry, when after I type a name and a selection came up and I clicked onto it, I noticed that all information I have entered in the PUBLICATION section disappeared and only the year of the datarecord remained. Even after I have saved the datarecord and re-edit, same thing happends if I carried out the same process of selection in any part of the datarecord e.g. authors name etc. To prevent this from happening I just don't use the selction function. In case two - In the LICE site/webpage/tag - During editing, if I use the selection function, instead of allowing me to continue, a page with the title - CHOOSE type to create and add - appears and I don't know what to do even if I click the cancel button - nothing happens. The only way to get out of this is to use the top left '<' go back button until I come back to the start again. The only where to avoid this is again not to use the selection fuction.

**Comment by benscott** [comment]
Sorry about that - this is now fixed.
