### ISSUE TITLE
Diplazium in Malesia - Selection malfunction

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5924]
- Added by [Peter Hovenkamp](http://diplazium.myspecies.info/user/2)
- Scratchpad: [Diplazium in Malesia](http://diplazium.myspecies.info)

### Description:

A problem similar to the one described for Phthiraptera.
If I try to select a term in the field "associated accepted name" (a term reference field using the autocomplete widget) I am transferred to an empty item of a bibliographic item. 
Did not happen last time I tried (a few weeks ago).

**Comment by benscott** [comment]
Sorry about that - this is now fixed.
