### ISSUE TITLE
Liturature menu

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5928]
- Added by [Ralph Harbach](http://mosquito-taxonomic-inventory.info/user/2)
- Scratchpad: [Mosquito Taxonomic Inventory](http://mosquito-taxonomic-inventory.info)

### Description:

There is no list of references under the Literature menu of the Mosquito Taxonomic Inventory (http://mosquito-taxonomic-inventory.info/biblio)

**Comment by benscott** [comment]
Sorry about that, this should be working properly again.
