### ISSUE TITLE
PHTHIRAPTERA -Indexing in LITERATURE page is broken again

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5930]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Authors new datarecord are not link to their literature listing like before and in fact the whole LITERATURE page indexing is not working again. Sorry don't know why and I have not enter any title with strange character either, Happened today and yesterday was fine

**Comment by benscott** [comment]
Fixed by #6031
