### ISSUE TITLE
Content lost in several pages

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5931]
- Added by [edchacon](http://floracostaricensis.myspecies.info/user/2)
- Scratchpad: [Flora de Costa Rica](http://floracostaricensis.myspecies.info)

### Description:

The content of several pages was deleted or disappeared. 
For example, I had content in this page and now  I can not see it.

http://floracostaricensis.myspecies.info/node/492#overlay-context=node/492

**Comment by jrdh** [comment]
Hi, there seems to be content on the page you've linked - has the issue been resolved since you reported it or have you recreated the page?
