### ISSUE TITLE
The page body lost

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5932]
- Added by [edchacon](http://floracostaricensis.myspecies.info/user/2)
- Scratchpad: [Flora de Costa Rica](http://floracostaricensis.myspecies.info)

### Description:

The body section for most of the pages was lost and only taxonomic names remains in the page.

**Comment by jrdh** [comment]
Hi, can you provide more information about which area/page of your site you are seeing this issue please?
