### ISSUE TITLE
Autofill not working in Biblio 

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#5933]
Trying to use autofill for taxa in the taxonomic name box in Biblio

We get this message:

![error](https://user-images.githubusercontent.com/44700406/58087604-86b28480-7bc9-11e9-9dff-7eac65953b1b.jpg)

**Comment by jrdh** [comment]
Apologies, thought I'd already flagged this up, but this is a dupe of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5939
