### ISSUE TITLE
Unable to import taxonomy checklist

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#5937]
Email from Barry Warrington ( http://agromyzidae.myspecies.info/ )

> Hello,
>  
> I have created my taxonomy database following the format in the provided
> training files but I am unable to import it. The error message states
> 'Term name missing' and I am unable to ascertain why this is.
>  
> Please could you advise on what I could do to correct this?

Attached is the spreadsheet he was trying to upload: [Agromyzidae checklist Scratchpad template.zip](https://github.com/NaturalHistoryMuseum/scratchpads2/files/3213139/Agromyzidae.checklist.Scratchpad.template.zip)

**Comment by benscott** [comment]
I have sent back an updated spreadsheet which fixes this.
