### ISSUE TITLE
Removing tabs from taxon description

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5947]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Hi,

Is it possible to remove the 'Specimens' tab on the species description page?

Thanks.

**Comment by jrdh** [comment]
Hi Barry,
Thanks for getting in touch. Currently there is no way to hide certain tabs, however, I've added this functionality [here](https://github.com/NaturalHistoryMuseum/scratchpads2/pull/5950). When we release the next version of the scratchpads platform (will be in 2-3 weeks) you'll be able to toggle the default tabs that are shown under the settings for the taxonomy the description is displayed under - including the `Specimens` tab.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

That’s great, many thanks.
