### ISSUE TITLE
EOL images irrelevant

### ISSUE THREAD

**Issue by Chrisis21** [NaturalHistoryMuseum/scratchpads2#5948]
[Taxonomy/media page](http://antsme.myspecies.info/taxonomy/term/10/media)

Apparently the images from EOL are irrelevant to the taxon... e.g. _Cataglyphis nodus_ (ant)
![image](https://user-images.githubusercontent.com/41307327/59427408-9ea5ae80-8deb-11e9-8f0d-134e39c00704.png)
or _Tetraponera ambigua_
![image](https://user-images.githubusercontent.com/41307327/59427454-bd0baa00-8deb-11e9-8abe-b071578d26c8.png)
Also not fully loading...

**Comment by jrdh** [comment]
Thanks @Chrisis21, looking into this now.

**Comment by benscott** [comment]
Hi Christos,

The EOL image display is working correctly again, but I'm afraid it will display inaccurate images unless your classification is restructured a little. Scratchpads are designed to use binomials, but on your scratchpad the genus is not included in the species name.

Take, for example, Camponotus acvapimensis. http://antsme.myspecies.info/taxonomy/term/244

Normally, this would be structured on a Scratchpad as:

**Unit name 1:** Camponotus
**Unit name 2:** acvapimensis

On your Scratchpad the data is:
**Unit name 1:** acvapimensis

It's not a big problem, but does mean the EOL lookup isn't always accurate as it's searching for only part of the species name.  The easiest fix would be to reimport your taxonomy, including both the unit 1 & unit 2 parts of the species binomial (we can help structure the data, if it would help).
