### ISSUE TITLE
Number of Documents

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5951]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

Does anybody know how I can find the total number of pdfs uploaded to my site?

Thanks

**Comment by jrdh** [comment]
Hi Anna, I don't think there's a way of getting this number through the site, however from a quick look in the database I can tell you there are 1550 pdfs that have been uploaded.
