### ISSUE TITLE
BioAcoustica - emails not sending

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5953]
Emails are not being sent, e.g. when new user signs up. 

![grafik](https://user-images.githubusercontent.com/929684/59923028-40e81680-942a-11e9-84b2-dd36358e1c1f.png)

**Comment by jrdh** [comment]
Hey @edwbaker, any idea when this started happening?

**Comment by edwbaker** [comment]
Afraid not, I mentioned it to @benscott on Slack on 23rd May though.

**Comment by jrdh** [comment]
@benscott did you find anything or did you not get a chance to look into it?

**Comment by benscott** [comment]
This was fixed - but I have since updated the containers which might have introduced the prob again. I'll take a look now.

**Comment by jrdh** [comment]
Ok thanks, were the changes you made tracked under an issue or pr?

**Comment by PaulKiddle** [comment]
@benscott What's the status of this?

**Comment by benscott** [comment]
Working again
