### ISSUE TITLE
map with region

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5954]
- Added by [yves BRAET](http://doryctinaekey.myspecies.info/user/2)
- Scratchpad: [Key to the genera of Doryctinae of the world](http://doryctinaekey.myspecies.info)

### Description:

Dear,
In my website (http://doryctinaekey.myspecies.info/), only for new taxa I add, I can't select a region/subregion/country on the map. The use of polygon is ok. I have use it as surrogate the country selection for the Cerritulus genus.
Please could you check and repare that?
Thank you for your help

**Comment by jrdh** [comment]
Hi Yves, I checked this out yesterday and it did seem a bit inconsistent however it seems to be working fine today. Given that it seems to have stabilised, I'd be interested to know if you are you still having issues?

**Comment by ybraet** [comment]
Hi Jrdh,
It is still not working on my side. Look at the Cerritulus genus. On the map (edit taxon) I have removed the polygon that I had draw previously to surrogate the French Guiana area. I have tried to select the French Guiana area (which is the area of distribution of this taxa) but nothing happen even after 10 minutes... 
So on my side this doesn't work. 
Please could you check?
Thank you for your help.

PS: I have not received any alert about your answer to my topic. Sorry for the delay of mine

**Comment by ybraet** [comment]
Dear Jrdh, PaulKiddle,

My issue is the same than the issue #5991 

Please could you do the same to allow me to use region in my map displayed in taxon description? This was possible several months ago.

Thank you for your help
Yves

**Comment by PaulKiddle** [comment]
The problem was specifically for the French Guiana region. This has been fixed in the code.
