### ISSUE TITLE
Add video

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5956]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Is it possible to embed a video on a page so it is viewable ‘full screen’ within the page?

Thanks.

**Comment by jrdh** [comment]
Hi Barry, thanks for getting in touch. Just so I can make sure I answer your question correctly, are you asking about embedding a video uploaded to the scratchpad or a linked video from say, youtube?

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Either really. I would like to have a video playable on a page which is shown as a screen within the page, not as a link or thumbnail.

Thanks.

**Comment by jrdh** [comment]
I've done some digging and you should be able to embed youtube videos directly by editing the html of the page's body using the plain text editor (click `Switch to plain text editor` under the body editor). For example:

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/kmmhOlhdxaA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

Just use the width and height attributes to alter the size on the page.

The filtered HTML text format that is used by default allows `iframe` tags, hence why this works. That's the easiest way to do it and should give you all the flexibility you need.
