### ISSUE TITLE
Cannot attach images to taxonomy

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5962]
If you add an image field to a vocabulary, when you try editing a term and uploading an image file, there's an AJAx error:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/81690/60663420-113c0400-9e57-11e9-8d5a-ad5e6e427b49.png">

<img width="855" alt="image" src="https://user-images.githubusercontent.com/81690/60663436-1e58f300-9e57-11e9-9285-41475d010f7d.png">

**Comment by PaulKiddle** [comment]
I can't reproduce this, which site is it on?

**Comment by benscott** [comment]
This bug is a problem on all content types using the media multiselect widget - see #6034
