### ISSUE TITLE
Duplicate terms - autocomplete term widget (tagging)

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5963]
When adding a taxonomy field as a tagging widget, terms are duplicated:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/81690/60822306-1d003100-a19d-11e9-806b-ba0302bf52e3.png">

**Comment by PaulKiddle** [comment]
Can't reproduce this one either, what site is it on?

**Comment by alycejenni** [comment]
@benscott - any more info?

**Comment by benscott** [comment]
Seen on Alkcarb, and on local. If the tagging widget is now working, it's probably already been fixed.

**Comment by alycejenni** [comment]
Mysteriously fixed :ghost: 
(checked on Alkcarb and local)
