### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by Paul-Cannon** [NaturalHistoryMuseum/scratchpads2#5964]
I've found that when I am logged in and access some of the images on the fungi.myspecies site directly from Google images I'm taken directly to the image edit screen and not to the species page - and I can then apparently edit the page. If I can do this, can others while I'm logged in? One of the affected images has the title "Rufoplaca arenaria 1". Please could you check this out? The search page is here [https://www.google.com/search?q=Caloplaca+arenaria&tbm=isch&source=univ&client=firefox-b-d&sa=X&ved=2ahUKEwj8geeVgajjAhUsQxUIHXJKAdcQsAR6BAgHEAE&biw=1920&bih=966#imgrc=QQ5fFXK593-a3M:](url)
Many thanks
Paul

**Comment by PaulKiddle** [comment]
Hi Paul,
This will only be the case if you're using Google with the same browser that you're logged into your scratchpad with; other users will be sent to the view image page but won't be able to edit it.

**Comment by Paul-Cannon** [comment]
OK, thank you for the reassurance.
Paul

________________________________
