### ISSUE TITLE
Failed migration does not restore site

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5966]
When migrating a site fails, the restore gets stuck.  

This is currently affecting:
aconitum.myspecies.info 
acrocephalus.vaibla.net

See the corresponding restore files in the 2.9.9 platform sites directory.

**Comment by PaulKiddle** [comment]
acrocephalus.vaibla.net seems to be on 2.9.9 and working correctly
aconitum.myspecies.info I have managed to restore

I suspect the failure might have been caused by max_statement_timeout, I've upped the timeout and I will try migration again.
