### ISSUE TITLE
Literature bar too large

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5967]
- Added by [Paul Cannon](http://fungi.myspecies.info/user/2)
- Scratchpad: [Fungi and Lichens of Great Britain and Ireland](http://fungi.myspecies.info)

### Description:

The brown (in my case) bar under the Literature tab on the species pages is sometimes much larger than usual - see e.g. under [Nesolechia oxyspora ](http://fungi.myspecies.info/taxonomy/term/8593/literature)

**Comment by PaulKiddle** [comment]
Seems like there's a block of BHL links (`.block-bhl-default`) underneath the literature section title, stretching it out. Removing the `float:left` might fix it.

**Comment by PaulKiddle** [comment]
Fixed - now able to see BHL list and block headers are normal height
