### ISSUE TITLE
Pictures not showing 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5972]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Sometimes pictures don't show on Biblio pages

http://icgf.myspecies.info/node/1822

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Some pictures are not showing up when you try to choose them from the Library either.

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

I changed the file name and it works again. Maybe it doesn't like Greek letters in file names.

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

I changed the file name and it works again. Maybe it doesn't like Greek letters in file names.

**Comment by PaulKiddle** [comment]
I can reproduce this on the server but not on my local machine, might be an infrastructure issue.
I'll keep digging into it.

**Comment by PaulKiddle** [comment]
@annanc14 I've released a fix for this - can you try uploading a file with a Greek filename to make sure it works?

**Comment by annanc14** [comment]
Yes, that works. Thank you very much!
