### ISSUE TITLE
Viewing full image in media gallery is forbidden

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5975]
- Added by [muscapaul](http://sciaroidea.info/user/42)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

http://sciaroidea.info/taxonomy/term/43378/media
Clicking the image for a full view results in the error Request unsuccessful: Forbidden

**Comment by PaulKiddle** [comment]
The image was set to be accessible to the Undercover Gnats group (http://sciaroidea.info/file/2151/edit):

![private-image](https://user-images.githubusercontent.com/1755184/61627951-e506ec80-ac78-11e9-95e9-36a5a0f19788.jpg)

I've changed it to public for you.
