### ISSUE TITLE
Search temporarily unavailable

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5977]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

When I try to open the Literature Tab, I keep getting this message:

Search is temporarily unavailable. If the problem persists, please contact the site administrator.

http://icgf.myspecies.info/biblio?f%5B0%5D=is_uid%3A36&sort=asc&order=Title

**Comment by PaulKiddle** [comment]
The page seems to be okay now - hopefully just a temporary problem.
