### ISSUE TITLE
Italics in Biblio titles

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5982]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Trying to put italic html tags around species names in biblio titles.

Sometimes I get the error - "Invalid html"

http://icgf.myspecies.info/node/2333#

**Comment by PaulKiddle** [comment]
This should have been fixed in #5872 / #5898
I'll try and have a look what went wrong.
