### ISSUE TITLE
Summary Block

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5983]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Does anyone know how I can put the data I have in the Descriptions Tab into the Summary block on the Overview tab?

Thanks

http://icgf.myspecies.info/ειδη-species/acteoniscus-petrochilosi

**Comment by PaulKiddle** [comment]
Hi @annanc14,

I've written up some instructions on how to do this and added them to the wiki:

[Customize taxon pages](https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Customize-taxon-pages#option-2-context-layout-editor) - Follow option 2, context layout editor.

Let me know if you have any trouble.

**Comment by annanc14** [comment]
Thanks very much!! That was really simple....
Anna
