### ISSUE TITLE
PHTHIRAPTERA - Indexing in LITERATIURE page is broken again

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5984]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi

Today 30-7-2019 I noticed that Scratchpad is not the no. of updating papers uploaded. Is the Index linkage in the LITERATURE page broken again?? e.g. Author Chin Ta-Hsiung (1640) should be 23 data record as shown in CONFIGURATION- BIBLIO-SETTING -AUTHOR but in LITERATURE is only 22.

**Comment by PaulKiddle** [comment]
Seems to be working, index was just a bit slow
