### ISSUE TITLE
Taxonomy tree page not accesible. Part 3

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5989]
- Added by [Marco Gaiani](http://neotropicalcicadellidae.myspecies.info/user/2)
- Scratchpad: [Neotropical Leafhoppers](http://neotropicalcicadellidae.myspecies.info)

### Description:

Sorry guys to bother again with the same issue, but my taxonomy term page displays a:
"Access denied. You are not authorized to access this page."

Help please

**Comment by PaulKiddle** [comment]
I've temporarily fixed this using the solution in https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5935#issuecomment-502637973, but obviously we need to figure out why this is happening for a more long term fix.

**Comment by benscott** [comment]
Hi Marco,

Sorry for the delay in getting this fixed - I've tracked down and fixed the underlying cause of this bug. Your taxonomy is displaying properly again and this issue shouldn't reoccur next time you  reimport the taxonomy. 

Thanks very much,
Ben
