### ISSUE TITLE
Region distribution is not displayes

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5991]
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

http://sciaroidea.info/taxonomy/term/51185/descriptions

Colombia is selected as distribution in Taxon description, but region is not highlighted, only a small dot appears at low scale. Newly created taxon description has the same problem

**Comment by PaulKiddle** [comment]
Hi Vladamir,

The taxon description was using the polygon tool instead of the region tool to select the distribution  area. I've updated it to use the region for you.

![region](https://user-images.githubusercontent.com/1755184/63029282-2cfbe680-bea8-11e9-8791-38b56ae7f000.png)
