### ISSUE TITLE
PDOException on excel import

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5995]
Trying to import occurrence nodes into http://alkcarb.myspecies.info/, throws a PDOException ```Column 'field_location_lat_long_latitude' cannot be null```.  There is data in the location lat/long field.

Rolling site back to 2.9.9 fixes the issue.

![Screenshot 2019-08-14 at 19 35 40](https://user-images.githubusercontent.com/81690/63259740-2342fc00-c277-11e9-9e47-aa1e0169ce02.png)

**Comment by alycejenni** [comment]
Seems to have been broken by something in e7af91a
