### ISSUE TITLE
Slow Site

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5996]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

The site has been really slow yesterday and today. Very slow saving data..... thanks

**Comment by PaulKiddle** [comment]
Hi Anna, should be running faster today.
