### ISSUE TITLE
[bib] tags problem on /glossary

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5997]
http://bio.acousti.ca/glossary - the term for "phonoreception" and others on this page which use the [bib]...[/bib] tags to quote references don't render (or hide) the references.

**Comment by alycejenni** [comment]
I don't have an answer yet, but this is what I've found today:

This seems to work for the first entry on the page, but not for any subsequent entries:
![image](https://user-images.githubusercontent.com/23579762/64881987-0cb07a80-d654-11e9-9c66-130f196d0a16.png)

![image](https://user-images.githubusercontent.com/23579762/64882013-19cd6980-d654-11e9-8f84-83e2e439e002.png)

(all three entries have the same text for the first two lines)
It does not matter if it's the first time that specific reference has been used.
