### ISSUE TITLE
BHL and NCBI blocks in wrong place

### ISSUE THREAD

**Issue by Paul-Cannon** [NaturalHistoryMuseum/scratchpads2#5998]
The BHL block now appears above the biblio references that I've input for the species pages, which mean that the most relevant refs drop off the bottom of the page as it's viewed on the screen. Similarly, the NBCI block now appears above the species description (see for example that for Spathularia flavida). Could these both be put back below the user-contributed content where they were until recently? I tried to do this myself but couldn't work out how...

Much appreciated
Paul

**Comment by benscott** [comment]
Hi Paul, The order of blocks can be adjusted using the context interface - http://fungi.myspecies.info/admin/structure/context. I've rearranged the blocks so the BHL & NBCI blocks are below your content.

**Comment by Paul-Cannon** [comment]
Hi Ben
Thanks for your help. I do not have permissions to access the page you give below - but no need now...

Paul

________________________________
