### ISSUE TITLE
Distribution map not showing data

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6003]
- Added by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)
- Scratchpad: [Lonchaeidae Online](http://lonchaeidae.myspecies.info)

### Description:

It looks like none of the maps on Lonchaeidae online are showing country data

**Comment by PaulKiddle** [comment]
Hi Iain, can you post a link to a specific map that should be showing data?

**Comment by PaulKiddle** [comment]
This should be fixed now
