### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6005]
- Added by [Ralph Harbach](http://mosquito-taxonomic-inventory.info/user/2)
- Scratchpad: [Mosquito Taxonomic Inventory](http://mosquito-taxonomic-inventory.info)

### Description:

Not able to add new pages to the Fossil Culicidae menu. Every time I do to save the new page, it comes up as Invalid HTML. Please let me know that this has been corrected so that I can add new content.

**Comment by alycejenni** [comment]
Hi Ralph,
Is this related to issue #5982 (i.e. is it because you're putting italics in the title)?

**Comment by edwbaker** [comment]
I have just seen Ralph and can confirm this is the italic issue, on two different content types.

**Comment by PaulKiddle** [comment]
I think it's titles with an ampersand in it or other entities that require escaping in xml

**Comment by PaulKiddle** [comment]
Fixed and deployed on Ralph's site
