### ISSUE TITLE
Error message when importing new locations

### ISSUE THREAD

**Issue by poospiza** [NaturalHistoryMuseum/scratchpads2#6006]
Hi,
I get this error message when I run the import of Locations using the Excel template:

Unable to handle the provided embed string or URL.
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_map_latitude' cannot be null

**Comment by scratchpads** [comment]
Comment by [N. M. Williams](http://ethoikos.myspecies.info/user/2)

http://ethoikos.myspecies.info/

**Comment by alycejenni** [comment]
duplicate of #5995
