### ISSUE TITLE
Non-italicized species names

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6007]
- Added by [Ralph Harbach](http://mosquito-taxonomic-inventory.info/user/2)
- Scratchpad: [Mosquito Taxonomic Inventory](http://mosquito-taxonomic-inventory.info)

### Description:

Species listed under genera in the Fossil Culicidae menu are not italicized. They, like the genus names, should be in italics. Please let me know that this has been corrected.

**Comment by alycejenni** [comment]
Hi Ralph,
Your species should be added as the binomial name in order to be italicised, with the genus as `Unit 1` and species as `Unit 2`. e.g.
![image](https://user-images.githubusercontent.com/23579762/64248443-00684700-cf09-11e9-97c9-ca7a020d6447.png)
