### ISSUE TITLE
Cannot link file to biblio node

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6009]
http://bio.acousti.ca/content/bioacoustic-monitoring-new-zealand-avifauna-and-after-aerial-1080-operations

http://bio.acousti.ca/sites/default/files/thesis_access_0.pdf

**Comment by edwbaker** [comment]
In addition: 
http://bio.acousti.ca/content/variability-repertoires-and-singing-behavior-male-and-female-‘i‘iwi-drepanis-coccinea

http://bio.acousti.ca/sites/default/files/Beck_hilo.hawaii_1418O_10174.pdf

No warning or error messages in either case.

**Comment by alycejenni** [comment]
Duplicate of #5994
