### ISSUE TITLE
DOI import issue

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6011]
The DOI 10.26049/VZ69-3-2019-01 resolves via CrossRef but the Scratchpads importer does not work.

**Comment by benscott** [comment]
Manually tested 10.26049/VZ69-3-2019-01 in the CrossRef OpenURL API and it's returning as unresolved. The Scratchpads importer is working correctly and tested with other DOIs - this is CrossRef end.
