### ISSUE TITLE
Cannot import files using URL

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6022]
When importing files using a URL, the file is not completely downloaded to the Scratchpad - just a chunk at the start of the file.

**Comment by jrdh** [comment]
What were you importing @edwbaker? Was it an import to feeds or was it a media file? I tried a media import and it worked fine for me.

**Comment by edwbaker** [comment]
Media files. I can't check if it works at the moment as bioacoustica has been broken since the weekend. Will check once that's fixed.

**Comment by alycejenni** [comment]
@edwbaker can you check if this is still an issue?
