### ISSUE TITLE
Alkarb text encoding

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#6026]
Bracket instead of a plus minus sign (±). 

http://alkcarb.myspecies.info/node/2138
http://alkcarb.myspecies.info/node/2030

**Comment by benscott** [comment]
https://www.drupal.org/project/vbo_search_and_replace

**Comment by alycejenni** [comment]
Importing data incorrectly imported ± symbols as `(`: need to find and replace these on the Alkcarb site.

**Comment by alycejenni** [comment]
As far as I could see this only affected the 'age' field, so I've done this semi-manually, using a lot of update statements, e.g.

```sql
UPDATE alkcarbmyspeci_0.field_data_field_age_info SET field_age_info_value = '[...] 186±6 Ma [...]' WHERE entity_id = 2562;
```

(`[...]` = other string content - no point in pasting it all out here but it was included in the original query).

I've saved a list of the affected nodes and the original values but I'm just attaching a list of the IDs - ask if you need the original values.
[alkcarb_affected_node_ids.txt](https://github.com/NaturalHistoryMuseum/scratchpads2/files/4078073/alkcarb_affected_node_ids.txt)

I'm going to check other fields now. Will close if I don't find anything.

**Comment by alycejenni** [comment]
Found a couple more in the 'narrative' field on nodes 1933 and 2035. Now fixed.
