### ISSUE TITLE
Cannot disable Ecological Interactions in main menu on BioAcoustica

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6040]
The link is also duplicated when the module is enabled.

**Comment by alycejenni** [comment]
I'm unable to recreate the link duplication issue - when did that happen?

**Comment by edwbaker** [comment]
About two months ago. I wonder if it's the menu link is not deleted when the module is disabled? I think I might have enabled and disabled it previously but I can't be sure.

**Comment by alycejenni** [comment]
I can't recreate that so I'm going to manually delete the extra link and hope it's fixed itself - reopen if it happens again!
