### ISSUE TITLE
Missing taxa on ecological interactions page 

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6041]
http://bio.acousti.ca/interactions

Species A should be populated.

**Comment by alycejenni** [comment]
Quick update: I'm completely unable to recreate this, so it may be a bioacoustica-specific issue. I'm still looking into it, but I need to make a local bioacoustica instance on my dev machine and that's proving _unecessarily difficult_.

**Comment by alycejenni** [comment]
It turned out to not be bioacoustica-specific - it was because all the missing terms happened to not have a translation in the 'und' (undefined/generic) language.
It's now fixed (hopefully) but if you want a workaround in the meantime, add a translation for/change the language to 'und'.
