### ISSUE TITLE
only a few photos are show in media gallery

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6049]
- Added by [yves BRAET](http://doryctinaekey.myspecies.info/user/2)
- Scratchpad: [Key to the genera of Doryctinae of the world](http://doryctinaekey.myspecies.info)

### Description:

Dear team,
Another issue I have detected. All the images/photos of my site (http://doryctinaekey.myspecies.info/gallery) have been tagged with taxa, terms, creators, etc
But only the more recent  ones are shown in the media gallery tab.
Under media tab of each taxa there is no problem it seems.
Please could you allow the full display of all photos and to allow their sorting by keywords.
Best regards
Yves

**Comment by PaulKiddle** [comment]
I wonder if this is a Solr indexing issue

**Comment by benscott** [comment]
Rebuilt the image index & the gallery is working correctly.
