### ISSUE TITLE
New password not working. Can only gain access with one-time password.

### ISSUE THREAD

**Issue by gubnet** [NaturalHistoryMuseum/scratchpads2#6051]
- Added by Chris Woolley
- Scratchpad: [Fossil Insects from Cretaceous Deposits of the Orapa Diamond Mine, Botswana](http://orapainsects.myspecies.info/)

Description: New password not working. I can only gain access with the one-time password after requesting a new password.

Hi, I'm not sure but I either forgot or was prompted to change my original password. When I change it using the one time password and save the changes, I cannot gain access to my scratchpad using the new password - I have to go through the 'request new password' routine again which, as stated, allows me access but does not save the changes. Any help appreciated.
Thanks
Chris

**Comment by PaulKiddle** [comment]
Hi Chris,
I've created an account on your site and tested the password reset and it seems to work for me.
Can I just check you're using the right username - `Christopher Woolley`, with a space in?

**Comment by gubnet** [comment]
Thanks Paul - yes sorry, this is my mistake. I wrongly assumed my email address was my username. Thanks for your help. Chris
