### ISSUE TITLE
Distribution map not showing data

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6052]
- Added by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)
- Scratchpad: [Lonchaeidae Online](http://lonchaeidae.myspecies.info)

### Description:

Hi    I reported this as an issue several weeks ago  -  the ability to show distribution is a key part of my site  - can you give me an update on when this is likely to be resolved      thanks  ..........  Iain

**Comment by PaulKiddle** [comment]
Hi Iain, we are currently updating all scratchpads to fix this issue. I've just updated yours, you'll find the distribution maps working again now.

**Comment by scratchpads** [comment]
Comment by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)

Many thanks for this quick response  - that really helps me

best wishes  ............  Iain
