### ISSUE TITLE
taxonomy - can't delete a taxon (AJAX error)

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6053]
- Added by [Dean Hendrickson](http://truchasmexicanas.myspecies.info/user/2)
- Scratchpad: [Truchas Mexicanas](http://truchasmexicanas.myspecies.info)

### Description:

When I try to delete the top line in my taxonomy, the genus Oncorhynchus lacking children, I get the error:

truchasmexicanas.myspecies.info says
An AJAX HTTP error occurred
HTTP Result Code 500
Debugging information follows.
Path: /System/ajax
StatusText: internal Server Error
ResponseText:

I've tried deleting it in the downloaded template as well, but uploading that does nothing

**Comment by PaulKiddle** [comment]
Seems to be specific to this taxon, I tried creating and deleting new terms with no problem.
I've manually deleted it from the database now and moved your site to the latest version, so you shouldn't see this problem again. If you do please raise another issue or reopen this one.
