### ISSUE TITLE
Glossary terms not highlighted

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6056]
Terms from the glossary used to be highlighted in taxon descriptions (e.g. http://bio.acousti.ca/taxonomy/term/222/descriptions) - this is no longer working.

**Comment by therobyouknow** [comment]
I'm guessing you mean, for example, the 'Behaviour' long text field, I've mocked up a highlight here @edwbaker 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1080646/197741219-edd1e378-66f5-44d9-a975-f2002c5900b6.png">

And with the highlight, I would think you would want this to be clickable to take you to the terms page?

This should be covered in https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6550

So closing this ticket now as duplicate.

**Comment by Archilegt** [comment]
Yes, it should be covered in #6550.
Ed meant this Glossary: https://bio.acousti.ca/glossary
