### ISSUE TITLE
A few issues to be considered.....

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6064]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Just thought I'd mention a couple of issues which maybe could be looked at during your fixing spell. 

1) I raised an issue that each time I add or edit a taxon description, it leads to the distribution map been included, which I do not want. Other users have also experienced this issue. 

2) Literature tab - this is something I do not require, therefore, is it possible to remove it from the site?

3) Taxonomic tree - is it possible to choose to have all the genera visible, istead of having to click on family/sub-family? This would be really handy as it is a tad annoying. 

4) Is it possible to embed a Twitter account on the home page?

Many thanks.

**Comment by benscott** [comment]
Thanks very much for your suggestions - I have raised a separate issue #6070 for your species page improvments.

We're aware of the twitter issue - #5877. Both of these issues will be worked on in the current sprint.  

For the taxonomic tree display, the tree rendering is very resource intensive so we need to limit the display to keep the sites working well.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Ok, thanks.

I have now figured out how to remove the literature tab so that is all sorted.
