### ISSUE TITLE
Back up

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6065]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

Back ups are not being generated again....

Thanks.....

http://icgf.myspecies.

**Comment by PaulKiddle** [comment]
Hi Anna, sorry about that. I believe I've fixed this, backups should be generating again now.
