### ISSUE TITLE
Species page customisation

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#6070]
I raised an issue that each time I add or edit a taxon description, it leads to the distribution map been included, which I do not want. Other users have also experienced this issue.

Literature tab - this is something I do not require, therefore, is it possible to remove it from the site?

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

I have now been able to remove the literature tab.
