### ISSUE TITLE
image duplicates

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6085]
- Added by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)
- Scratchpad: [Mormyridae - African weakly electric fishes](http://mormyrids.myspecies.info)

### Description:

This has been an issue for years now.  This issue has been posted previously, but never a fix. Images when added via the "add file" option are added as duplicates. If one tries to delete one duplicate, both disappear. See http://mormyrids.myspecies.info/en/taxonomy/term/745#
for example.

**Comment by PaulKiddle** [comment]
Hi John, this issue is already tracked at #5737 and we'll be getting to it soon
