### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6087]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Suddenly getting the Access denied page when I click on links on our site.

http://icgf.myspecies.info/red-data-book-categories/tρωτο-vulnerable-vu

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

More specifically, it happens when I click on any of the taxonomic term links in the taxon descriptions. 

I hope this can be fixed soon, because I can't really use the site at all now....

Thanks.....

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

The only term links that work are the taxa links themselves.

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

The only term links that work are the taxa links themselves.

**Comment by PaulKiddle** [comment]
Duplicate #6115
