### ISSUE TITLE
Technical difficulties message

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6090]
If one of the regular Technical Difficulties occurs while attaching a file to a biblio node an un-closeable modal box is stuck over the screen making you  have to restart biblio entry again. 
<img width="1185" alt="Screenshot 2020-01-05 at 12 46 25" src="https://user-images.githubusercontent.com/929684/71780372-d5c2f380-2fb9-11ea-8002-3e05f5df5bda.png">

**Comment by jrdh** [comment]
This was caused by high CPU usage on the bioacoustica server which in turn was caused by a large number of requests coming from a few Chinese crawlers. A temporary block has been put in place based on user agents.
