### ISSUE TITLE
Spam originating from Scratchpad

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6094]
- Added by [Darwyn Sumner](http://www.micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://www.micropezids.myspecies.info)

### Description:

It seems as though a message purporting to come from my site has been issued through the Scratchpad site.
From the failed delivery details I read X-Mailer: Drupal
The message seems to be thanking someone else for registering my site:
Thank you for registering at European Micropezids & Tanypezids. Your
application for an account is currently pending approval. Once it has been
approved, you will receive another e-mail containing information about how to
log in, set your password, and other details.
What's going on? Have you been hacked?

**Comment by PaulKiddle** [comment]
It seems like someone has signed up for an account your site using your own email address. It should be fine to just ignore this email.
