### ISSUE TITLE
Site Down Again

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#6104]
Hello,

Exactly the same problem as yesterday morning I'm afraid.....

Blank white page when I go to the site...

It worked okay yesterday afternoon though....

http://icgf.myspecies.info

Thanks

**Comment by PaulKiddle** [comment]
Sorry, we're still having problems with one of the database servers. We're working to get them up again as soon as possible.

**Comment by annanc14** [comment]
Thank you. Ours is working again now....

**Comment by PaulKiddle** [comment]
All sites should be up and running again now.
