### ISSUE TITLE
Many Taxonomy Term Pages Not Showing

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#6115]
Hello,

This has been a problem for nearly 3 weeks now.

When I try to view taxonomic term pages (other than those in the ΕΙΔΗ - SPECIES taxonomy) they don't show properly. They just say "Access Denied". 

There must be hundreds of pages affected, because I have 9 taxonomies. I will post some links to affected pages below:

[link 1](http://icgf.myspecies.info/red-data-book-categories/%CE%B5%CE%BA%CE%BB%CE%B9%CF%80%CE%BF%CE%BD%CF%84%CE%B1-%CF%83%CF%84%CE%B7-%CF%86%CF%85%CF%83%CE%B7-extinct-wild-ew#overlay-context=content/%25CE%25B5%25CE%25AF%25CE%25B4%25CE%25B7-%25CE%25BA%25CF%258C%25CE%25BA%25CE%25BA%25CE%25B9%25CE%25BD%25CE%25BF%25CF%2585-%25CE%25B2%25CE%25B9%25CE%25B2%25CE%25BB%25CE%25AF%25CE%25BF%25CF%2585-red-book-species) 

[link 2](http://icgf.myspecies.info/taxonomy/term/268#overlay-context=) 

Sometimes the first page in the list of terms works, but then all others below that in the grey side panel have the same problem. See [http://icgf.myspecies.info/nontaxonomy/term/603](url)

Please can you try and fix this as soon as possible. I have to finish working on a big part of this site soon, so I will have to show it to my boss. I can't do that though, when so many pages are not working.

Thank you very much.....

Anna

![access](https://user-images.githubusercontent.com/44700406/72969311-e18e2280-3dcd-11ea-9446-5a52f5726b7b.jpg)

**Comment by PaulKiddle** [comment]
Hi Anna, so sorry for the delay in this. I've tracked down the bug and fixed it on the live sites so this shouldn't happen again now.
