### ISSUE TITLE
Biblio entry is not showing pdf file to anyone else?

### ISSUE THREAD

**Issue by Morjens123** [NaturalHistoryMuseum/scratchpads2#6116]
My own username is "Admin".  I have tried to upload few pdf's to bibliography.  I can see my uploads (For example:  http://pistiaistyoryhma.myspecies.info/node/62) but any other logged user or not logged user cannot see the pdf file in the "File attachments:" section.  What could be the problem here?

**Comment by PaulKiddle** [comment]
Checking against other scratchpads this seems to be an issue on multiple sites. I'll try and investigate further.

**Comment by Archilegt** [comment]
Hello @Morjens123 and @PaulKiddle ,
This is also my problem. I am not finding an option to publish/unpublish a pdf, just to "move it to a private folder". I found no option for the case that started this thread: how to make a pdf that I see logged in available for external users. It may be worth to update the related training material too.
Cheers,
Charlie

**Comment by Archilegt** [comment]
@PaulKiddle , @alycejenni , @Morjens123 
I solved the issue. It is not a bug but a matter of documentation and wording. 
Steps for making the pdfs visible, from admins to public users: 
1) Log in as an admin. 
2) Go to People: Permissions: Biblio: Show download links. 
3) Tick the optional boxes as desired.
4) Click Save.
The topic is mentioned in the "Add literature" wiki tutorial, but in negative [https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Add-literature#restricting-access-to-attachments]. I would recommend to move the fragment to its own tutorial and redact it in both positive and negative, like "Giving/ restricting access to pdf attachments".
