### ISSUE TITLE
how can I host my page to my institutional server? 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6123]
- Added by [Azzah Al Jabri](http://omanflora.myspecies.info/en/user/2)
- Scratchpad: [e-Flora of Sultanate of Oman](http://omanflora.myspecies.info)

### Description:

I want to host my page "oman Flora" to my institutional server. I tried to follow the steps available in your develop page and didn't work.

**Comment by PaulKiddle** [comment]
Apologies, the website is a little out of date. The current best way to host your own Scratchpad is to run the docker containers included in this repo. Instructions are available on the wiki:
https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Installing-Scratchpads-with-Docker-Compose
