### ISSUE TITLE
Biblio-module updates

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6124]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

Could you please check for Drupal updates to the literature module? I am missing a feature to add not just ISSN but also e-ISSN to journals. I am also missing a default behavior for autofilling the ISSN field once that the journal field has been filled. ISSN are designed to work as unique identifiers. If after filling journal and ISSN for the first time those two values could be linked and trigger reciprocal autofill, that would be a time-saving improvement! :-)

**Comment by PaulKiddle** [comment]
Biblio 1.2 has been released not too long ago. https://www.drupal.org/project/biblio
This module hasn't been updated for a while so we'll have to be careful to make sure the upgrade doesn't break anything.

**Comment by alycejenni** [comment]
[2.9.17.1](http://scratchpads.org/news/2021-05/scratchpads-release-2917) now released
