### ISSUE TITLE
Bug in biblio-module

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6127]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

There is a bug in the biblio-module, tab "Publication". When filling the necessary fields for creating a reference, the values on tab Publication frequently disappear, leaving only the publication year filled. The bug already happens in the preview mode. Could you please check it out? It is causing double input burden. Thanks!

**Comment by PaulKiddle** [comment]
Can confirm

To reproduce:
 - Go to create a new biblio entry
 - Select publication type
 - Fill in title
 - Select Publication tab, fill in year of publication
 - Press Preview button

The preview shows but the publication tab now only has one field (year) on it.
Can reproduce this locally.

![Screenshot from 2020-01-28 12-10-03 - 1](https://user-images.githubusercontent.com/1755184/73263066-9d34c500-41c7-11ea-84ee-f146ab52375f.png)

**Comment by Archilegt** [comment]
Yes. And the info in tab Identifiers may get lost too when previewing.

**Comment by alycejenni** [comment]
This could be a similar issue to #5782 - i.e. form attributes not being carried over when the form is rebuilt.

**Comment by therobyouknow** [comment]
On basis that this has been implemented I'm assuming it has been released so I have removed it from current release sprint because completed/done/closed.  Thank you for all your work on it.
