### ISSUE TITLE
Increase title field character number

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6131]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

I have literature with a title string longer than 255 characters counting spaces, which is the maximum value permitted by the system. Could that be increased? That limit might not be only disrupting manual biblio entry but also bulk import of references. In case that the limit property cannot be increased, what could be the next solution in line? To change the field type to one that allows longer values? And if so, would that affect title-based internal connectivity of the site?

**Comment by jrdh** [comment]
Hi Archilegt,
Thanks for getting in touch, this is a duplicate issue that another user has already reported here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5796. Closing in favour of the original.
