### ISSUE TITLE
Backup 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6132]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Hello,

I would like to make a back up, but the old ones from months ago are not deleting ..... thanks

**Comment by jrdh** [comment]
Hi Anna / @annanc14,
I can see two backups available at the moment:
  - icgf.myspecies.info-20191218.104710.tar.gz
  - icgf.myspecies.info-20200204.133909.tar.gz

So it looks like the old ones have now been deleted, presumably you managed to remove them in some way?

I'll close this issue seeing as it looks like it's resolved but feel free to reopen it again if necessary.
