### ISSUE TITLE
Location nodes not saving

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6136]
- Added by [Ariane Buckenmeyer](http://acoela.myspecies.info/en/user/32003)
- Scratchpad: [The Stylet - ](http://acoela.myspecies.info)

### Description:

There's a bug in the location tab - submission of new location entries result in an error message, both when created and submitted individually, or submitted in bulk through an external file.

**Comment by PaulKiddle** [comment]
Resolved by 5d3d862
