### ISSUE TITLE
Specie Descriptions Down

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6140]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

None of my species description pages are opening.
It just goes to the Error page.

**Comment by PaulKiddle** [comment]
Hi Anna, the pages I checked seem to be working fine - can you link to an example of a broken one?

**Comment by PaulKiddle** [comment]
Found the problem, added a fix to the repo and production
