### ISSUE TITLE
Broken links - Phthiraptera.info

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6143]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

For all data records as well as anywhere else in the Phthiraptera.info website, the links to all the species, genus listed under the Taxonomic name:, are all broken. If one click on it an error message appears - " Error - The website encountered an unexpected error. Please try again later."  Appreciate if you could have a look at it. 

Appreciate if you can have a look at it. Thanks

**Comment by PaulKiddle** [comment]
I've added a fix to master and fixed on production too
