### ISSUE TITLE
Image information boxes

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6145]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

The information boxes on the images are all out of line, not encountered this issue before.

**Comment by jrdh** [comment]
Hi Barry, just to confirm - are you talking about this for example in the [gallery](http://agromyzidae.myspecies.info/gallery)?

![image](https://user-images.githubusercontent.com/4718259/74649590-c669c500-5177-11ea-9581-1c1140f0b1bf.png)

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Yes, that’s correct.

**Comment by jrdh** [comment]
This has been fixed and released to your site .

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Great, many thanks.
