### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by kailor** [NaturalHistoryMuseum/scratchpads2#6146]
Hello, 

I requested a new website. And it has been created. But when i press any of the links it goes to a 404 Not Found Website.

And it shows the following message:

`Not Found
The requested URL [redacted] was not found on this server.

Apache Server at projectwoop.myspecies.info Port 80`

**Comment by PaulKiddle** [comment]
Hi Kalior, I've fixed the underlying problem and your website is available again. Follow the link from your email again and you'll be able to log in.
