### ISSUE TITLE
Editing information on scientific names does not work

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6152]
- Added by [Jens G. Rohwer](http://lauraceae.myspecies.info/user/2)
- Scratchpad: [Lauraceae](http://lauraceae.myspecies.info)

### Description:

When I go to Lauraceae Taxonomy, then to the name Aiouea guatemalensis, I can see the information previously entered when I click on "view", but nothing any more when I click on "edit".  Therefore, it is not possible to update the information.
http://lauraceae.myspecies.info/category/lauraceae-taxonomy/lauraceae/aiouea/aiouea-guatemalensis#overlay-context=taxonomy/term/18519&overlay=admin/structure/taxonomy/lauraceae_taxonomy//17853%3Fdestination%3Dtaxonomy/term/17853

**Comment by jrdh** [comment]
This is now resolved and you should be able to edit everything as normal.

Notes for other devs: I fixed this by enabling the "Content translate" module. Not exactly sure what was causing the problem but it was language related - the term data was stored under the "und" language but the form was being built using the "en" language code so no data was shown. Presumably there was some half complete language install on this scratchpad and adding this extra module allowed it to correctly handle the languages.
