### ISSUE TITLE
Error: Specimens-Location-Country Tab 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6157]
- Added by [Ariane Buckenmeyer](http://acoela.myspecies.info/en/user/32003)
- Scratchpad: [The Stylet - ](http://acoela.myspecies.info)

### Description:

SLC tab ("acoela.myspecies.info is currently unable to handle this request") not loading.

**Comment by jrdh** [comment]
Specifically, http://acoela.myspecies.info/en/specimens-location-country seems to take a long time to load and then errors out.

**Comment by jrdh** [comment]
I've resolved this issue, at least in the sense that the page loads now. The problem was the number of rows that were being loaded from the database, as there was no pager on the view, were causing a timeout. I've added a pager with 1000 rows and it now loads.
