### ISSUE TITLE
Strange bug in authors' names

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6159]
Authors' surnames display correctly but their names appear in capitals and with every letter separated by a dot and a space.

![imagen](https://user-images.githubusercontent.com/60008120/75526587-ba54f180-5a1a-11ea-9e1d-78a7a8c0a45b.png)

**Comment by alycejenni** [comment]
Is this still an issue? I visited the [page in your screenshot](http://myriatrix.myspecies.info/content/identity-photophilus-folkmanov%C3%A1-1928-new-generic-synonymy-chilopoda-geophilomorpha#) and it seems to be fixed:
![image](https://user-images.githubusercontent.com/23579762/77086724-0c75ab00-69fa-11ea-8d6a-1ede39aaa665.png)

But I just want to check that this isn't a problem on other pages.

**Comment by Archilegt** [comment]
@alycejenni thank you for checking this. Yes, that particular case is fixed because I changed the order of the words in the name. However, the bug persists, see http://myriatrix.myspecies.info/content/resurrection-scolopendra-longipes-wood-and-scolopendra-cubensis-saussure-synonymy
In that example, the name Randy appears as if it were an acronym. 

Other strange bug in authors' names is represented by this example:
myriatrix.myspecies.info/content/über-polyzonium-germanicum-brandt
I entered one of the names as Nikolaevich, but the platform truncated it to Nikolaevic.

This bugs may be harder to correct because of some sort of automatic registering of strings happening in the background, combined with users' inability to access that name database and delete undesired spellings. It would be great to know how to permanently delete undesired spellings, so that they don't continue appearing as autofilling suggestions or overwriting the correctly entered spellings while saving.

**Comment by Archilegt** [comment]
Weird things also happen to the keywords. In this example, "British Columbia" is forced into capital letters:
http://myriatrix.myspecies.info/content/millipede-family-conotylidae-northwestern-north-america-complete-bibliography-family

**Comment by alycejenni** [comment]
The author names are presenting that way because they've been input in all-caps; we can't distinguish between an all-caps name and initials. To fix it you'll have to change the case of the names. This isn't a really a bug.

I'm not sure I understand what the issue with the keywords is - were these imported from somewhere else where "British Columbia" was _not_ in capital letters?

I will investigate the truncated author name.

**Comment by Archilegt** [comment]
Hi @alycejenni
I do understand the logic behind a surname in capitals sticking together and a given name in capitals splitting without it being a bug. I understand that the system will treat given names in capitals as acronyms and surnames in capitals still as surnames. No problem with that. It is just an undesired behavior and not a bug.
However, that is not the problem that I am trying to describe. What is happening to me is that even if I edit the name and write it in initial uppercase letter followed by lowercase letters, it will be populated again and again with the original, incorrect, full uppercase version. That is the bug: that I can't fix "MERCURIO, RANDY"  to "Mercurio, Randy" because somehow the system brings the original "casing" back. 
This is not necessarily a malfunction. It could be another undesired behavior, stemming from the interaction between SP and the cache of the used browser. That is a possible explanation that needs to be explored and documented. In some cases, deleting the browser cache may be the only way of getting rid from an incorrect spelling or "casing" of a name.
The same may be true for the issue with "British Columbia". Maybe the uppercase version is stored in my browser's cache. Also possible but less likely, the cache may be influencing truncated names.

A note on uppercase authors' names: in Myriatrix they come from populating references with Zootaxa's DOIs. Zootaxa stores authors' names in full uppercase letters. The same may happen to other journals. I will write a tailored workflow for procesing those references and post it on the Myriatrix GitHub wiki after we have a clearer view of what is truly happening with the "casing".

**Comment by Archilegt** [comment]
Hi @alicejenni
I tried fixing the casing "MERCURIO, RANDY J." from another computer and browser but it didn't work. This makes me think that we are indeed facing a bug. Current workaround: I changed the syntax of the name. Instead of rewriting it as "Mercurio, Randy J.", I rewrote it as "Randy J. Mercurio". Now it displays properly. 
This is just a partial solution, as some names may need to be written as "Surname, Given name" in order to display correctly. If those names get polluted with uppercase letters and therefore the given names spplited as acronyms, it may be impossible to solve that with this workaround. I am thinking on complex names from Spanish or Latin American authors, which need to be written in a very specific way for the paper authorship to display correctly.

**Comment by alycejenni** [comment]
Ah, apologies for the misunderstanding!
That's not due to the browser cache, it's because contributors are stored in the case that they were first entered, but queries are case-insensitive - so when you enter the correct capitalisation it finds the existing record with the same spelling and replaces it with that. An alternative workaround could be adding/removing the '.' in the name (`Mercurio, Randy J`) so that it registers as a different name, but I'll see if I can allow updating capitalisation as an actual "fix".

The truncated name is because `Nikolaevich` is being stored as `initials`, of which a contributor can only have 10. The way it's handled doesn't seem sensible so I'll fix that too.

Thanks for reporting these!

**Comment by Archilegt** [comment]
Sweet! Many thanks! :D
