### ISSUE TITLE
Disable and remove scratchpads_col module

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6164]
This is the module that powers the backend col data provider http://classifications.scratchpads.eu. For some reason it is enabled by default on all Scratchpads (dependency of `scratchpads_tweaks`), however there is no reason to include it. Trying to use the endpoint it provides throws an error, as no sites have the `scratchpads_col_terms_` tables in their databases.

Todo:
- [x] Create new branch & platform for classification.scratchpads.eu
- [x] Migrate site to new platform
- [x] Remove scratchpads_col from tweaks dependencies
- [x] Add migration to uninstall scratchpads_col
- [ ] Remove scratchpads_col files

**Comment by PaulKiddle** [comment]
NB: Create a separate repo/branch/release for classifications.scratchpads.eu, as the only site that uses this module.

**Comment by Archilegt** [comment]
@PaulKiddle , this is an essential module in Scratchpads and it shouldn't be removed but fixed and updated. This module gives both new and existing Scratchpads the ability to import a Catalogue of Life classification and to use it as a taxonomic backbone for information aggregation. It is specially important for Scratchpads dealing with large numbers of names. Please, also contact the CoL+ team and proceed to add more annual versions of the CoL. The 2015 versions are way behind from current updates.

**Comment by PaulKiddle** [comment]
@Archilegt I believe you're talking about the module `scratchpads_classification_service_client`, which allows scratchpads to import catalog of life data?
As opposed to `scratchpads_col`, which I think is used only by the `classifications.scratchpads.eu` site, as we only need one data provider.

The former is definitely valuable and I agree should be updated. The latter I think can be removed safely from all standard scratchpads.

**Comment by Archilegt** [comment]
@PaulKiddle oki doki!
