### ISSUE TITLE
Ecological interactions not displaying second taxon in some cases

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6170]
The commit at 10f6a9d12393107f1ba957926df13f371c3cacbc assumed if `$right_fields` is not defined then there is no second taxon defined.

However, this is not the case for http://algaldiseases.myspecies.info/interactions - viewing individual nodes shows there are second taxa defined, but they are not showing in list view. Same also for interaction type (`field_interaction_type`).

My guess is that `$ecoint_node->field_int_collection` either is not using the `und` language or its value is not at index `0` for some reason... needs some investigation.

Interactions were imported from spreadsheet:

[TEMPLATE-import_into_ecological_interactions_xls (9).zip](https://github.com/NaturalHistoryMuseum/scratchpads2/files/4325703/TEMPLATE-import_into_ecological_interactions_xls.9.zip)

**Comment by jrdh** [comment]
@PaulKiddle I've managed to fix in this on a local copy of their database by completely rebuilding the eco int content type as it is a **_mess_** on the algal diseases scratchpad. There doesn't seem to be any eco int data on the site at the moment so I'll fix it asap as it involves deleting all the fields and recreating them correctly which will lose any field data too. The template you uploaded has nothing in it as far as I can see, do you have a populated template from them knocking around anywhere? Would be good to test that importing their data works before I fix their eco int content type as it's pretty destructive.

**Comment by PaulKiddle** [comment]
Afraid I only have the attached file that was sent to me, I assumed it was populated. They did say they had the same results using the template vs manually adding interactions, i.e. species B not being visible once the records are present, so I'm sure just adding some manual entries will be enough to check everything works.

**Comment by jrdh** [comment]
This is resolved now, I fixed it by going through and recreating their ecological interactions content type including the embedded `field_int_collection` field collection type too. To do this I essentially just made their site look exactly like the currently working content types/field collections on http://phthiraptera.info/ and http://bio.acousti.ca/.
