### ISSUE TITLE
USA blockade affects Docker installation

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6172]
Please, find a parallel alternative to Docker. Docker has to comply with USA unilateral country blockades, which affects access depending on ever-changing politics. Developers from Cuba cannot use Docker. See error report below:

```
Step 1/2 : FROM mysql:5.6
ERROR: Service 'mysql' failed to build: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nSince Docker is a US company, we must comply with US export control regulations. In an effort to comply with these, we now block all IP addresses that are located in Cuba, Iran, North Korea, Republic of Crimea, Sudan, and Syria. If you are not in one of these cities, countries, or regions and are blocked,


docker: Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nSince Docker is a US company, we must comply with US export control regulations. In an effort to comply with these, we now block all IP addresses that are located in Cuba, Iran, North Korea, Republic of Crimea, Sudan, and Syria. If you are not in one of these cities, countries, or regions and are blocked, please reach out to
```

**Comment by jrdh** [comment]
Hi @Archilegt, thanks for reporting this, it's not something we've been aware of up to this point and the core development team looking after Scratchpads is based in the UK so we haven't experienced it first hand either. At present, while we appreciate the frustration, it is unlikely that we'll be able to do anything about this problem soon, particularly with the additional burden on the Museum and its technical staff that the covid-19 pandemic is causing. The most likely solution would be for us to setup our own docker hub which hosts the scratchpads images.

In the meantime, we would recommend you try some of the workarounds that other users have attempted, there are a few options here: https://github.com/docker/hub-feedback/issues/369 and probably elsewhere too. I would expect either setting up your own mirror outside of Cuba or trying to use a mirror already up outside of Cuba would be your best bet. Hope you manage to get things up and running!
