### ISSUE TITLE
media galery specification when image is open

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6175]
- Added by [Maria Zabaleta](http://rocosos.myspecies.info/user/2)
- Scratchpad: [Puntas Rocosas del Uruguay](http://rocosos.myspecies.info)

### Description:

I would see the media galery name below the photo, not only the  taxonomic name, the creator name and the licence type.
I use the galery name to know the place where the photo is belong.
Is it possible to include it in the little table below the image?
I can't find the possibility to modify it.
Thank you

**Comment by alycejenni** [comment]
Hi Maria,

I've made the change for you so I could test that it was working, but for anyone else with the same issue (or if you want to know how I did it/make other changes):

1. Go to Admin > Structure > File Types > Image > manage display
2. Hover over "default" in the top bar, next to "Manage display":
![image](https://user-images.githubusercontent.com/23579762/78038216-7ed47c80-7364-11ea-8b14-004567c2acf2.png)
3. Select "colorbox"
4. Make any changes you need to
5. Save.

Let us know if you have any issues!

**Comment by scratchpads** [comment]
Comment by [Maria Zabaleta](http://rocosos.myspecies.info/user/2)

HI,

thank you very much for your help.
And for your explanation of the process.  I can improve my capacities to manage the site.

Excuse me for my very bad english.

Maria
