### ISSUE TITLE
Domain issue with GoDaddy & Scratchpad

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6179]
This is a continuation of issue #5785 that I thought was resolved but is not.  I am using a GoDaddy domain http://poissongabon.info/ for my 2nd Scratchpad.  When I set this up originally, everything worked fine. Well over a year ago, it stopped working, for unknown reasons.  When I put "poissongabon.info" in my web browser I get a 404 error  and it says "Apache Server at 157.140.2.32 Port 80."  Strangely, once in a while when I try this, the page loads. I have reread the comments on issue #5785, but I am not sure what I need to do to restore function. Attached are screen caps of the DNS management info from GoDaddy. What do you suggest?
<img width="1232" alt="Screen Shot 2020-03-29 at 12 11 24 PM" src="https://user-images.githubusercontent.com/21112349/77854322-9cb0ae80-71b7-11ea-8a86-01724969a2e0.png">
<img width="564" alt="Screen Shot 2020-03-29 at 12 11 57 PM" src="https://user-images.githubusercontent.com/21112349/77854324-9d494500-71b7-11ea-8c43-f8674efe1398.png">

**Comment by PaulKiddle** [comment]
I believe if you remove the forwarding rule this should work correctly. GoDaddy's forwarding configuration doesn't pass the domain name to our servers, so they can't tell which scratchpad a user is trying to access.
It looks like your actual DNS records are set correctly for both `www.poissongabon.info` and `poissongabon.info`, so forwarding shouldn't be necessary anyway.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Thanks, Paul.  Removing the forwarding seems to have fixed the issue.  Thanks very much!
