### ISSUE TITLE
 Error message The archive "GBIF DwCA" has not yet been created.

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6181]
- Added by [Ilia Gjonov](http://bg-cicadidae.myspecies.info/user/2)
- Scratchpad: [Bulgarian Cicadidae](http://bg-cicadidae.myspecies.info)

### Description:

Dear Sirs,
My DarwinCore Archiver (DwC-A) and Darwincore in Tools menu are enabled but when I'm trying to download a DwC archive on http://bg-cicadidae.myspecies.info/gbif-dwca.zip I receive an answer:
Error message The archive "GBIF DwCA" has not yet been created.

I tried to run cron many times but I don't have a result.

Please help me!

**Comment by scratchpads** [comment]
Comment by [Ilia Gjonov](http://bg-cicadidae.myspecies.info/user/2)

I also don't have a page on admin/config/system/dwcaexport. In the System page Darwin Core export is missing. I have just Antibot, Forum, Backup and Google Analytics.

**Comment by cicadina1** [comment]
Thanks! It is working now.

**Comment by alycejenni** [comment]
I'm not actually sure how this was fixed because I never got around to looking at it, but I'm glad it's working again now! Let us know if it becomes a problem again.
