### ISSUE TITLE
AJAX error when tring to delete terms in Taxonomy

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6182]
- Added by [Ilia Gjonov](http://bg-cicadidae.myspecies.info/user/2)
- Scratchpad: [Bulgarian Cicadidae](http://bg-cicadidae.myspecies.info)

### Description:

I can't delete some terms in Taxonomy.

The reported error is:
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Service unavailable (with message)
ResponseText:

**Comment by alycejenni** [comment]
Hi Ilia, what exactly were you trying to delete?

**Comment by PaulKiddle** [comment]
I've upgraded this site to the latest version which should fix taxonomy-related issues
