### ISSUE TITLE
Problem with rich text editor

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6184]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

The issue is located in the biblio module, section "Abstract". It is appearing today in the basic view, without the rich text editor as usual. When I try to change to rich text editor by clicking the active text below the typing box, nothing happens. Curiously, in the section "Full text" the rich text editor is active, and the active text below the box works for enabling or disabling the editor. Therefore, it seems that the issue is very localized, just in "Abstract" section.

**Comment by Archilegt** [comment]
Normal behavior is back. I don't know what happened before.

**Comment by Archilegt** [comment]
Now I know. The text format for that specific reference and for that specific abstract was set to plain text and not to filtered HTML.
This issue can be closed now.
