### ISSUE TITLE
Time zone handling

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6185]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

I activated the Events Tool and posted two events. After posting the second event I noticed a strange behavior of the date. I further inspected the issue and it seems that problems with event dates may come from how each SP handles the time zone. The default setting is "Site's time zone", which for proper behavior of date in events should probably be changed to "Date's time zone". This can be changed by going to Structure, Content types, Event, Manage fields, Event date, Field settings. Once there go to box "Time zone handling", select "Date's time zone" and click on "Save field settings".
I did that, but as there is already data in the field, the settings cannot longer be changed. Is there a way to force this at your end or should I delete the two events and then attempt to change the time zone handling settings?

**Comment by alycejenni** [comment]
There's currently no way to bulk update timezones for fields, so you'll have to delete and recreate them after changing the settings, sorry.
