### ISSUE TITLE
Taxonomy Import Issue

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6189]
- Added by [Ellie](http://scan.myspecies.info/user/3457)
- Scratchpad: [SCAN: The Schistosomiasis Collection at the NHM](http://scan.myspecies.info)

### Description:

I am having an issue with importing taxon names. I tried to manually create a class term (Gastropoda) but I believe it has got stuck and now I can't import any new taxonomy records.

The error I am receiving is: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'revision_id'

Thanks

**Comment by alycejenni** [comment]
Did you get an error when you created the Gastropoda term or did it all appear to save okay?

**Comment by scratchpads** [comment]
Comment by [Ellie](http://scan.myspecies.info/user/3457)

I believe so yes. I have exported the taxonomy records and it shows Gastropoda in permitted values tabs but not in the template tab (or on the site).

**Comment by alycejenni** [comment]
I've removed the only reference to Gastropoda that I can find in the database, so try creating or importing again and let me know if you get any more errors!

**Comment by scratchpads** [comment]
Comment by [Ellie](http://scan.myspecies.info/user/3457)

It worked! Thanks for your help :)
