### ISSUE TITLE
GBIF data displayed incorrectly

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6193]
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

Disrtibution map of Cerotelion racovitzai display GBIF records for UK and Sweden. There are no occurrences of this species in GBIF at all!

http://sciaroidea.info/taxonomy/term/40540/descriptions

https://www.gbif.org/occurrence/search?taxon_key=1563717

**Comment by alycejenni** [comment]
Either the taxon wasn't present in GBIF or there was an temporary issue with the GBIF API when the map for this term was first loaded, because it was incorrectly mapped to the GBIF taxon key `1563698`.

I've reloaded the row in the database so it's now mapped to the correct one.
