### ISSUE TITLE
AJAX error - Two taxa disappeared

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6195]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

I lost two taxa due to an error. I can't find them in the classification: Baskoiulus rusticans and Mesoiulus rusticanus. Could you please restore them to the classification? Thanks in advance.

Error message:
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Internal Server Error
ResponseText:

**Comment by Archilegt** [comment]
AJAX errors are now constantly happening while working with the classification (= taxonomic backbone). Text of the last error, while creating a new entry:

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Internal Server Error
ResponseText: [{"command":"settings","settings":{"basePath":"\/","pathPrefix":"","ajaxPageState":{"theme":"scratchpads_admin","theme_token":"v4jvN1VdBYiROrCNHRV5QeasdzmUqxdUQVDmd7xgS3Q","jquery_version":"1.8","css":{"modules\/overlay\/overlay-parent.css":1},"js":{"misc\/jquery.ba-bbq.js":1,"modules\/overlay\/overlay-parent.js":1}},"insert_from_view":{"init":false,"settings":[{"machine_name":"pensoft_publication_references","name":"Pensoft publication references","label":"Add Reference citation","view":"publication_citations_references","display":"references","field":"nothing","width":"75%","height":"75%","icon":"sites\/all\/modules\/custom\/publication\/modules\/publication_html_format\/images\/references.png","row_tag":"span","wrap_tag":""},{"machine_name":"pensoft_publication_figures","name":"Pensoft publication figures","label":"Add Figure citation","view":"publication_citations_figures","display":"figures","field":"nothing","width":"75%","height":"75%","icon":"sites\/all\/modules\/custom\/publication\/modules\/publication_html_format\/images\/figures.png","row_tag":"span","wrap_tag":""},{"machine_name":"pensoft_publication_specimens","name":"Pensoft publication specimens","label":"Create specimen table","view":"publication_create_specimens","display":"default","field":"nothing","width":"75%","height":"75%","icon":"sites\/all\/modules\/custom\/publication\/modules\/publication_html_format\/images\/specimens.png","row_tag":"tr","wrap_tag":"table"}]},"mediaelementAll":true,"overlay":{"paths":{"admin":"node\/*\/webform\nnode\/*\/webform\/*\nnode\/*\/webform-results\nnode\/*\/webform-results\/*\nnode\/*\/submission\/*\nbhl_viewer\/*\nnode\/*\/clone\nuser\/*\/exif-custom\nuser\/*\/femail\nfemail\/remove\/*\nfemail\/verify\/*\nfield-collection\/*\/*\/edit\nfield-collection\/*\/*\/delete\nfield-collection\/*\/add\/*\/*\nfile\/add\nfile\/add\/*\nfile\/*\/edit\nfile\/*\/delete\ninsert-from-view\/*\nmedia\/*\/edit\/*\nmedia\/browser\nmedia\/browser\/*\nnode\/*\/edit\nnode\/*\/delete\nnode\/*\/revisions\nnode\/*\/revisions\/*\/revert\nnode\/*\/revisions\/*\/delete\nnode\/add\nnode\/add\/*\nuser\/*\/openid\nuser\/*\/openid\/delete\noverlay\/dismiss-message\npublication\/add\npublication\/add\/*\npublication\/*\/edit\npublication\/*\/delete\nfile\/*\/move\nscratchpads-front\/edit\nsetup\nsetup\/*\nsetup-complete\nuser\/register\nuser\/*\/shortcuts\nnode\/*\/simplenews\nuser\/*\/spambot\nadmin\nadmin\/*\nbatch\ntaxonomy\/term\/*\/edit\nnode\/*\/translate\nuser\/*\/cancel\nuser\/*\/edit\nuser\/*\/edit\/*\ntaxonomy\/*\/translate\ntaxonomy\/*\/translate\/*\nrelation-select\/add\/*\/*\nnode\/*\/translate\/*\nnode\/*\/edit\/*\ntaxonomy\/term\/*\/translate\ntaxonomy\/term\/*\/translate\/*\ntaxonomy\/term\/*\/edit\/*\nuser\/*\/translate\nuser\/*\/translate\/*\nnode\/*\/revisions\/view\/*\/*\nimport\nimport\/*\nbiblio\/import","non_admin":"admin\/structure\/block\/demo\/*\nimport\/*\/xlstemplate\nadmin\/reports\/status\/php"},"pathPrefixes":[],"ajaxCallback":"overlay-ajax"},"states":{"#edit-field-unit-name2--3":{"visible":{":input[name*=\u0022field_unit_name1\u0022]":{"filled":true}}},"#edit-field-unit-name3--3":{"visible":{":input[name*=\u0022field_unit_name2\u0022]":{"filled":true}}},"#edit-field-unit-name4--3":{"visible":{":input[name*=\u0022field_unit_name3\u0022]":{"filled":true}}},"#edit-field-unit-indicator1--3":{"visible":{":input[name*=\u0022field_unit_name1\u0022]":{"filled":true}}},"#edit-field-unit-indicator2--3":{"visible":{":input[name*=\u0022field_unit_name2\u0022]":{"filled":true}}},"#edit-field-unit-indicator3--3":{"visible":{":input[name*=\u0022field_unit_name3\u0022]":{"filled":true}}},"#edit-field-unit-indicator4--3":{"visible":{":input[name*=\u0022field_unit_name4\u0022]":{"filled":true}}},"#edit-path-alias":{"!enabled":{"input[name=\u0022path[pathauto]\u0022]":{"checked":true}}}},"ajax":{"edit-field-vernacular-name-collection-und-0-remove-button--3":{"callback":"field_collection_remove_js","effect":"fade","wrapper":"field-vernacular-name-collection-add-more-wrapper--2","event":"mousedown","keypress":true,"prevent":"click","url":"\/system\/ajax","submit":{"_triggering_element_name":"field_vernacular_name_collection_und_0_remove_button","_triggering_element_value":"Remove"}},"edit-field-vernacular-name-collection-und-add-more--3":{"callback":"field_add_more_js","wrapper":"field-vernacular-name-collection-add-more-wrapper--2","effect":"fade","event":"mousedown","keypress":true,"prevent":"click","url":"\/system\/ajax","submit":{"_triggering_element_name":"field_vernacular_name_collection_add_more","_triggering_element_value":"Add another item"}}},"urlIsAjaxTrusted":{"\/system\/ajax":true,"\/admin\/structure\/taxonomy\/myriatrix\/hierarchy\/form_callback\/add-form\/":true},"field_group":{"fieldset":"form","htab":"form","htabs":"form"},"tableDrag":{"field-vernacular-name-collection-values--3":{"field_vernacular_name_collection-delta-order":[{"target":"field_vernacular_name_collection-delta-order","source":"field_vernacular_name_collection-delta-order","relationship":"sibling","action":"order","hidden":true,"limit":0}]}},"linkit":{"autocompletePath":"http:\/\/myriatrix.myspecies.info\/linkit\/autocomplete?s=","modulepath":"sites\/all\/modules\/contrib\/linkit","autocomplete":{"charLimit":3,"wait":250,"remoteTimeout":5000,"caseSensitive":true},"url":{"ckeditor":"\/linkit\/dashboard\/ckeditor"}},"tagmap":[]},"merge":true},{"command":"insert","method":"prepend","selector":"head","data":"\u003Cscript type=\u0022text\/javascript\u0022 src=\u0022\/\/myriatrix.myspecies.info\/sites\/myriatrix.myspecies.info\/files\/advagg_js\/js__HAl1T3T9x2nx_Vj5_05ypqcIHW29WMlDTaqaYd3Ua6c__T91yrdlJP9LKxIxE95aiX8Rv47-aQ76x9tqXVYJon8c__3wKn-QAtqjy3WhExZmqNVMBWwDHJp_fLhLBu3sFzoyo.js\u0022\u003E\u003C\/script\u003E\n","settings":null},{"command":"add_css","data":"\u003Clink type=\u0022text\/css\u0022 rel=\u0022stylesheet\u0022 href=\u0022\/\/myriatrix.myspecies.info\/sites\/myriatrix.myspecies.info\/files\/advagg_css\/css__W6T5o8wo8GS0Ge74rcEOwSysaTDPqaT5qKOdelhYqCY__jeyJmEHZVUVdlAXi3vk0Gw3kl5ECRhaZL5mpnCrDwU8__3wKn-QAtqjy3WhExZmqNVMBWwDHJp_fLhLBu3sFzoyo.css\u0022 media=\u0022all\u0022 \/\u003E\n"},{"command":"insert","method":"replaceWith","selector":"[data-tui-this-term=\u002237874\u0022] div","data":"\u003Cdiv\u003E\u003Cspan\u003E\u0026nbsp;\u003C\/span\u003EScolopendra morsicans\u003Ca href=\u0022\/admin\/structure\/taxonomy\/\/hierarchy\/form_callback\/edit-form\/37874\u0022 class=\u0022edit-term-link use-ajax\u0022 data-tui-this-term=\u002237874\u0022\u003Eedit\u003C\/a\u003E \u003Ca href=\u0022\/myriatrix\/scolopendra-morsicans\u0022 class=\u0022edit-term-link view\u0022\u003Eview\u003C\/a\u003E\u003C\/div\u003E","settings":null},{"command":"insert","method":"html","selector":"#tui-tree-subcontainer","data":"\u003Col\u003E\u003Cli data-tui-this-term=\u00226460\u0022 class=\u0022tui-has-children tui-open\u0022\u003E\u003Cdiv class=\u0022tui-highlight\u0022\u003E\u003Cspan\u003E\u0026nbsp;\u003C\/span\u003EMyriapoda\u003Ca href=\u0022\/admin\/structure\/taxonomy\/myriatrix\/hierarchy\/form_callback\/edit-form\/6460\u0022 class=\u0022edit-term-link use-ajax\u0022 data-tui-this-term=\u00226460\u0022\u003Eedit\u003C\/a\u003E \u003Ca href=\u0022\/myriatrix\/myriapoda\u0022 class=\u0022edit-term-link view\u0022\u003Eview\u003C\/a\u003E\u003C\/div\u003E\u003Col\u003E\u003Cli data-tui-child-of=\u00226460\u0022 data-tui-this-term=\u00227151\u0022 class=\u0022tui-has-children tui-open\u0022\u003E\u003Cdiv class=\u0022tui-highlight\u0022\u003E\u003Cspan\u003E\u0026nbsp;\u003C\/span\u003EChilopoda\u003Ca href=\u0022\/admin\/structure\/taxonomy\/myriatrix\/hierarchy\/form_callback\/edit-form\/7151\u0022 class=\u0022edit-term-link use-ajax\u0022 data-tui-this-term=\u00227151\u0022\u003Eedit\u003C\/a\u003E \u003Ca href=\u0022\/myriatrix\/chilopoda\u0022 class=\u0022edit-term-link view\u0022\u003Eview\u003C\/a\u003E\u003C\/div\u003E\u003Col\u003E\u003Cli data-tui-child-of=\u00227151\u0022 data-tui-this-term=\u002237205\u0022 class=\u0022tui-has-children tui-closed tui-never-opened\u0022\u003E\u003Cdiv\u003E\u003Cspan\u003E\u0026nbsp;\u003C\/span\u003ENotostigmophora\u003Ca href=\u0022\/admin\/structure\/taxonomy\/myriatrix\/hierarchy\/form_callback\/edit-form\/37205\u0022 class=\u0022edit-term-link use-ajax\u0022 data-tui-this-term=\u002237205\u0022\u003Eedit\u003C\/a\u003E \u003Ca href=\u0022\/myriatrix\/notostigmophora\u0022 class=\u0022edit-term-link view\u0022\u003Eview\u003C\/a\u003E\u003C\/div\u003E\u003C\/li\u003E\u003Cli data-tui-child-of=\u00227151\u0022 data-tui-this-term=\u002237206\u0022 class=\u0022tui-has-children tui-open\u0022\u003E\u003Cdiv class=\u0022tui-highlight\u0022\u003E\u003Cspan\u003E\u0026nbsp;\u003C\/span\u003EPleurostigmophora\u003Ca href=\u0022\/admin\/structure\/taxonomy\/myriatrix\/hierarchy\/form_callback\/edit-form\/37206\u0022 class=\u0022edit-term-link use-ajax\u0022 data-tui-this-term=\u002237206\u0022\u003Eedit\u003C\/a\u003E \u003Ca href=\u0022\/myriatrix\/pleurostigmophora\u0022 class=\u0022edit-term-link view\u0022\u003Eview\u003C\/a\u003E\u003C\/div\u003E\u003Col\u003E\u003Cli data-tui-child-of=\u002237206\u0022 data-tui-this-term=\u00227152\u0022 class=\u0022tui-has-children tui-closed tui-never-opened\u0022\u003E\u003Cdiv\u003E\u003Cspan\u003E\u0026nbsp;\u003C\/span\u003ECraterostigmomorpha\u003Ca href=\u0022\/admin\/structure\/taxonomy\/myriatrix\/hierarchy\/form_callback\/edit-form\/7152\u0022 class=\u0022edit-term-link use-ajax\u0022 data-tui-this-term=\u00227152\u0022\u003Eedit\u003C\/a\u003E \u003Ca href=\u0022\/myriatrix\/craterostigmomorpha\u0022 class=\u0022edit-term-link view\u0022\u003Eview\u003C\/a\u003E\u003C\/div\u003E\u003C\/li\u003E\u003Cli data-tui-child-of=\u002237206\u0022 data-tui-this-term=\u002237281\u0022 class=\u0022tui-has-children tui-closed tui-n

**Comment by Archilegt** [comment]
Maybe related to #6182

**Comment by PaulKiddle** [comment]
Both these taxa were set as parents of each other, so they were detached from the tree. I've restored them both to the root node, you should be able to move them to the correct place now.

**Comment by Archilegt** [comment]
Hi @PaulKiddle ,
Many thanks for the fix! 
This may be useful to you: The taxa were "detached" from the tree by me. I was holding the branch (with those two taxa) and dragging it to a new place in the tree. I should have released the click by accident in the middle of nowhere, so the branch was not able to reattach itself to any parent taxon (not even to an incorrect one). That may have created the "circular parent" error. 
I just wanted to document this in the case that it could be possible to prevent similar errors in the future by giving some sort of "short memory" to any detached-and-dragged branch of the tree. The "short memory" could store the tree parent taxon for the higher taxa child of the detached branch. That could prevent the branch from disappearing in case that it is accidentally dropped on a blank space. The desired behavior would be that the accidentally released-on-nowhere branch returns to its original place in the tree. I hope that this makes sense.
Thank you again!

P.S.: Maybe a similar fix already exists in Drupal Core but not in SP because of the recoded taxonomy handling?
