### ISSUE TITLE
how to update gbif-dwca.zip

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6202]
- Added by [Ilia Gjonov](http://bg-cicadidae.myspecies.info/user/2)
- Scratchpad: [The Bulgarian Cicadidae](http://bg-cicadidae.myspecies.info)

### Description:

I have new info in my scratchpad and I would like to update the gbif-dwca.zip. I tried "clear all caches" and "run CRON manually" .
How to refresh it?

**Comment by scratchpads** [comment]
Comment by [Ilia Gjonov](http://bg-cicadidae.myspecies.info/user/2)

Tried to disable DarwinCore Archiver and to enable it after but I can't disable it.

**Comment by PaulKiddle** [comment]
Hi Ilia,

Currently this file does not update automatically, but you can update it manually by submitting the form at the following page:
http://bg-cicadidae.myspecies.info/admin/config/content/scratchpads_gbif_registry_client

**Comment by PaulKiddle** [comment]
This file should be updated in the `dwcarchiver_cron` function, but doesn't because it's a hard-coded archive and not in the database.

**Comment by Archilegt** [comment]
Closed issue #6332 may be relevant to this issue.
