### ISSUE TITLE
High CPU usage on cron

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6204]
myriatrix.myspecies.info/ is consuming a huge amount of CPU when running cron, causing problems on sp-control. Need to determine what's going on.

**Comment by PaulKiddle** [comment]
Problem appears to be apachesolr_cron function

**Comment by PaulKiddle** [comment]
Updating apachesolr module doesn't seem to have fixed it. Will need to do a more thorough investigation.

**Comment by Archilegt** [comment]
Any chance that those problems may have caused the disappearance of two taxa reported on #6195?

**Comment by PaulKiddle** [comment]
Looks like it does, somehow they've both been set as each other's parent causing a circular dependency.
