### ISSUE TITLE
Altered name of tabs

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6206]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

Tab "Literature" and tab "Media" got their names changed to "Search results". I have not made that edit. Could you please investigate the cause and let me know if I should manually correct the tab names? Thanks!

**Comment by PaulKiddle** [comment]
Apologies, these have been put back to normal now.
