### ISSUE TITLE
Can't open Species Descriptions.

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6210]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

Can't open Species Descriptions.from Content or the Home Page

It goes to the error page....

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

Also can't save terms after editing.

**Comment by PaulKiddle** [comment]
Error page seems to be a bug specific to certain taxa: http://icgf.myspecies.info/taxonomy/term/5012

**Comment by PaulKiddle** [comment]
I've updated this site to the latest platform so this should be working for all taxa now
