### ISSUE TITLE
Editing existing specimens shows empty fields

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6214]
- Added by [lukas.scharer](http://macrostomorpha.info/user/2)
- Scratchpad: [Macrostomorpha](http://macrostomorpha.info)

### Description:

When I try to edit an existing specimen all fields show up as empty, although clearly containing data (tested in both Safari and Firefox).

**Comment by lukasscharer** [comment]
This problem still persists. Is there any progress on this @PaulKiddle? It seems like a large enough bug to deserve immediate attention.

**Comment by PaulKiddle** [comment]
Hi Lukas, I'm looking into this. It seems to be a problem with the drupal language module.
I've made a change to the record at http://macrostomorpha.info/node/4700 which has fixed the problem for that item.
I can apply the same change to all of the affected records for you.
Can you tell me, does the problem affect all specimen/observation records, or only ones from a certain date range/certain batches?

**Comment by lukasscharer** [comment]
Hi @PaulKiddle. Thanks for looking into this. I have not checked all the specimens, but I checked in total about 30 old and new ones, and it seems that these all have that same issue. The one you fixed indeed seems fine, though. So yes, if you could fix that for all of them it would be great.
However, will that happen again once I upload new specimens? I am planning to upload several hundred new specimens in the coming weeks.
Ana also, once you have fixed it for all existing specimens, I will download, modify and reupload an import file and check if that recreates the problem.

**Comment by PaulKiddle** [comment]
I've updated all of the records for you.
I just tested adding new records both through the form and the spreadsheet import and had no problems, so you should be fine from here.

**Comment by lukasscharer** [comment]
Thanks @PaulKiddle. The problem seems solved.
