### ISSUE TITLE
Error displaying Description tab

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6218]
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

If description exists for a taxon, the tap Description produces an error:
http://sciaroidea.info/taxonomy/term/45105/descriptions

**Comment by PaulKiddle** [comment]
```
Error: Call to undefined function gm3_js_point_settings() in gm3_field_js_point_settings() (line 1175 of /var/aegir/platforms/scratchpads-2.9.12/sites/all/modules/custom/gm3/gm3_field/gm3_field.module).
```

**Comment by PaulKiddle** [comment]
Duplicate of #6291

I've upgraded this site to the latest version, which contains a fix for this issue
