### ISSUE TITLE
Taxon descriptions error

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6219]
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

Newly created taxon descriptions produce error:
http://sciaroidea.info/node/59946

**Comment by PaulKiddle** [comment]
I've upgraded this site to the latest version, which contains a fix for this issue
