### ISSUE TITLE
Media published appear in editor view but not in public view

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6221]
- Added by [sandy](http://solanaceaesource.org/user/17)
- Scratchpad: [Solanaceae Source](http://solanaceaesource.org)

### Description:

I might be doing something wrong, but when I upload pictures to the Solanaceae Source site - I can see them when I am logged in, but if I log out and try as a user they do not show. 
Thanks Sandy

**Comment by Archilegt** [comment]
Hi Sandy,
Try going to the Content menu. Last section is the "Files". Look at the "Image" file type and check if there are images counted as "Unpublished". If so, then open the image editor, select the unpublished images and publish them. Hopefully that will solve it. If not, try posting a screenshot of what you see.
Cheers,
Carlos

**Comment by alycejenni** [comment]
I've just had a look and it seems like all the images are visible to anonymous users now - closing  as I'm assuming this has been sorted out since the issue was opened (please reopen if it hasn't!)
