### ISSUE TITLE
Error on opening "Descriptions" tab

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6223]
- Added by [Ian Kitching](http://sphingidae.myspecies.info/user/29)
- Scratchpad: [Sphingidae Taxonomic Inventory](http://sphingidae.myspecies.info)

### Description:

When I click on the "Descriptions" tab of any taxon, I get the following error message.

Sphingidae Taxonomic Inventory
Creating a taxonomic e-science
Error
The website encountered an unexpected error. Please try again later. 

For example, on http://sphingidae.myspecies.info/taxonomy/term/1559/descriptions

As much of the work I planned to do from home involves updating the Sphingidae Taxonomic Inventor, this is a big problem.

**Comment by jpsullivan65** [comment]
I am also experiencing this issue.

**Comment by PaulKiddle** [comment]
Hi both,

I'm upgrading both of these sites now which should fix the issue.

**Comment by jpsullivan65** [comment]
I am still experiencing this issue.

**Comment by PaulKiddle** [comment]
Yesterday's upgrades failed. I've successfully run them today so please try again.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Sorry, no change.  E.g. when I go to http://mormyrids.myspecies.info/en/taxonomy/term/354/descriptions

I get:

Error
The website encountered an unexpected error. Please try again later.

**Comment by PaulKiddle** [comment]
@jpsullivan65 I had assumed you were talking about poissongabon.info before. I have now updated mormyrids too, so this error should be resolved on both sites.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Working now, thank you!
