### ISSUE TITLE
description of species 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6225]
- Added by [Rahmah Jrais](http://floraofksa.myspecies.info/user/2)
- Scratchpad: [E Flora of the Kingdom of Saudi Arabia ](http://floraofksa.myspecies.info)

### Description:

when I open description icon in each species it gives me error

**Comment by PaulKiddle** [comment]
Hi Rahmah, I have updated your site to the latest scratchpads version which should fix your problem.
