### ISSUE TITLE
spam comments

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6227]
- Added by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)
- Scratchpad: [Mormyridae - African weakly electric fishes](http://mormyrids.myspecies.info)

### Description:

I have accumulated 19,300 spam comments on the blog articles that appear on my site. These are not shown to the public but I see them when I'm logged in as admin.There are way too many to delete one-by-one or even page-by-page. 

http://mormyrids.myspecies.info/en/node/473#overlay=en/admin/content/comment/approval

Can you remind me how I can turn off comments to articles and tell me how I can delete all unapproved comments on my site in a single go? (Or perhaps do this for me if you can.)

**Comment by PaulKiddle** [comment]
I'm currently deleting the unpublished comments for you.

You can change your general comment settings here:
http://mormyrids.myspecies.info/en/admin/config/content/comments

You can also change comment settings for each content item using the Comment Settings tab at the bottom of the edit page.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Thanks so much, Paul!  When I checked the comment settings it indicated that comments were closed on blog articles which was puzzling unless you changed the setting.

**Comment by PaulKiddle** [comment]
The comment settings on individual articles might still be open - either that or perhaps the settings were changed previously (there didn't seem to be any from the last couple of years).
