### ISSUE TITLE
Difficulties in uploading media

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6228]
- Added by [Ariane Buckenmeyer](http://acoela.myspecies.info/en/user/32003)
- Scratchpad: [The Stylet - ](http://acoela.myspecies.info)

### Description:

ERROR MESSAGE (when attempting to upload files through '[Create Media](http://acoela.myspecies.info/en/node/add/media)' tab: 

An AJAX HTTP error occurred. HTTP Result Code: 503 Debugging information follows. Path: /en/file/progress/100623886 StatusText: Backend fetch failed ResponseText: Technical difficulties.

Technical difficulties. The Natural History Museum Scratchpads servers are currently experiencing a few problems. Please try reloading the page you are attempting to access (this will happen automatically in 15 seconds), or come back later. If there is a major problem, further information regarding this outage should be available on our Twitter feed. If you continue to experience this problem, please contact the Scratchpads Team.

**Comment by PaulKiddle** [comment]
Hi Ariane,

It does appear that despite this error the image is uploaded correctly - can you confirm this?
