### ISSUE TITLE
Cannot uncheck default publishing options on content type forms

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6234]
For example, specimen observation page:

 - Go to Structure -> Content types -> Specimen/Observation -> Edit (or go to /admin/structure/types/manage/specimen-observation)
 - Go to publishing options
 - Un-check a checked checkbox
 - Submit form
 - Change has not been saved

This is preventing the workaround for #6229

**Comment by PaulKiddle** [comment]
I believe this was broken by #4582 / b77f25b

**Comment by PaulKiddle** [comment]
@lukasscharer I've applied this fix to macrostomorpha.info, you should be able to [unset publishing options](http://macrostomorpha.info/admin/structure/types/manage/specimen-observation) now.

Can you try and let me know if everything works?

**Comment by Archilegt** [comment]
@PaulKiddle, I am online. If you apply the fix to [Myriatrix](http://myriatrix.myspecies.info/), I could test it right away.

**Comment by lukasscharer** [comment]
Thanks a lot @PaulKiddle. I just checked this in both the Specimen/Observation and Location content types, it works properly now in both. However, while this is a workaround of my earlier issue #6229, it is not a particularly elegant workaround. I still think that these states should be editable in the import function. And thanks also @Archilegt for the original suggestion of changing the default setting in the content type. Much appreciated.

**Comment by Archilegt** [comment]
@PaulKiddle , you closed this issue and #6229 but:
1) I still have this bug in Myriatrix and cannot uncheck my "Default options" "Published" box. I need help for unchecking that box. I do not want specimens in Myriatrix to be published by default.
2) This tutorial (https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Add-locations-and-specimens#adding-a-specimen) still needs to be updated with the additional fragment that I provided, as is indicated in issue #6229.
Any help/improvement would be greatly appreciated!

**Comment by PaulKiddle** [comment]
Ok, I should have some time to look into this next week - I'll keep you updated
