### ISSUE TITLE
Unable to connect to twitter account

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6249]
- Added by [Ariane Buckenmeyer](http://acoela.myspecies.info/en/user/32003)
- Scratchpad: [The Stylet ](http://acoela.myspecies.info)

### Description:

Error message: "Could not obtain a valid token from the Twitter API. Please review the configuration" prior to adding an account.

**Comment by jrdh** [comment]
This is a duplicate of https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5877
