### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6250]
- Added by [George Beccaloni](http://www.wallaceletters.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Correspondence Project](http://www.wallaceletters.info)

### Description:

I requested a backup of the A. R. Wallace Correspondence Project Scratchpad and none was generated, even after several days of waiting.

**Comment by jrdh** [comment]
Hi George, thanks for reporting this. The backups are still there and are still be created at your request, but strangely they're not showing on the backup scratchpad page. Here's a link to the latest backup that was requested in case you need to download it: http://backup.scratchpads.eu/wallaceletters.info-20200721.174903.tar.gz. I'll be looking into why they're not being shown now but rest assured that the backups are still on the scratchpads servers!

**Comment by jrdh** [comment]
Will be fixed in the next release.
