### ISSUE TITLE
Errors in taxon description

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6256]
- Added by [Chris Lyal](http://weevil.info/user/2)
- Scratchpad: [International Weevil Community Website](http://weevil.info)

### Description:

On the Weevil community Website in the http://weevil.info/alonso-zarazaga-lyal-1999-amended/entiminae#overlay=admin/content/spm view an error message appears. on Any taxon page where a description or other text has been added the description tab delivers a similar error. Checking the Content pages for descriptions it appears that text that was present in the past is now gone.

**Comment by jrdh** [comment]
This has been resolved by updating your site to the latest Scratchpads version (2.9.13).
