### ISSUE TITLE
Can't Edit Taxa

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6265]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

I've just change the name and engine name of the taxonomic tree.

Since then I have not been able to edit taxa.  I click on edit on the taxon in the tree but there are no options for taxon name etc....

**Comment by scratchpads** [comment]
Comment by [Anna](http://icgf.myspecies.info/user/36)

The options in the box on the right (Scientific Name, Usage, Reference, Vernacular Names, Misc and Rank) have all vanished. 

There is only a lot of numbers and an un-editable taxon name.

**Comment by annanc14** [comment]
It's working again. Must have just need some time after I changed the names.
