### ISSUE TITLE
Highlighted areas of map dissapeared

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6269]
Hi,
I had finished a distribution map with highlighted areas here: http://myriatrix.myspecies.info/myriatrix/scolopendra-alternans
I did it some time ago and now I went to check it and the highlighted areas are not there. Did you change something that make the highlighted areas disappear? I am preparing a demonstrative paper on Myriatrix Scratchpad and I am worried with this sort of things happening.

**Comment by PaulKiddle** [comment]
Seems to have been fixed with latest release
