### ISSUE TITLE
Phthiraptera- search engine

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6272]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

When you click onto the LITERATURE Tap, you normally can saerch via author, year, key words etc. But this seems to be broken.  The same has occured previously.

Sam

**Comment by benscott** [comment]
Fixed by reindexing the site.
