### ISSUE TITLE
PHTHIRAPTERA- Literature author link broken

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6273]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi, When one go to CONFIGURATIOn - BIBLIO SETTING and click onto a author, usually this will result in the lsiting of the literature by the author. However, there seems that this link is broken because when this action is taken, the resultant is no Literature found shown.

**Comment by benscott** [comment]
Fixed by reindexing the site.
