### ISSUE TITLE
Distribution map issues

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6276]
- Added by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)
- Scratchpad: [Lonchaeidae Online](http://lonchaeidae.myspecies.info)

### Description:

Is there any chance I could  have a phone chat with one of the developers to discuss some niggling problems I am having with the maps and other things?
contact me at imacgowan9@gmail.com

**Comment by PaulKiddle** [comment]
Hi Iain, apologies we haven't been able to get back to you on this.
I'm about to go on leave but will try to catch up with you in a week when I'm back.
In the mean time it would be helpful for you to give a quick list of the specific problems you're having.

**Comment by scratchpads** [comment]
Comment by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)

Hi 

no problem - enjoy your leave!    I think that overall I may not be making the best of the site due to my lack of knowledge.  I would welcome someone just giving it a look over to see what improvements could be made. More specifically I would like to add all 600 world species to the site but I think there is a shorter way than me putting in each one individually.  I also wonder if the species list could be divided up by biogeographical realm to make it easier for users to find the relevant species amongst the entire family - this would also tie in with the checklists which I am working on I also have a slight problem with some of the maps - for example Lonchaea bukowskii  In edit mode I click on the British Isles which comes up shaded, but then on saving they go back to clear again.  Hope this is not too much!!   thanks  .....  Iain

**Comment by PaulKiddle** [comment]
Thanks for your patience.
You can bulk import species at the using the Import link: http://lonchaeidae.myspecies.info/admin/import

Your options are either:
  - import species from the Catalogue of Life (2014/15 lists)
  - Download a spreadsheet that you can populate with your species data, then re-upload it to import everything in one go

I appreciate parts of Scratchpads are not very user friendly. We're doing our best to support users but unfortunately there are a lot of long standing issues and we have very little developer resource, so we're not able to get round to everything.

**Comment by alycejenni** [comment]
You can find a lot more information on importing and such on our [wiki](https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/import) or the [docs](https://scratchpads.readthedocs.io).
