### ISSUE TITLE
Distribution map not saving

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6278]
When trying to add a new taxon description with a distribution map, the country (e.g. Botswana) gets highlighted but it does not save anything and therefore the map does not appear under the taxon overview tab. Please, fix this problem. Thanks.

**Comment by PaulKiddle** [comment]
I've been able to reproduce this on myriatrix.myspecies.info but not on others - will need some more investigation

**Comment by PaulKiddle** [comment]
I've found the issue and a fix is included in the next release.
If you don't mind waiting until Wednesday for that, I will update your site then - I could do it today but I'm on leave Monday and Tuesday and I don't want to tempt fate lest anything goes wrong without me there to fix it.

**Comment by jrdh** [comment]
Going to assume this has been released given that it was 4 months ago, feel free to reopen if not!
