### ISSUE TITLE
Indexing error for a taxon page

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6280]
There should be an indexing error that prevents me from reaching the taxon page for [_Scolopocryptops melanostomus_](myriatrix.myspecies.info/myriatrix/scolopocryptops-melanostomus) and instead redirects me to the taxon page of [_Scolopocryptops melanostoma_](http://myriatrix.myspecies.info/myriatrix/scolopocryptops-melanostoma). Could you please fix this and/or let me know how can I fix it? Thanks in advance!

**Comment by PaulKiddle** [comment]
Looks like you had set Scolopocryptops melanostomus as an alias in the Scolopocryptops melanostoma URL Redirects section. I've deleted that so it works correctly now.

**Comment by Archilegt** [comment]
@therobyouknow , yes, it did. :-)
The thing is that I cannot fix it for #6399 myself because I don't see anything set in the URL Redirects section of https://myriatrix.myspecies.info/myriatrix/newportia-scolopendrides-mexicana

**Comment by Archilegt** [comment]
This _Scolopocryptops_ issue is solved, so I will close it. The _Newportia_ issue still needs to be solved.
