### ISSUE TITLE
Disable map auto-zoom

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6283]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Is it possible for the distribution map to remain in a set position as opposed to shifting to where the records are located? 

For example, I have set the map so that the UK is in the centre of the window but when I add a species distribution to the map, the map shifts due to the areas added.

Thanks.

**Comment by PaulKiddle** [comment]
This should be fairly straightforward. We'd need to add an extra option to `gm3.admin.inc`, then check the settings object in `gm3.js` before calling `autozoom`.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Thanks, although that means very little to me! Having set the map (using lat/long) so that the U.K. was central, I added all the VC’s where a species is known but depending where these areas are, the map shifts and/or zooms in/out.

**Comment by BarryWarrington** [comment]
Hi, 

Will the map auto zoom issue be resolved soon? Only reason I ask is the site will be going live soon and I’d like this feature to be fixed.

Many thanks,

Barry.
