### ISSUE TITLE
Media licences

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6286]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Some photographs are showing in the media gallery page as having the licence ‘Attribution CC BY’, despite me actually choosing ‘All Rights Reserved’ when uploading the images. When you click on the photos involved, they do show the correct rights.

**Comment by benscott** [comment]
Bug should now be fixed - see #6314
