### ISSUE TITLE
Missing description pages

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6293]
Where have all the tabs gone? When I click on a species, all info is missing!

![9041B266-6FD3-4539-9881-AF8BBC59A2B7](https://user-images.githubusercontent.com/75427252/101015306-20007c00-355f-11eb-9508-6ccf534f03be.png)

**Comment by alycejenni** [comment]
There were a couple of new blank tabs ticked under **Admin > Structure > Taxonomy > Great Britain & Ireland Species > Settings > Species tab display options**. I've unticked them and everything now seems to be back to normal. I have no idea where those came from and they seem to have disappeared now!

Sorry about that, should be fixed now.

**Comment by BarryWarrington** [comment]
That’s great, many thanks for sorting it so quickly!

**Comment by therobyouknow** [comment]
On basis that this has been implemented I'm assuming it has been released so I have removed it from current release sprint because completed/done/closed.  Thank you for all your work on it.
