### ISSUE TITLE
Glossary overlay "Access denied" bug

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6294]
Myriatrix Scratchpad will have a databasing hackathon from Saturday, Dec 5th, 9 AM UTC+02 to Sunday, Dec 6th, 3 AM UTC+02.
I hope that it does not crash with a scheduled maintenance.
Note that the **literature database bug** causing data loss while adding pdfs has not been solved yet. Therefore, all hackathon participants will have to edit the same reference two times. Please, consider fixing that bug soon. It has been reported many times during the past months.
One colleague will be working on the "Morphology" glossary page (http://myriatrix.myspecies.info/nontaxonomy/term/37297).  **There is a bug** in the edit overlay of the glossary. When an edit is made and saved, and the editor clicks on the edited term's "view" link, s/he is redirected to an "Access denied" page. Example: http://myriatrix.myspecies.info/morphology/antenna#overlay-context=nontaxonomy/term/37297

**Comment by alycejenni** [comment]
I'm not aware of any scheduled maintenance work taking place this weekend.

We appreciate that the bibliography bug is annoying, we're aware that it has been reported multiple times, and we apologise that it hasn't been fixed yet (though not for lack of trying). Unfortunately it isn't as simple as "just fix it". Tracking down and fixing bugs can be very difficult and time-consuming, especially in a project as old and complex as Scratchpads (which also does not currently have a full-time dedicated maintainer, and over the past year has suffered from the effects of the pandemic in regards to developer availability).

As for the glossary overlay bug, I'll add that to the queue.

**Comment by alycejenni** [comment]
Clicking on a nontaxonomy node opens `taxonomy/term/x` instead, which is the biological classification and uses the [wrong callback](https://github.com/NaturalHistoryMuseum/scratchpads2/blob/b831972883e873ea41e142b42966d9004627725d/sites/all/modules/custom/scratchpads/scratchpads_species/scratchpads_species.module#L520).

**Comment by therobyouknow** [comment]
On basis that this has been implemented I'm assuming it has been released so I have removed it from current release sprint because completed/done/closed.  Thank you for all your work on it.
