### ISSUE TITLE
Articles page only not showing all Biblio entries

### ISSUE THREAD

**Issue by Bramble18** [NaturalHistoryMuseum/scratchpads2#6302]
On our site (www.e-m-b.org) we have an 'Articles' page, which directly links to the Biblio. In the Biblio, as accessed via Content in the Administrator's menu, there are hundred's of papers listed, all published.

Under the 'Articles' page however the Biblio search box only shows the latest publication, and no combination of field changes registered anymore than '1' paper.

This is a new issue. It wasn't long ago that this search function showed all the papers correctly.

Many thanks

**Comment by Bramble18** [comment]
This issue is still ongoing. Please could I have some help with this? Thanks

**Comment by benscott** [comment]
This should now be fixed - how's that looking for you now?

**Comment by Bramble18** [comment]
> This should now be fixed - how's that looking for you now?

Thanks very much Ben - all fixed
