### ISSUE TITLE
All the literature and the media gallery data are missing on their tabs

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6304]
- Added by [yves BRAET](http://doryctinaekey.myspecies.info/user/2)
- Scratchpad: [Key to the genera of Doryctinae of the world](http://doryctinaekey.myspecies.info)

### Description:

Dear all,
First, I wish you a Happy New Year 2021!!

I am connected since a long time to my website (http://doryctinaekey.myspecies.info) and I see that the Tabs Literature and Media Gallery doesn't show any data now (There are no facets available to filter on).
Please could you fix this issue as they are two tabs very usefull for the users??

Thank you for your help!!
Yves BRAET

**Comment by scratchpads** [comment]
Comment by [yves BRAET](http://doryctinaekey.myspecies.info/user/2)

Edit: When I add or modify an existing content (like adding a word in a title of the bibliography reference) it appear in the corresponding tab.

**Comment by benscott** [comment]
Hi Yves, this should now be working again.
