### ISSUE TITLE
Character projects?

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6305]
- Added by [Nicholas Gardner](http://anseriformes.myspecies.info/user/2)
- Scratchpad: [Waterfowl evolution](http://anseriformes.myspecies.info)

### Description:

When are character projects coming back? Part of why I signed up and was interested in Scratchpads was for the ability to organize/manage character matrices and character projects.

**Comment by Archilegt** [comment]
+1. I also need character projects back.

**Comment by benscott** [comment]
Sorry, the character projects were retired quite some time ago and we have no plans to reinstate them.

**Comment by Archilegt** [comment]
Scott, then please at least point us to the relevant code and tutorials. Or make a package with those, because I believe that the tutorials were wiped off of the web. The idea behind using Drupal for Scratchpads was that it could be developed by the community. So, even if the NHM Informatics Team has no plans to reinstate the character projects, we (the community) could make good use of the existing code and previous tutorials.

**Comment by benscott** [comment]
That'd be wonderful if you'd like to get involved to get this module back up and working. We're always very pleased to receive any community contributions. 

The code is available in the main repository - https://github.com/NaturalHistoryMuseum/scratchpads2/tree/master/sites/all/modules/custom/character_editor. I'll try and dig out the old docs for it as they weren't ported to our new system, and if you have any questions I'll try to answer them here.

**Comment by Archilegt** [comment]
Relevant for re-enabling and maybe improving the character projects:
Thessen et al. 2020. Transforming the study of organisms: Phenomic data models and knowledge bases. PLOS Computational Biology. https://doi.org/10.1371/journal.pcbi.1008376

I am still interested in receiving the old docs with the tutorials for the character matrix projects and, if possible, relevant notes on how the module was designed. Note also that issue "Character editor project cannot be enabled" #6067 remains open and that some investigation progress was made by @PaulKiddle there.
