### ISSUE TITLE
Unable to edit older pages

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6309]
- Added by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)
- Scratchpad: [Mormyridae - African weakly electric fishes](http://mormyrids.myspecies.info)

### Description:

Older pages on my Scratchpad can't be edited.  When you open the Edit tab, the text box is empty.  If you type something into this text box and save, it is appended to the original content. More recently created pages are editable.

http://mormyrids.myspecies.info/en/node/447#
http://mormyrids.myspecies.info/en/node/455#

**Comment by benscott** [comment]
This should now be fixed.
