### ISSUE TITLE
WoRMS web service down

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#6310]
**Describe the bug**
WoRMS web service not working.

**To Reproduce**
Reported via email on http://myriatrix.myspecies.info/

**Your setup:**
 - http://myriatrix.myspecies.info/

**Comment by Archilegt** [comment]
Many thanks! :D

**Comment by Archilegt** [comment]
@benscott, the WoRMS importer is not yet working. I tested it and I got:
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Service unavailable (with message)
ResponseText: 

And there was no response text, so I cannot tell you more.
The issue needs to be reopened.
