### ISSUE TITLE
The best and easiest way to create determination keys for e.g. insects in scratchpads?

### ISSUE THREAD

**Issue by Morjens123** [NaturalHistoryMuseum/scratchpads2#6311]
It would be pretty cool scratchpads had some kind of easy and quick feature or tool to make identifcation keys for insects. A few years ago we made on our page this "test" key:  http://pistiaistyoryhma.myspecies.info/node/575# 

So using basic page editing / html to make determination keys is possible, but it feels like too much work. Perhaps this is something you are working on or perhaps your feel "page editing / basic html" is "good enough"

**Comment by PaulKiddle** [comment]
This sounds like a fairly complex feature to implement. At the moment we are mainly focusing on bugs and small features, so it's unlikely we'll be able to do this at any point in the near future.

**Comment by Archilegt** [comment]
@Morjens123, just adding that in Scratchpads it is possible to add Lucid keys. 
See the Antkey Scratchpad: http://antkey.org/en/content/key
And the tutorial: https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Lucid-keys
