### ISSUE TITLE
Species pages empty of content

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6312]
- Added by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)
- Scratchpad: [Mormyridae - African weakly electric fishes](http://mormyrids.myspecies.info)

### Description:

No text or images are appearing on my species pages, e.g.: http://mormyrids.myspecies.info/en/taxonomy/term/283

This appears to have been introduced after requested fix for my previous problem, #6309.

**Comment by benscott** [comment]
Fixed by resetting the taxonomy display tabs. Bug introduced by 2.9.14?, will track on issue #6313.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Thank you, Ben!
