### ISSUE TITLE
no tabs in taxonomic term view

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6313]
- Added by [Ilia Gjonov](http://www.bg-cicadidae.myspecies.info/user/2)
- Scratchpad: [The Bulgarian Cicadidae](http://www.bg-cicadidae.myspecies.info)

### Description:

Most of the tabs in taxonomy term view disappeared. The tabs "Map", "References" etc. are missing. It is only one empty tab, "Revision" and "Statistics".

**Comment by benscott** [comment]
Fixed by resetting the taxonomy display tabs. Need to investigate why this bug occurred, potentially introduced by releaase 2.9.14?

**Comment by PaulKiddle** [comment]
fixed by #6350
