### ISSUE TITLE
Media licences 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6314]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

See issue #6286.

I intend the site to go live in a few weeks and I need the correct images licences to be shown. 

Any idea when this problem will be sorted?

Many thanks.

**Comment by benscott** [comment]
This should now be fixed - how's that looking for you now?

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

It sorted most of the images but I have just added another photo (all rights reserved) yet the side bar is showing it as ‘Attribution CC BY’. When you click on the photo, it correctly shows ‘All rights reserved’.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

The above image has now reverted to the correct licence. Thanks for sorting it out.
