### ISSUE TITLE
Page washed out

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6315]
- Added by [Barry Warrington](http://www.agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://www.agromyzidae.myspecies.info)

### Description:

The page for 'Host plant genera A-Z' is a completely different colour for some reason, appearing washed out.

Please can you advise how to sort this?

Many thanks.

**Comment by BarryWarrington** [comment]
The same also applies to the 'newsletter' page.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Now resolved.
