### ISSUE TITLE
Disable map auto zoom

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6316]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Hi, 

re query #6283 - it was mentioned that this should be easy to fix but the maps are still zooming.

Any idea when this will be resolved?

Many thanks.

**Comment by BarryWarrington** [comment]
Hi,

I am hoping to go 'live' with my site but the auto-zooming maps are kind of spoiling it as the maps are inconsistent with their placement and level of zoom. 

It would be really appreciated if this apparent 'easy fix' could be implemented whenever possible.

Thanks.

**Comment by benscott** [comment]
Fixed in #6325
