### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6317]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

Hi, 

I have put my site out of maintenance mode but other people are still getting the 'site under maitenance' message when they try to access the site.

How long does it take for the site to go 'live'?

Thanks.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

It takes an hour each time the site comes out of maintenance mode - is that standard?

**Comment by benscott** [comment]
It is, we need to be quite aggressive with the caching to keep the number of Scratchpads up.
