### ISSUE TITLE
URGENT - TAXONOMIC TREE MISSING

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6319]
Hi, 

The taxonomic tree is missing from the relevant page - see attached screenshot.

![screen](https://user-images.githubusercontent.com/75427252/106573914-2779dc80-6532-11eb-9585-ca75eafc7be2.jpg)

If I go to 'structure', 'taxonomy', 'edit terms' for my vocabulary, all the family/subfamily/genera/species are all there.

Also, if I click on one of the hyperlinks in the site, it takes me to a species page in which the taxonomic tree is present;

![screen2](https://user-images.githubusercontent.com/75427252/106574168-7a539400-6532-11eb-956c-8242162a3d8f.jpg)

Please help!

Thanks,

Barry.

**Comment by BarryWarrington** [comment]
Before the above happened, within my vocabulary list was an empty box with seemingly nothing associated with it - see below. I deleted this which must have caused the above issue.

![83E7E0CB-A991-4508-BFD2-161ADE602E5A](https://user-images.githubusercontent.com/75427252/106587297-59466f80-6541-11eb-9487-cd9d85955ad0.jpeg)

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Now fixed, many thanks Ben!!
