### ISSUE TITLE
Remove hyperlink

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6320]
See attached screenshot. I copied and pasted the URL into the page but it has created a hyperlink which I am unable to remove. When I go to edit the page, the URL text does not have a hyperlink associated with it so I can not choose 'unlink'.

Is there anyway I can remove the hyperlink?

Thanks,

Barry.

![Untitled](https://user-images.githubusercontent.com/75427252/106873305-3ac0af80-66cc-11eb-8594-b4194ed7faaa.jpg)

**Comment by Archilegt** [comment]
@BarryWarrington, this sort of manual work shouldn't be necessary. There is a "Cite me" black tab at the upper right corner of the taxon pages. It was working for a while, but it has not being working for a long time. Apart from not generating the correct citation, it is also failing to recognize when an editor is logged in, and displaying the message "Please note that you are currently logged in. The snapshot will use the anonymous version of the page."
Hopefully this will get fixed soon!

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Ah, ok. I'll keep my manual text on the site until the issue you mention has been resolved.

Thanks,

Barry.
