### ISSUE TITLE
Mystery letters

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6321]
Please see attached screenshot - what do the letters refer to indicated by the arrow? Can these be removed?

Many thanks,

Barry.

![Untitled](https://user-images.githubusercontent.com/75427252/106904117-ae75b300-66f2-11eb-8a9f-388b21372383.jpg)

**Comment by Archilegt** [comment]
@BarryWarrington, it may mean that you or someone else inadvertently added a space after AGROMIZIDAE in the field Unit Name 1. See more about "Non-breaking Space" at https://www.w3schools.com/html/html_entities.asp

**Comment by BarryWarrington** [comment]
Thanks for the link. Having read the info, it doesn’t tell me how to correct it - any thoughts?

Thanks.

**Comment by Archilegt** [comment]
Hi, Barry. Please, try opening your classification editor and see if there is a blank space after the name AGROMIZIDAE. If so, please delete the space.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

No blank space. Any other suggestions?

Thanks!

**Comment by Archilegt** [comment]
1) The space could also be on the "Author" field, or 
2) the mystery letters could have appeared because that field is completely empty. If so, I would recommend changing "AGROMIZIDAE" to "Agromizidae" and then adding the author and year of the family name. I do not know the author, but I guess you do.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

All sorted, all I had to do was enter the author - pretty simple! Sorry for wasting your time.

Thanks,

Barry.

**Comment by Archilegt** [comment]
No waste at all! I am a Scratchpads user and I am happy to help other users if I have the time! :-)
Kind regards,
Carlos

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Many thanks Carlos!
