### ISSUE TITLE
Log in failing

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6322]
I forgot the password to log on to the site. I went through the process of getting a new password but each time I click on the one time link, I either reach a screen that says access denied or, I can enter a new password in my account but then it says there has been more than 5 failed attempts for this account and it is temporarily blocked.

Please can I be informed how to regain access!

Thanks.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Issue now resolved.
