### ISSUE TITLE
Apostrophe producing mixed letters

### ISSUE THREAD

**Issue by BarryWarrington** [NaturalHistoryMuseum/scratchpads2#6323]
When entering the creator name to a media (photograph) file, if an apostrophe is needed, it creates a mix of letters in the creator list. See attached, for Aideen O’Doherty;

![CB20A516-974B-4E6E-97D9-172DEA0CC3C6](https://user-images.githubusercontent.com/75427252/107149943-4a9df500-6953-11eb-98bd-1641d357abb9.jpeg)

How can I resolve this issue?

Thanks.

**Comment by jrdh** [comment]
Will be fixed in the next release.
