### ISSUE TITLE
My pages are loading very, very slowly...

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6334]
- Added by [George Beccaloni](http://wallacefund.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Website](http://wallacefund.info)

### Description:

My Wallace Correspondence Project and Memorial Fund Scratchpads are loading so slowly they are not usable..

**Comment by jrdh** [comment]
Seems to be going ok at the moment - this could perhaps have been caused by the 2.9.15 release.
