### ISSUE TITLE
Stats and Statistics taxon tabs functionality partially lost

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6335]
**Describe the bug**
Stats and Statistics taxon tabs functionality are partially lost. When those tabs are used, the taxonomic tree on the left panel never finishes loading, staying with the "rotating point". Additionally, the useful summary graph with number of children taxa (= descendants statistics) is completely gone.

**To Reproduce**
See examples for Scolopendromorpha:
Tab Stats: http://myriatrix.myspecies.info/taxonomy/term/8814/stats
Tab Statistics: http://myriatrix.myspecies.info/taxonomy/term/8814/statistics

**Comment by jrdh** [comment]
Fix will be released in the next release.
