### ISSUE TITLE
Alkcarb - location tab occurrences non-functional

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6340]
- Added by [Emma_HW](http://alkcarb.myrocks.info/user/5)
- Scratchpad: [Alkaline Rocks and Carbonatites of the World](http://alkcarb.myrocks.info)

### Description:

Hi 
There seems to be a problem with access entries page when going through the location tab. It comes up with access denied error. All other forms (map and occurrence list) of accessing the data are working OK. Thanks Emma

**Comment by alycejenni** [comment]
Same as #6177 again; fixed temporarily
