### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#6341]
Hello, 

Our site is not working at all this morning. Is it a general Scratchpads problem?

Thanks........

[http://icgf.myspecies.info]

**Comment by Archilegt** [comment]
It's a general problem. My site is not reachable since last night.

**Comment by annanc14** [comment]
> It's a general problem. My site is not reachable since last night.

Okay...... thank you...

**Comment by Archilegt** [comment]
@benscott , @PaulKiddle , the Scratchpads sites are intermittently online, for three days now. Right now they are offline. Is there something happening on your side?

**Comment by benscott** [comment]
Our apologies, the sites are up but it appears some users have been blocked in our new firewall rules. Please could you email your IPs to scratchpads@nhm.ac.uk and we'll investigate further.
