### ISSUE TITLE
Map icons

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#6342]
**Describe the bug**

Zoomed in map icons are misisng

**To Reproduce**

1. Go to the map
2. Zoom in
3. See the missing map icons

**Screenshots**

<img width="478" alt="image" src="https://user-images.githubusercontent.com/81690/111766449-76d75a80-889d-11eb-9d0c-a1abc45ef9ce.png">

**Your setup:**
 - Scratchpad URL: http://alkcarb.myrocks.info/map
 - Browser: Chrome

**Comment by scratchpads** [comment]
Comment by [Emma_HW](http://alkcarb.myrocks.info/user/5)

I'm also getting the same issue on Safari from a mac. Thanks, Emma

**Comment by jrdh** [comment]
Strangely, this works fine for me which makes me think it's a caching issue? @benscott which file is listed as 404ing? Is it http://alkcarb.myrocks.info/sites/all/modules/custom/gm3/images/marker/blue.png ?

**Comment by PaulKiddle** [comment]
Also working for me, I agree it's probably a cache issue

**Comment by remmerose** [comment]
Hi All, 
I've just checked today - was getting the same issue. Cleared the cache, but still did not fix the problem. Using chrome on Dell NHM laptop. 
Thanks Emma 
![alkcarb-06052021](https://user-images.githubusercontent.com/83774422/117322054-90e8ee80-ae85-11eb-904d-7c60687a0fa0.PNG)

**Comment by PaulKiddle** [comment]
Hi @remmerose ,

When you follow this link, do you get an image or an error page?
http://alkcarb.myrocks.info/sites/all/modules/custom/gm3/images/marker/blue.png

**Comment by remmerose** [comment]
Hi Paul, Sorry for the delay - i get the image.

Emma

**Comment by remmerose** [comment]
And the map icons are still missing for me today too.

Thanks!

**Comment by PaulKiddle** [comment]
I've had confirmation the icons are fine now
