### ISSUE TITLE
Alkcarb - Location - Format of Occurrence Order

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6344]
- Added by [C-Rooks](http://alkcarb.myrocks.info/user/314)
- Scratchpad: [Alkaline Rocks and Carbonatites of the World](http://alkcarb.myrocks.info)

### Description:

At present the occurrences are listed in order of date added. It would be best if this could be changed to display them in sequential order by Continent > Country > Occurrence Number

Thanks,

Curtis

**Comment by alycejenni** [comment]
I've modified your occurrences view so they're now grouped by continent then sorted by country > occurrence number.
You can modify these settings yourself in `Structure` > `Views` > `Scratchpads Occurrences page` > `Edit`.

**Comment by Archilegt** [comment]
Hi @alycejenni,
Is the path "Structure > Views > Scratchpads Occurrences page > Edit" exclusive to the Alkcarb Scratchpad? I do not have a "Scratchpads occurrence page" in Myriatrix, the closest being "Scratchpads specimen observation page".

**Comment by alycejenni** [comment]
@Archilegt yes, it depends on what your views are called.
