### ISSUE TITLE
Taxon pages not showing properly

### ISSUE THREAD

**Issue by annanc14** [NaturalHistoryMuseum/scratchpads2#6349]
Hello,

This morning the taxon pages are not showing properly. The usual tabs are missing and the taxonomic information is also missing. 

Thanks....
![Untitled](https://user-images.githubusercontent.com/44700406/113095101-90609680-91fb-11eb-8768-eee9e66f166c.jpg)

**Comment by PaulKiddle** [comment]
Hi Anna,
I've tracked the problem down and put in a fix in for your site - can you check that the species pages are displaying as they should now?

**Comment by annanc14** [comment]
That's great! Thanks very much....

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

The same has happened to my site!

Please can this be fixed on mine too?

**Comment by PaulKiddle** [comment]
The fix has now been applied to all sites
