### ISSUE TITLE
Taxon pages not showing correct tabs

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6352]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

On my species pages, only a 'revisions' tab is showing.

Please can this be resolved?

Thanks.

**Comment by PaulKiddle** [comment]
Hi Barry, I've made the fix and applied it to your site - should be working correctly now.

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Thanks, much appreciated.
