### ISSUE TITLE
Timing out

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6354]
- Added by [Paul Cannon](http://fungi.myspecies.info/user/2)
- Scratchpad: [Fungi of Great Britain and Ireland](http://fungi.myspecies.info)

### Description:

Thank you for fixing the tabs on http://fungi.myspecies.info, glad it was a simple matter. However, I'm getting timeouts about two in every three edits I attempt (sometimes with an AJAX error, sometimes not), which is making the site almost unusable. Is this something that will get sorted soon? I don't think there is a problem at my end.
Best wishes
Paul

**Comment by PaulKiddle** [comment]
Hi Paul, apologies for the silence on this issue. I believe we've sorted out the performance problems now - I've checked your site and it's working fine for me - but if you're still experiencing issues you can re-open this issue and we'll have another look.
