### ISSUE TITLE
Overwrite Citekey values with literature NID values

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6359]
This is not exactly a bug, but finishing a previous bug fix. 
While citing literature via [bib]NID[/bib], problems were noted. It turned out that what was actually meant to be cited were "citekey" values but that citekeys were (are?) maintained as sets of values different from the literature NID values. In Myriatrix, this was solved by making the Citekey field visible and editable. Now it is possible to manually enter the NID value into the citekey field. However, it would be quite a bit of work to manually go over each of ca. 1000 references and check if the citekey matches the NID.
Suggestion: Please, overwrite all citekey values with the NID values in Myriatrix (http://myriatrix.myspecies.info/biblio).

**Comment by alycejenni** [comment]
Done. There were 280 records where the citekey didn't match the NID - I've saved all the previous values in case they're needed or if there's a problem!
