### ISSUE TITLE
Classification tree unresponsive

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6361]
- Added by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)
- Scratchpad: [Mormyridae - African weakly electric fishes](http://mormyrids.myspecies.info)

### Description:

Nodes of my sites' classification not responding to clicks shortly after page is opened.  Works after a couple minutes. Has been like this for the past few days.
http://mormyrids.myspecies.info/

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Addendum.  Upon further study, it seems the classification tree is acting differently than before. The problem does not resolve after a certain amount of time as I stated. One has to click on the name to the right of the node square before the node becomes responsive to clicks. Earlier this was not the case.

**Comment by alycejenni** [comment]
Hi John,
I'm afraid I can't recreate this. Is it all nodes on the tree that aren't responding, or just some of them?

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Upon clicking my Scratchpad's 'Mormyridae' tab, you're given a classification with three names visible, Mormyridae and beneath it Mormyrinae and Petrocephalinae. What's changed is that clicking any of the node squares now does *nothing*: the nodes do not open.  You must first click on one of the names for clicking on the node squares to do anything.  It was not so until very recently and this is clearly not the desired functionality. I just checked another Scratchpad and this is true on it, also, so looks to be a system-wide change that has happened. Due to some update? Please change the behavior of the clickable classifications to what it was.

**Comment by alycejenni** [comment]
Not sure what's causing it, but I can recreate now: at the very top level (i.e. [Mormyridae](http://mormyrids.myspecies.info/en/taxonomy/term/430)), the expand/collapse toggles don't work on any of the tree items. This _only_ seems to be a problem at the very top level - on other pages (e.g. [Petrocephalinae](http://mormyrids.myspecies.info/en/taxonomy/term/431)) everything seems to work fine.

We have released an update recently but obviously this was not an intended effect!

**Comment by alycejenni** [comment]
The caches needed to be cleared. Can you confirm if this is working for you as well now?
