### ISSUE TITLE
Literature reference display duplicated

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6376]
**Describe the bug**
On this user Publications page (http://myriatrix.myspecies.info/user/56/biblio), under year 2020, the literature reference starting with "M. Karam-Gemael" is displayed two times. The reference does not seem to be duplicated in the literature database (http://myriatrix.myspecies.info/content/conservation-terrestrial-invertebrates-review-iucn-and-regional-red-lists-myriapoda).
Could that page be "reindexed" to eliminate the duplicate? Apologies if "reindexed" is not the correct term.

**Comment by alycejenni** [comment]
For some reason everyone in this reference has been cited twice:

![image](https://user-images.githubusercontent.com/23579762/121514705-3858c400-c9e4-11eb-90f0-b43b38b7f250.png)
![image](https://user-images.githubusercontent.com/23579762/121514878-6a6a2600-c9e4-11eb-97a3-e6be37453428.png)

I've removed the extra names and that seems to have fixed it.

**Comment by Archilegt** [comment]
Hi, @alycejenni,
Many thanks for checking this issue and finding the problem. As per your findings, this is related to the bug caused by the literature module not being able to parse different DOIs and creating several name sets, one per each concatenated DOI. Other literature references from Myriatrix and/or other Scratchpads may present the same issue, but now we know how to solve it.
This issue is now probably solved for newly created references by: Upgrade biblio and change crossref importer to json api #6356, which solves #6147, #6299, #6124
Thanks again!
