### ISSUE TITLE
AlkCarb.com - Embedded Twitter Feed

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6378]
- Added by [C-Rooks](http://alkcarb.myrocks.info/user/314)
- Scratchpad: [Alkaline Rocks and Carbonatites of the World](http://alkcarb.myrocks.info)

### Description:

We need to embed a twitter feed onto the homepage of the site linked to @alkcarb. I can provide account details if needed to set up.

Thanks,
Curtis

**Comment by PaulKiddle** [comment]
Blocked by #5877

**Comment by PaulKiddle** [comment]
Have created the twitter feed block, just need to add it to the front page

Need to modify scratchpads_front to invoke a hook when generating block options (scratchpads_front_blocks_as_options)

Need to add hook implementation to alkcarb module to return `[module, delta]`

```pseudocode
blocks = invoke_all(scratchpads_front_blocks)
for(blocks as [module, delta[) {
  block = block_load(module, delta)
  block_info[block->bid]=block
}
```

**Comment by PaulKiddle** [comment]
Configuration should be correct now but for some reason the external javascript isn't loading.
Possibly to do with the `scratchpads_front` module, I can't quite follow the code. I'll try again after I'm back from leave.

**Comment by remmerose** [comment]
Thanks Paul - good to hear that it is almost there!

**Comment by remmerose** [comment]
Meant to say in our call today @PaulKiddle this looks great and seems to be fully functional now, so issue can be closed! Thanks very much!
