### ISSUE TITLE
Alkcarb: Access denied on taxonomy tree links

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6379]
Location taxonomy links are access denied: http://alkcarb.myrocks.info/taxonomy/term/19

"Nontaxonomy" works http://alkcarb.myrocks.info/nontaxonomy/term/19

**Comment by PaulKiddle** [comment]
Merged PR to master and migrated alkcarb to master

**Comment by remmerose** [comment]
Hi Paul this looks to have solved the problem - thanks very much. I've noticed that the same issue is appearing on the occurrences page - I'll open a new request though.
Emma
