### ISSUE TITLE
Scratchpad Blocked

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6383]
- Added by [Darwyn Sumner](http://www.micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://www.micropezids.myspecies.info)

### Description:

I'm blocked from access to my Scratchpad by the message:
17aaf0c1d3e-d7ed5e80
82.0.41.18
This is a matter of some urgency
Please respond

**Comment by benscott** [comment]
As per our emails, the site is no longer blocked.
