### ISSUE TITLE
Blocked for days, again

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6384]
I have been blocked for a few days already, again. I have not been able to add new literature to Myriatrix literature database. Adding keywords to the keyword field seems to trigger an AJAX error, but the main problem is that when I try to save the literature, I get a "blocked" message. Please, solving this is a matter of some urgency. Concurrently, a Myriatrix user from Dominican Republic also asked "Is Myriatrix working or is it a problem with my computer?", which I assume relates to this user being unable to log in and/or add literature to the database.

-------------------------------------
Error message:

You have been blocked
You are unable to access this website

Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered this service. There are several actions that could result in being blocked including submitting a certain word or phrase, a SQL command or malformed data.
How can I resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page occurred and the event ID found at the bottom of the page.

17abdf41afe-14f7b185
86.50.94.181

**Comment by Archilegt** [comment]
This problem is apparently caused by the service provider "Barracuda Networks, Inc."

**Comment by benscott** [comment]
Hi @Archilegt - apologies for these access denied errors. As you know, we've been moving the Scratchpads behind the Museum firewall, and it took a little time to get the settings right but we should't be blocking any more users now. We have a custom "You have been blocked..." page in place now, asking people who see it to email us, so should this happen again we'll pick it up and respond quickly.

**Comment by Archilegt** [comment]
Hi, @benscott !
It should be okay to close this issue, as it has been solved in general lines (e.g., cache rebuilt) as mentioned elsewhere in our exchanges. Thank you for taking care of this! :)
