### ISSUE TITLE
Creating a new site sends the wrong login link to the user

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6385]
I've just tried creating a new test site using `http://get.scratchpads.org/node/add/site`
Upon clicking the login link in the email I'm told the link has expired.
I was also sent the "An upgrade to Drupal is available" email, which site maintainers should not normally receive.
This is probably because we're no longer using the hosting_scratchpads form.

This is blocking creation of the following scratchpads that have been requested on the mailing list:
 - Amazonian Melastomes
 - Ophioninae
 - Ichneumonidae

**Comment by benscott** [comment]
Sites should be be created with the old signup form & then everything works.

**Comment by benscott** [comment]
Also, the requestees for the three sites above have all been sent the new site form.
