### ISSUE TITLE
Page load speed

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6386]
Some page requests seem to be loading very slowly, or not at all. There doesn't seem to be a consistent pattern - needs investigation.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](http://mormyrids.myspecies.info/en/user/175)

Scratchpads have been slower than molasses and unusable for days!

**Comment by benscott** [comment]
The performance issues should now be resolved
