### ISSUE TITLE
Account deletion is painfully slow

### ISSUE THREAD

**Issue by PaulKiddle** [NaturalHistoryMuseum/scratchpads2#6389]
Account deletion is slow or times out, making it hard for maintainers to delete spam accounts.

Affected sites include:

- https://cate-araceae.myspecies.info/
- https://ubsc.myspecies.info/
- https://cate-araceae.myspecies.info/
- https://bionoset.myspecies.info/

**Comment by benscott** [comment]
This was caused by the firewall performance issues and is now fixed.
