### ISSUE TITLE
unable to load taxonomic names / authors  etc

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6391]
- Added by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)
- Scratchpad: [Lonchaeidae Online](http://lonchaeidae.myspecies.info)

### Description:

Lonchaeidae online:  When I try to put in a taxonomic name or author - a message says "request terminated abnormally"

**Comment by benscott** [comment]
Just released a fix & this should be working again.
