### ISSUE TITLE
problems adding pictures

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6393]
- Added by [Maria Zabaleta](http://rocosos.myspecies.info/user/2)
- Scratchpad: [Puntas Rocosas del Uruguay](http://rocosos.myspecies.info)

### Description:

this message appears when I try to add pictures 
The specified file temporary://p1fbsqhh4t1f32fo01ar3pe2m934.tmp could not be copied, because no file by that name exists. Please check that you supplied the correct filename.

**Comment by benscott** [comment]
Hi Maria, apolgoes we've been experiencing some technical problems on the server but this should now be working again.
