### ISSUE TITLE
grid editor

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6394]
- Added by [Gjonova](http://formicidae-bg.myspecies.info/user/2)
- Scratchpad: [The Ants of Bulgaria](http://formicidae-bg.myspecies.info)

### Description:

Hello,
could you fix the problem with grid editor - it does not work in Localities and Specimens.
Thank you!

**Comment by benscott** [comment]
That should be working for you now

**Comment by scratchpads** [comment]
Comment by [Gjonova](https://formicidae-bg.myspecies.info/user/2)

Thank you!
