### ISSUE TITLE
Scratchpads page loads extremely slow, no communication

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6395]
My Scratchpad <http://mormyrids.myspecies.info/> and others have been unusably slow for days.  This has been reported below. Others like <http://antkey.org/> are speedy.  What gives?  The fact that there is no communication with Scratchpad admins is really inexcusable.

**Comment by Quote2106** [comment]
Just to add on this point and stay in the loop, I landed on this page to report the same issues for the scrachtpads https://bopco.myspecies.info/ & https://jemu.myspecies.info/.

The former, for which I am the owner gives the following when logging in 
![block](https://user-images.githubusercontent.com/47144980/127975948-facee6d3-5d36-4151-9682-977358c84189.png)
g)

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](https://agromyzidae.myspecies.info/user/2)

I agree. My site has been so slow or not working at all. I'm unable to add content which is extremely frustrating. It would be good if these issues can be looked at and addressed with some urgency.

**Comment by benscott** [comment]
Our apologies for the ongoing slowness of Scratchpads. We believed this bug to be fixed but it keeps reoccurring - I'm looking into it now.

**Comment by benscott** [comment]
I have just rolled out a fix for the Scratchpad performance - the sites appear to be much faster for me, but let me know if you're still experiencing any issues. 

@Quote2106 - are you still finding yourself blocked from accessing those Scratchpads?  That's a different problem, still related to the new firewall if it's being overzealous blocking real users.

**Comment by scratchpads** [comment]
Comment by [John P. Sullivan](https://mormyrids.myspecies.info/en/user/175)

Hi Ben. Thanks for your attention to this matter. Speed seems to be better, however my clickable classification is not working, i.e. clicking on collapsed node does not open it.  See https://mormyrids.myspecies.info/en/taxonomy/term/430

**Comment by benscott** [comment]
Glad the speed is improved & I've released a fix for the clickable classification. How's that working for you now?

**Comment by jpsullivan65** [comment]
Just an update on speed: Today (Aug-14) everything is nice & snappy.  Quite a change from where we were from the past few weeks!  Thanks.  My one request for the future would be to have a mechanism to inform active Scratchpad admins about interruptions to service or future slowdowns so we aren't left wondering if you guys have turned off the lights and gone home.  Any way to post such notifications here on GitHub?

**Comment by Archilegt** [comment]
Hi, @benscott 
The clickable classification seems unresponsive in Myriatrix as well. Could you please check if your fixes have been implemented in Myriatrix?

**Comment by jrdh** [comment]
Hi @Archilegt - just cleared the cache and that has fixed it. We had some issues with configuration after switching to HTTPS and this was a direct result of that. In the `tinytax` module that controls the tree we are comparing the URL of the plus/minus image in the tree with a stored URL and these were mismatched due to one using `http://` and one using `https://` (https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/sites/all/modules/custom/tinytax/js/tinytax.js#L35). Clearing the cache updated the `http://` one to `https://` and that's it solved.

**Comment by Archilegt** [comment]
Super! Many thanks, Josh!

**Comment by benscott** [comment]
Great, thanks @jpsullivan65, glad it's all working properly again!  Yep, apologies for the lack of communication around this, posting system notifications here would be really useful, both to help inform you and for us to better to track impacted sites.  I've created a new issue label 'system-status', and from now on we'll be posting any critical system alerts here.

**Comment by Archilegt** [comment]
@benscott , you are also welcome to post system notifications on the FB group "Scratchpads Users" (https://www.facebook.com/groups/665993564280327). Alerts on foreseen disruptions (e.g., moving behind a firewall, migrating to https) would be especially welcome. Some of us use Scratchpads actively, not only for research, but also for training colleagues and students. If we plan a training and then Scratchpads is not working, that is a major issue for us.
I also wanted to say that the corona situation has greatly disrupted both fieldwork and research trips to museums. Scratchpads is one important avenue, at least for me, for ameliorating the disastrous impact of corona on my research schedule of the past and present year. I already used Myriatrix as a biodiversity informatics recording tool in a paper. This cycle of being IP-blocked, not being able to edit, etc., etc., is making really hard to advance in other projects. Currently, I am unable to finish adding Myriapoda 2020 literature, and I have a deadline to meet in September. I cannot express how important it is that at least the literature module and the taxonomic editor start working again.

**Comment by benscott** [comment]
Thanks @Archilegt, I was not aware of that Facebook group but we'll post alerts on future disruptions there too!  With the firewall move now stable we don't anticipate any further downtime - and we're also hiring another developer to help on the project so we'll be able to respond quicker to any problems in the future.

Is #6398 the literature bug?

**Comment by Archilegt** [comment]
@benscott , yes, that is the bug that I am getting now. It is still happening today.
