### ISSUE TITLE
External access

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6402]
- Added by [Ralph Harbach](http://mosquito-taxonomic-inventory.info/user/2)
- Scratchpad: [Mosquito Taxonomic Inventory](http://mosquito-taxonomic-inventory.info)

### Description:

A colleague at the Smithson was denied access to the Anatomical Glossary (main menu item) of the Mosquito Taxonomic Inventory. I hope uses are not denied access to other menu items.

**Comment by benscott** [comment]
Hi Ralph, apologies to you and your colleague. We've just moved the Scratchpads behind the Museum firewall, and it took a little time to get the settings right but we should't be blocking any more users.  We have a custom "You have been blocked..." page in place now, asking people who see it to email us, so should this happen to anyone else we'll pick it up and respond quickly.
