### ISSUE TITLE
Lice tap classification tree does not work

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6403]
- Added by [Yokb](http://phthiraptera.info/user/29)
- Scratchpad: [Phthiraptera.info](http://phthiraptera.info)

### Description:

Hi,

When click onto the lice tap, it only opens to the order 'Phthiraptera' page. It would not allow further extention of the order so one would not be able to look at the other levels.

**Comment by benscott** [comment]
Fixed - #6404
