### ISSUE TITLE
Add Services module to provide scratchpad API for machine access to scratchpad public data already on the public site

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6426]
**Overview**
[Services](https://www.drupal.org/project/services) is the definitive module to provide API endpoints.
We can use this to provide an upwards API for use by an aggregator/linked-open-data platform we are planning at NHM: Scratchpads Explorer/Portal/Window

**Possible Solutions**
Drupal Services contrib module

**Anything Else?**
Add any other information here.

**Comment by therobyouknow** [comment]
`services` module is in codebase as of https://github.com/NaturalHistoryMuseum/scratchpads2/releases/tag/2.10.1
Closing issue as this issue is fulfilled by the presence of the module.

**Comment by Archilegt** [comment]
This is definitely something that is part of a Scratchpads 3.0. Glad that it is already a reality!
