### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6437]
possibly related to earlier overall scratchpads outage today

**Comment by therobyouknow** [comment]
e.g.

![image](https://user-images.githubusercontent.com/1080646/140305625-0d77d9bc-46b9-47db-95db-0c836717e68c.png)

**Comment by Archilegt** [comment]
Possibly. Myriatrix literature search is unavailable as well.
https://myriatrix.myspecies.info/biblio

**Comment by benscott** [comment]
Search is now fixed and working across all Scratchpads.
