### ISSUE TITLE
Notification of scheduled training

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6438]
There is a scheduled training for users of Myriatrix, from November 20th, 09:00 h to November 21st, 03:00 h, Berlin time. Myriatrix is expected to be accessed from multiple countries and do multiple edits, refresh the same page multiple times, etc. We will mainly work in editing the taxonomic backbone, adding bibliographic references, and probably taxon pages. It would be nice if users are not automatically blocked by a firewall, and if the needed modules are up and running. Please, consider letting me know if there are maintenance activities on the Scratchpads side that may disrupt this training. Thanks!

**Comment by benscott** [comment]
Thanks for letting us know!

**Comment by therobyouknow** [comment]
@Archilegt thank you, for my own familiarisation of scratchpads, do you have training materials and/or a video recording I could look at, please? Thank you!  And thank you for the prior notification.

**Comment by Archilegt** [comment]
@therobyouknow, hi! Thank you for your request! I will be happy if we could go online for a two-hour basic training. We just need to choose a time. Think of this Thursday or Friday, and shoot me an email with your free slots, please. :)
The written tutorials are now at: https://scratchpads.readthedocs.io
The video tutorials are at the Scratchpads Team Vimeo account: https://vimeo.com/user1390789

**Comment by therobyouknow** [comment]
Thank you @Archilegt Yes both links useful.  I'm familiar with the 'official' https://scratchpads.readthedocs.io/ which contains a lot of information.  

Of particular interest to me though is how scratchpads are being used in real life by end users such as yourself and for me to be aware of the various ways in which it is being applied. So any 'third party' training materials are a good insight for this, as it gives me an opportunity to 'see' scratchpads through your eyes when you are using it. So the https://vimeo.com/user1390789 link could be very useful to me in that regard. Thank you!

Do you maintain the https://vimeo.com/user1390789 Scratchpad Team channel on vimeo?

**Comment by Archilegt** [comment]
@therobyouknow , glad that the info is useful! About the Scratchpad Team channel on vimeo, I wrote Isabella van de Velde (the voice in the videos) but she has not seen my message yet. Vince may know, as the channel was an official one. If you would like to relaunch it and have updated or more training videos, just let me know and I will try to find the time to contribute.
The "import" workflows are especially important, and they seem not to be working at the moment, or at least some of them. We should go through those workflows together online after you read the training materials and see the videos. I will then show you the current problems from the user perspective.

**Comment by therobyouknow** [comment]
Thank you so much @Archilegt 

Yes I would like to see how we can relaunch it and update with new videos, depending on time and scheduling. Suggestions welcome for screen recording software for making new videos.

I have some experience of editing videos - here are videos I've edited for a regular Drupal meetup a few years ago: https://vimeo.com/therobyouknow/videos/appears/sort:date

**Comment by therobyouknow** [comment]
Closing issue as this event has passed.
