### ISSUE TITLE
Can't access images to add metadata

### ISSUE THREAD

**Issue by Paul-Cannon** [NaturalHistoryMuseum/scratchpads2#6440]
**Describe the bug**
I can upload images, but can't access them to add metadata via the "View" button on the Content menu. Nothing happens when I click on "view", it doesn't even seem to time out. Possibly linked to issue #6425?

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: https://fungi.myspecies.info
 - Browser: Firefox

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?
More than a minor inconvenience, it's making it close to impossible to add new data

**Anything else?**

**Comment by benscott** [comment]
I think this is the same issue as #6445 - the Scratchpads have been reconfigured behind the firewall and this is now fixed.
