### ISSUE TITLE
Site not working.

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6441]
Species pages on https://mormyrids.myspecies.info/  not working for the past two days.  What's happening?

Communication please.

**Comment by therobyouknow** [comment]
Thank you. Assigned to me.

Confirming that I can see the issue here:https://mormyrids.myspecies.info/en/classification/5

![image](https://user-images.githubusercontent.com/1080646/141095682-3ff9924f-3554-4698-9441-eb8cd1595226.png)

**Comment by Archilegt** [comment]
Myriatrix classification is also unreachable. https://myriatrix.myspecies.info/classification/13

**Comment by jpsullivan65** [comment]
Situation unchanged from when I posted 5 days ago. Site has not been working all week.  Some communication would be nice.

**Comment by benscott** [comment]
Hi @jpsullivan65  - apologies for this annoying bug and the delay in fixing it, it's been a struggle to track down what was gong wrong! We've completely updated the way Scratchpads are configured behind the new firewall, and replaced the components that were causing this problem, so your site should be working properly again.
