### ISSUE TITLE
Site not working - National Agromyzidae Recording Scheme Organiser

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6443]
**Describe the bug**
```
For the past two days, I keep getting the message 'The service is not available. Please try again later'. 

The site either doesn't load at all or crashes when I'm halfway through something, losing the work I had just tried to save. 

Please can this be resolved as it is making working on my site impossible. 

Many thanks, 
```

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

Visit site - and get the error.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by BarryWarrington** [comment]
I can click on any page of my site, agromyzidae.myspecies.info, and the message I quoted in my email comes up. It makes working on the site impossible, changes don’t save and is certainly more than a minor inconvenience. It’s only happened a couple of times today as Ben told me he think it’s sorted now. 

Just now, the site is not working with the attached screenshot error.

![BBBAA793-8D8D-4DC9-A12C-006DB3EFA48E](https://user-images.githubusercontent.com/75427252/141528078-fa2f39e8-acb1-40bf-9090-761b11321416.png)

The site is often very slow to load, particularly the taxonomic tree and distribution map. Scratchpads are a fabulous resource but the dips in performance really are frustrating.

**Comment by BarryWarrington** [comment]
The same error message occurred numerous times today, it can happen at any stage on any page. Really hope this can be sorted as it is certainly a pain!

**Comment by benscott** [comment]
Hi @BarryWarrington - apologies for this annoying bug and the delay in fixing it, it's been a struggle to track down what was gong wrong! We've completely updated the way Scratchpads are configured behind the new firewall, and replaced the components that were causing this problem, so you won't be seeing this error message again (and Scratchpads seem to be a little faster too).
