### ISSUE TITLE
Can't insert images

### ISSUE THREAD

**Issue by Hyposcada** [NaturalHistoryMuseum/scratchpads2#6445]
Since my (Wallace Memorial Fund and Correspondence Project) were moved behind the NHM firewall and the urls changed, I can not insert images onto pages. This applies to all images - existing ones or new ones. I cannot create any new pages until this issue have been fixed.

**Comment by benscott** [comment]
Apologies, there was a problem with how we'd configured Scratchpads behind the firewall. This is now fixed & inserting images into pages is now working. Thanks & apologies for the inconvenience.
