### ISSUE TITLE
Taxonomic editor inaccessible

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6455]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

The taxonomic editor is inaccessible. The overlay that should appear when clicking the grey gear + edit of tab overview in taxon page does not load at all, just a grey area appears.
The second way to access the taxonomic editor, which is via the menu Structure, is only accessible to site admins but inaccessible to all other users, as mentioned in " Structure icon for add new taxonomic hierarchy #6449".
It is important that both ways are working for all users, as they are part of the basic training course and videos.

**Comment by therobyouknow** [comment]
following up on this, does this continue to be an issue? Please advise and I will be ready to resume investigating.

I am wondering if our recent server upgrade and associated fixes have improved performance in this functionality - upgrade reference: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6505

If not, then it could be a specific bug which I will investigate.

**Comment by Archilegt** [comment]
The "overlay that should appear when clicking the grey gear + edit of tab overview in taxon page" problem was part of a major series of problems that were ongoing during a Myriatrix training. Most of those problems got solved with routine maintenance on London's side. 
The "Structure icon for add new taxonomic hierarchy #6449" issue should remain open until it is evaluated with test accounts (non-admin accounts). There is also an open issue elsewhere, raising the problem that the possibility to designate site admins has disappeared from the admin options. Maybe those two things could be checked in a round of admin vs user accounts.

**Comment by Archilegt** [comment]
This particular thread can be closed.

**Comment by therobyouknow** [comment]
Acting on your advice on 19 Jan - https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6455#issuecomment-1016503866 to close.   

Please comment here if there if the issue has re-arisen though. Happy to help.
