### ISSUE TITLE
AJAX errors - 'Epic' task

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6458]
To cover all recent AJAX errors October/November 2021 where it is believed there is a common root cause.

**Comment by therobyouknow** [comment]
To cover solution for:
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6366
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6381
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6440
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6445
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6448
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6453

About list created using current awareness of issues + search query: https://github.com/NaturalHistoryMuseum/scratchpads2/issues?q=is%3Aissue+is%3Aopen+ajax

Let me know if any more.

**Comment by jpsullivan65** [comment]
Does this cover the issue with my Scratchpad? Looks like my bug report has disappeared, but my site is still broken:
https://mormyrids.myspecies.info/en/taxonomy/term/430
Again, maybe some communication?  js151@cornell.edu

**Comment by benscott** [comment]
These ajax issues should now all be fixed.  The new https settings were not synced correctly across all the application servers, so for some requests an incorrect asset was being delivered, causing the ajax errors.  Caches have been rebuilt across all Scratchpads, so the loss of style this can cause has also been resolved.
