### ISSUE TITLE
[DUPLICATE of #6455, #6449] cant add new taxon - http://agromyzidae.myspecies.info 

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6460]
**Describe the bug**

I am trying to add a new taxon but the attached error pops up, meaning I can't update the website.

Please can this be looked at?

Many thanks as always,
National Agromyzidae Recording Scheme Organiser

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by Archilegt** [comment]
Already reported on Taxonomic editor inaccessible #6455, and related to Structure icon for add new taxonomic hierarchy #6449.

**Comment by therobyouknow** [comment]
Following up, can you advise if you are still seeing an issue please, also updated on https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6455 and https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6449

**Comment by therobyouknow** [comment]
is this still a problem? @Archilegt   Happy to keep the issue open and work on it for you, along with the other issues I'm looking at?   

We've had server issues some times over the last 6 months or more so I wanted to establish if this issue was a temporary problem caused by that, or if it was indeed a software bug in scratchpads that I actually need to fix.

**Comment by Archilegt** [comment]
I would say that this issue can be closed.
Structure #6449 is to remain open.

**Comment by therobyouknow** [comment]
Closing this issue on advice from @Archilegt 

Same issue being dealt with in these tickets:

https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6449
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6460
