### ISSUE TITLE
Issue with colour - http://agromyzidae.myspecies.info

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6461]
Issue with colour - http://agromyzidae.myspecies.info

If I make the cells in a table I have created a certain colour (see screenshot attached), it shows up on the editing page but when I save the changes and go back to the page in question, the cells are not coloured (see attached screenshot).

![image](https://user-images.githubusercontent.com/1080646/142858948-e1f725e7-bf46-46a6-8a88-429aec1fe65e.png)

![image](https://user-images.githubusercontent.com/1080646/142858979-6c77282d-bef4-4e43-8357-ec7332e333b7.png)

Is this something that can be fixed? Also, is it possible to create a table that doesn't have the borders visible?

Many thanks,

National Agromyzidae Recording Scheme Organiser

**Describe the bug**

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by therobyouknow** [comment]
I think this might be to do with the editor filter config - which might be a simple change

also mentioning https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6315 in case related

**Comment by BarryWarrington** [comment]
Is this yet to be looked at Rob? I tried adding the colour today but it just doesn’t work.

Thanks.

**Comment by therobyouknow** [comment]
Yet to be looked at, but I will look at this for you today @BarryWarrington  Thank you for reminding!

Any fix identified would be scheduled in a few weeks, in January.

**Comment by BarryWarrington** [comment]
Ok, great, thanks Rob. Just seen your message re Christmas period - thanks for letting us know. Hopefully the more frequent roll outs won’t mean more slow/inaccessible sites. 

Thanks for all your help since coming on board and have a great Christmas and new year!

**Comment by therobyouknow** [comment]
You're most welcome Barry. I'm looking at this issue now for you and I will update a little later today with observations outline potential fixes to be done in January.

**Comment by therobyouknow** [comment]
Possible solution for you Barry: For the page, https://agromyzidae.myspecies.info/node/1655/edit try selecting 'Filtered HTML Expanded' Text format choice from the drop down menu beneath the large text box:

![image](https://user-images.githubusercontent.com/1080646/147266706-f18ccaf5-f560-4b5c-a27c-1edd02e6a4b7.png)

This suggestion follows from earlier analysis ( https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6461#issuecomment-975454603 ) that the editor is filtering out certain 'markup' including that which provides the colours you are missing.

Please try it out and let me know how you get on. I may be able to tweak 'Filtered HTML Expanded' further for you to try further. It may be necessary to look at this after the break, in January.  But let me know how you get on with the above when you can. Thank you.

**Comment by BarryWarrington** [comment]
That’s worked, thanks Rob!

**Comment by Archilegt** [comment]
Addition of new text types such as "Filtered HTML Expanded" should be accompanied by text type documentation update on the "Compose tips" page of each Scratchpad, https://[mysite].myspecies.info/filter/tips. Example: https://myriatrix.myspecies.info/filter/tips.
The "Compose tips" page https://agromyzidae.myspecies.info/filter/tips shows very less information and needs a major update. It may be useful to check display of the "Compose tips" page across Scratchpads and to ensure that it is closer to what is shown in Myriatrix, adding the missing "Filtered HTML Expanded" tips.

**Comment by BarryWarrington** [comment]
Thanks but I’ve no idea what that all means! Hopefully Rob will be able to resolve the issues that have happened since I followed his solution.

**Comment by therobyouknow** [comment]
Good afternoon @BarryWarrington @Archilegt and thank you for your further posts here.

Checking in as per Christmas coverage ( https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6498 )

@BarryWarrington 

Noted I had seen the same issue when logged in as your user:

![image](https://user-images.githubusercontent.com/1080646/147833038-e2b225ec-4572-45dd-9e89-8b31d3e69bb2.png)

On page: https://agromyzidae.myspecies.info/node/1655/edit for "What's About".

This is now fixed. You should be able to edit the body field.

This was an error of omission I introduced for "Filtered HTML Expanded" option with regard to user permissions (settings at: https://agromyzidae.myspecies.info/admin/config/content/formats/filtered_html_expanded )


My apologies for that. I have now corrected that omission such that your user role of 'maintainer' is enabled for "Filtered HTML Expanded"

![image](https://user-images.githubusercontent.com/1080646/147833139-ab1e6a12-ac79-48db-b753-f867ea264c49.png)

Let me know how you now get on.

@Archilegt absolutely right that this need documenting. I'm very keen on this, so it will be updated. In the meantime, the information here in this ticket can offer interim guidance.

Thank you, Rob

**Comment by BarryWarrington** [comment]
Thanks Rob. I can now edit the page but the hyperlinks still open up a new
tab, when previously you stayed within the site. Is this something that can
be reverted back to how it was?

Many thanks,

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.

**Comment by therobyouknow** [comment]
@BarryWarrington I've not yet found a setting for it to open in the same tab as required. I checked the editor (CKEditor) and Text Format settings.

Do you get the problem only with "Filtered HTML Expanded", but not "Filtered HTML"?

In other words, if you select "Filtered HTML" and save do the links open in the same tab as required? (As in, what you are referring to as "before".)  Let me know, as that could be additional info for my troubleshooting.

We'd want it to work with "Filtered HTML Expanded" as well, because I know that you lose the colour facility with the original "Filtered HTML" setting.

If "Filtered HTML" opens in same tab as required, then I could also consider  copying the "Filtered HTML Expanded" settings that enable colour into "Filtered HTML" so that you get colour + links opening in same tab as required.

These changes I'm making are to site configuration which can be done outside of the usual release cycle. They currently only apply to your site at the moment.

I might not be able to look at this further today. But will be looking it when back next week.

**Comment by BarryWarrington** [comment]
I changed it to 'Filtered HTML', clicked save - the colour was lost but
when clicking on one of the hyperlinks, it stayed within the same tab as
desired.

Reverting it back to 'Filtered HTML Expanded' led to the colour being
restored (once I had added it) but the hyperlinks opening up in a new tab.

Many thanks,

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.

**Comment by therobyouknow** [comment]
Good morning @BarryWarrington and happy new year!  I will be looking into this for you from today and during this week.

I think it is a case of my fine tuning that filter.  I'm aware of a setting that can be fine tuned with regard to letting colours through but stopping open in new tab.  It's a case of being able to switch these on/off individually as required which I will look into.

**Comment by BarryWarrington** [comment]
That’s great, thanks Rob.

All the best for 2022!

**Comment by BarryWarrington** [comment]
Hi Rob,

Now the upgrade seems to be sorted, I checked this issue and it is still present.

Is this something you’d be able to revisit at some point?

Many thanks,

Barry.

**Comment by therobyouknow** [comment]
Looking at this again.

Taking note of the original Filtered HTML and new Filtered HTML Expanded settings so that I can revert back to them in the event a further change did not work.

original Filtered HTML 

https://agromyzidae.myspecies.info/admin/config/content/formats/filtered_html

![image](https://user-images.githubusercontent.com/1080646/166695930-1fdfeec4-41d8-418a-9231-cccbb5302964.png)

![image](https://user-images.githubusercontent.com/1080646/166696023-617e2771-a618-47c9-bbd5-3fbc56f649c2.png)

new Filtered HTML Expanded

![image](https://user-images.githubusercontent.com/1080646/166696199-d6d73357-f808-4b91-b427-f6d8c5654007.png)

![image](https://user-images.githubusercontent.com/1080646/166696263-4d84b7b9-53cb-45a4-a6ed-98af921dc0a4.png)

**Comment by therobyouknow** [comment]
Right click on a table cell. Then select Cell -> Cell Properties from menu:

![image](https://user-images.githubusercontent.com/1080646/166712225-e48c2d34-7dc4-488a-a957-2e8d7bbfaf5f.png)

Cell Properties modal pop up shown:

![image](https://user-images.githubusercontent.com/1080646/166712556-a7a628cd-f9da-48e6-be7b-32236aeec742.png)

Click 'Choose' next to Background Color

![image](https://user-images.githubusercontent.com/1080646/166712637-d1d65e30-a424-427b-8948-96f2f891bc8a.png)

Choose a colour and click OK.

![image](https://user-images.githubusercontent.com/1080646/166712886-cd43273e-3691-408f-9a96-6532461f284f.png)

Then click OK again 

![image](https://user-images.githubusercontent.com/1080646/166712989-5c464a91-1fed-42f5-aef1-2b6795e2958d.png)

**Comment by therobyouknow** [comment]
Result:

https://agromyzidae.myspecies.info/node/1655



![image](https://user-images.githubusercontent.com/1080646/166713711-72612825-5531-41eb-a3c2-f915af456562.png)

Edit page for this page https://agromyzidae.myspecies.info/node/1655/edit


**Technical Solution summary:**

I made the new "Filtered HTML Expanded" format the same as the original "Filtered HTML" format.

Referring to: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6461#issuecomment-1117343977

They were different in terms of:
- what configurations were enabled. They are now the same
- The Filter Processing order - they are now ordered the same

The key change difference is that for Filtered HTML Expanded, I've removed "Limit allowed HTML tags". Everything else is the same.

I did try adding `<td style>` to the allowed tags to allow the coloured table cells to pass through and show, but this didn't work.

Switching off  "Limit allowed HTML tags" is a potential security issue but this is mitigated if there is a limited number of people that can use the text editor for this format - the "Filtered HTML Expanded" format can be enabled for specific roles to help with that.

Also, the links load on the same page rather than in a new tab/window.

Please confirm this solves the issue as required.

**Comment by BarryWarrington** [comment]
Hi Rob,

Yep, all sorted - many thanks indeed for getting this fixed, very much
appreciated.

Regards,

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.
