### ISSUE TITLE
Grid with specimens not loading

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6462]
- Added by [N. M. Williams](http://ethoikos.myspecies.info/user/2)
- Scratchpad: [Ethoikos Biodiversity Database](http://ethoikos.myspecies.info)

### Description:

Not possible to see the either the complete list of specimens or specimens listed under the specimen tab of a taxon. When called an empty grid appears, greyed out. The animated circle rotates on the screen but no specimens are loaded to the grid.

**Comment by poospiza** [comment]
Seems to be working as expected now. Thanks!

**Comment by Paul-Cannon** [comment]
See also #6448...
Paul

**Comment by therobyouknow** [comment]
N. M. Williams, is this working for you now?

This page looks ok: https://ethoikos.myspecies.info/specimen_observation was it the one where you had seen problems?

![image](https://user-images.githubusercontent.com/1080646/143578927-d137cd76-dbaf-43d7-b9ea-5a5905c1c3d7.png)

**Comment by benscott** [comment]
Fixed - see #6458

**Comment by poospiza** [comment]
@therobyouknow Yes it was. And also the grids with specimens on taxon pages. Both are working as expected. Thanks!

> N. M. Williams, is this working for you now?
> 
> This page looks ok: https://ethoikos.myspecies.info/specimen_observation was it the one where you had seen problems?
> 
> ![image](https://user-images.githubusercontent.com/1080646/143578927-d137cd76-dbaf-43d7-b9ea-5a5905c1c3d7.png)

**Comment by Paul-Cannon** [comment]
All OK for me as well. Thanks for all the hard work

Paul
