### ISSUE TITLE
species drop down menu

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6463]
- Added by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)
- Scratchpad: [Lonchaeidae Online](http://lonchaeidae.myspecies.info)

### Description:

The species drop down menu is not working at
Lonchaeidae online

**Comment by Archilegt** [comment]
Same bug as Taxonomic tree not expanding #6446 
Also reported by https://arachnids.myspecies.info/ at https://www.facebook.com/groups/665993564280327

**Comment by therobyouknow** [comment]
Is this still an issue for you, Iain, this page looks ok: https://lonchaeidae.myspecies.info/taxonomy/term/2060 (is this the kind of page you were referring to?) If not please provide URL.

![image](https://user-images.githubusercontent.com/1080646/143570045-98d30053-43f1-436d-85d8-3eca773457ff.png)

**Comment by benscott** [comment]
Fixed - see #6458.
