### ISSUE TITLE
Loss of formatting on home page when not logged in

### ISSUE THREAD

**Issue by Paul-Cannon** [NaturalHistoryMuseum/scratchpads2#6464]
![image](https://user-images.githubusercontent.com/45429756/143277363-f0743aee-6240-4f11-8864-de264ecd7659.png)

See screenshot. The other pages seem OK, it's just the home page. All works fine with Firefox.

Best wishes
Paul

**Comment by Paul-Cannon** [comment]
Correction - this happens when I'm not logged in (and for others using the site), and it's common to both Firefox and Chrome

**Comment by therobyouknow** [comment]
Thank you for alerting Paul,  linking this issue we solved a while back in case knowledge from that could help us find root cause: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6425

**Comment by benscott** [comment]
This is now fixed - see #6458
