### ISSUE TITLE
Problems to start the created site

### ISSUE THREAD

**Issue by Mazabus** [NaturalHistoryMuseum/scratchpads2#6466]
My scratchpad ( http://rupicolas-paisaje.myspecies.info ) has been created but while clicking on the temporary link for login (for the first time), it gave me an error and I couldn't create a password. Right now I am stuck since even though I ask for a new password, I do not receive anything in my email.

Is there a way I can resolve the Issue?

Thanks,

**Comment by therobyouknow** [comment]
Related: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6466 - deals with the email sending issue, so linking to this ticket.

**Comment by therobyouknow** [comment]
Hello @Mazabus sorry about the issue here - I'll email you a password for login, to the email address you have on your site when you set it up. Will be done in next 20 minutes. Thank you.

**Comment by therobyouknow** [comment]
Email sent to the email used when on your site for your user. Let me know how you get on.

**Comment by Mazabus** [comment]
I'm afraid no email is received.

**Comment by Mazabus** [comment]
I found the email.  Problem solved.

Thank you very much

**Comment by therobyouknow** [comment]
Thank you @Mazabus Closing this issue.
