### ISSUE TITLE
new site creation fails

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6476]
we discovered this in our new release testing.

we don't think the root cause is in the scratchpads code base at the moment,  but rather in the scratchpads ansible devops infrastructure code base.

**Describe the bug**

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by benscott** [comment]
Fixed, new site creation tested and working.
