### ISSUE TITLE
Release in progress: Routine software update in progress - scratchpads sites should still be available - for your information - releases 2.10 and 2.10.1

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6479]
Dear Scratchpad user,

Just for your information:

We are in the process of updating Scratchpads sites with a new routine software update and during this time we expect your site to continue to be available.

Sites may run a bit slower during this time and pages take longer to load, while some of the server computing resource is in use deploying the release. We advise this based on our observations during the release so far.

The software update is for releases 2.10 and 2.10.1 which contain a number of fixes, updates and improvements.
https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/CHANGELOG.md

Thank you,
Rob Davis

**Overview**
Give a brief description of what the feature or improvement should do and why.

**Possible Solutions**
Do you have any ideas for how you'd want to implement it?

**Anything Else?**
Add any other information here.

**Comment by BarryWarrington** [comment]
Thanks for the heads up. Unfortunately, I’ve not been able to access my site for a day and a half now.

Hopefully this will be resolved soon.

**Comment by Archilegt** [comment]
The release affected the "tinyblocks" which display sets of images, either on the homepage or on the taxon pages. The block was supposed to display a main image with that same image and others as thumbnails on the side. Now the format is affected, with the thumbnails not displaying on the side but below, and also the thumbnails themselves remain in blank. The "show image while hovering on thumbnail" effect continues to work.
The release also affected the biblio module, the interface for registering new literature is not displaying.
I have not tested for other issues in Myriatrix.

**Comment by BarryWarrington** [comment]
I managed to get access very briefly and it appears that many of my recent changes (made last week) have not saved, chiefly the distribution maps. This means I am going to have to work through hundreds of taxon pages to see which species are affected. Hopefully this can be fixed so I don’t have to undertake this mammoth task!!

**Comment by therobyouknow** [comment]
We've paused the release to look at associated performance issues that occurred during it. 

983 sites have now got the new release, which is most of them, that number according to our release reporting tool. So it would appear that the release so far was succcessful but at the sametime the act of doing it appeared to have caused significant performance degradation affecting users.

We'll be aiming to resume at 5pm today.

**Comment by therobyouknow** [comment]
Resumed and complete. Several indications that release successful. 100 further sites released to.

Will now look at:
- particular issues you've advised above and in email (thank you). I will create new issues linking to this one for these, as required.
- issues seen during release, for improvements for next one.

Thank you!

**Comment by therobyouknow** [comment]
linking https://github.com/NaturalHistoryMuseum/scratchpads2-ansible/issues/256 for future consideration

linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6457 now resolved and closed.
