### ISSUE TITLE
New Customer Enquiry:  working group from Northern Germany

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6484]
> Hi Scratchpads team,
> i found your software solution very interesting and think about implementing
> this for a regional working group in Northern Germany. 

> I am wondering wether Scratchpads are still an available option and receiving
> support and further development? Is it possible to use the software installed
> on own private servers?
> Thanks a lot for your advice,

We replied:

> `Thanks for your interest. Scratchpads are still being worked on and actively used and are in the process of working up a more comprehensive plan of where we go next, ensuring the long term sustainability of the system and the data people have compiled in their respective sites. 
> 
> It is possible to run them on a private server and all the source code is public (https://github.com/NaturalHistoryMuseum/scratchpads2) but obviously, support is limited if you are running your own version of the code.

I've advised the contact we have raised this issue, for me to track helping them to get set up.

Next steps: for me to help them get setup - which is to advise them to fill out the form on get.scratchpads.org 

Contact details not shown here for general privacy purposes. Though they can create a github user and participate as that user of course.

**Comment by therobyouknow** [comment]
Closing for now. Enquirer advised of the standard sign up for getting a site get.scratchpads.org as well as the option to host on their own servers.

**Comment by Archilegt** [comment]
@therobyouknow, I will be happy to offer training/advice to these colleagues. Please, feel free to pass my contact along. Regards, C.
