### ISSUE TITLE
[RELATED #6558] Sites slow during and following release (scratchpads2 repo issue counterpart to scratchpads2-ansible issue)

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6488]
Issue about this raised in the "scractchpads2-ansible" repo issue list, this "scractchpads2-ansible" is the code that is used to deploy scratchpads
https://github.com/NaturalHistoryMuseum/scratchpads2-ansible/issues/256

Raising a "counterpart" issue in scratchpads2 for visiblity/on the radar for the scratchpad community.

Also linking ticket for recent completed release as this issue relates to this: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6479

**Comment by therobyouknow** [comment]
Thank you @archilegt and @barrywarrington for advising on your slow site speeds.

As @archilegt has observed https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6487#issuecomment-988802538 I think the performance may improve on its own.

The reason why I think performance can improve on its own is that "cache warming" will take place as expected.

To explain what a cache is, it's used to help your site display pages quicker, caches store pre-assembled pages of your site.  These pages are assembled by the scratchpads software for your site that runs on our servers.  It's quicker to display these cached pages than have the software assemble them everytime.  The cache pages are updated whenever a change is made to your site content, e.g. if a taxonomy is edited, new image uploaded etc.

The cache has to be rebuilt / "warmed up" after the release which is what I think is causing your sites to be slow. This is because when we do the release, the cache for each site is cleared,  so that the pages can be rebuilt from the new software. This helps ensure the pages are shown correctly, or if it would change the appearance  of the pages.  Sometimes problems can occur if we run new software with a cache made from earlier software, so we clear it. We might consider omitting this step in several circumstances where we think it's not necessary.

And because there are over 1000 sites, all having been released to and having their cache cleared, I think it can take a while for sites to have their cache warmed up, if this is happening all at once or near enough.

However, I will still look into this to see if there is anything else causing the sites to be slow.

So far, going forward, there are several things I think we can identify for improvements for the next release:
- see if we really need to clear the cache
- see if we need to run a database update, and backup the database before doing this
- use symlinking if possible, instead of copying site code

The above items will be in the open source aegir release/deployment software and can be changed there if we think they would provide benefit.

**Comment by BarryWarrington** [comment]
Thanks Rob. The homepage is often the slowest to load, ie when first getting on the site.

With the cache, I am often contacted by users saying why isn’t the distribution map showing a species from a given region when it is known from there. I have to advise the user to refresh the page which then loads up the up to date map. Is there a way in which I and other users don’t have to refresh a page so that the right map is shown?

Thanks.

**Comment by therobyouknow** [comment]
https://github.com/NaturalHistoryMuseum/scratchpads2-ansible/issues/262

**Comment by Paul-Cannon** [comment]
Just a little further info - caching may be a large part of this but I'm not sure it's the only problem. Starting out this morning the front page (fungi.myspecies.info) took around four minutes to load; there was a link to a new description added yesterday that would presumably not have been previously cached, though the rest of the page wasn't changed. Exiting the site and immediately re-entering (so no changes and no caching issues), the front page still took about 2.5 minutes to load. 
Hope you can fix this soon - and thank you for the good feedback we are getting on problems. That's a major improvement in itself!
Best wishes
Paul

**Comment by therobyouknow** [comment]
Thank you very much @Paul-Cannon yes I certainly want to get to the bottom of the issues you are seeing and avoid recurrence during/after future releases and at other times.

Yes I'm seeing some similar delays in page loading https://fungi.myspecies.info/, though eventually can see the pages I've clicked on to look at. I visited to see if the cache had be 'warmed up' But the front page was still slow to load for me of arounds minutes, and subsequent separate tries (separate web browser) experiencing the same. Further investigating by me needed on this, with liaison with colleagues and our infrastructure and platforms teams.

Thanks again.

![image](https://user-images.githubusercontent.com/1080646/145383622-af167d73-7fef-4c16-985a-7c756f1fa7e3.png)

**Comment by Paul-Cannon** [comment]
Just another small piece of info, sometimes I get a secure connection problem when trying to save data - the message is PR_CONNECT_RESET_ERROR. 
Paul

**Comment by therobyouknow** [comment]
Thank you Paul I will include this finding as part of information used in troubleshooting.

**Comment by therobyouknow** [comment]
Closing this issue because improvements for future released are being addressed in this other ticket: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6558
