### ISSUE TITLE
ajax errors saving edit to name of term on sphingidae.myspecies.info 

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6492]
Raised on behalf of site owner:

https://sphingidae.myspecies.info/taxonomy/term/1148

> Dear Ben & Scratchpad team,
> 
>  I have been spending the day updating the genus Dahira on the Sphingidae Taxonomic 
> Inventory scratchpad and was editing term 1148 (Hayesiana farintaenia) to change it from being the valid name to a previous
> combination of Dahira farintaenia. However, when saving, I got repeated Ajax Errors. On closing the edit box manually and
> checking, some of the edits have been made but there is no parent taxonomy (see first screen shot below) so the taxon has 
> been disconnected from the Taxonomy Tree and disappeared into the scratchpad ether (see also second screen shot). Any 
> idea how to get it back. I could create another term but then searches would continue to find both.
> 
>  
> 
> I also tried to revert to a previous version of the page but received the message “Access denied”. If I am a maintainer, why is this?
> 
>  
> 
> Any help gratefully received.
> 
>  
> 
> Cheers,
> 
>  
> 
> Ian

![image](https://user-images.githubusercontent.com/1080646/145825895-ffc5cd0c-15fb-408f-a30b-1c35a1ab4e09.png)

![image](https://user-images.githubusercontent.com/1080646/145825303-5f272c02-4231-4263-91f1-abbab97ffff5.png)

**Describe the bug**

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by therobyouknow** [comment]
Linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6459 - previous related issue - still open
Linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6458 - which was the Ajax Epic (umbrella) bug where we believe we had fixed the root cause. With Ian's new issue, we may consider re-opening.

**Comment by therobyouknow** [comment]
Update from site owner/user:

> Dear Ben and Scratchpad Team,
> 
>  I don’t know if you did anything overnight but this morning I was able to find and edit the Hayesiana farintaenia term (1148) and re-establish its taxonomy so it is back on the taxonomy tree where it belongs. So that problem is fixed but I don’t know why I could edit the term this morning but not yesterday.
> 
> Cheers,
> 
> Ian

This is useful because it helps towards us pinpointing root cause and to that end, at the moment the information suggests an intermittent infrastructure performance issue rather than a bug in the software. Thank you. 

Closing this ticket but leaving the AJAX Epic open because we'd still want to address what has been said is an infrastructure issue.

**Comment by Archilegt** [comment]
It seems to me that this is not directly related to ajax errors. This is an old classification (taxonomic tree) attachment error which has happened to me as well. There is a drag and drop functionality which allows easy rearrangement of taxa from one parent taxon to another in the classification. However, the drag and drop fails if the user accidentally drops the name in an empty area. The name then disappears from the tree. I remember that I had to ask for one name to be brought back manually because of this issue. The long term solution is to memorize the parent name from which the taxon is dragged from, and setting a failed drop to return the name to its memorized parent.
