### ISSUE TITLE
Going slow or failure to load on Aracnidos Centroamerican

### ISSUE THREAD

**Issue by sjl197** [NaturalHistoryMuseum/scratchpads2#6503]
Going slow or failure to load on https://arachnids.myspecies.info
Over last few days, I've been trying to edit some links to the literature etc onto each of the taxon names -using the fill-in boxes and radio buttons, but when trying to open a new editing page , then sometimes its been working fine, other times just very slow, often stalls. Regularly now i get a popup message pasted below when i click "save" (pasted below) telling me there's an error, then its been hit or miss whether it saves.

After i've done a few such edits, it often gets increasingly slow, and the number of times that error popup appears seems to increase. Now the website doesnt open at all after a couple of edits.

**To Reproduce**
 The website doesnt even load now, so i cant revise what steps.

**Screenshots**

This is text message which pops up sometimes when trying to save an edit"

An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: https://arachnids.myspecies.info/index.php?q=node_reference/autocomplete/taxonomy_term/taxonomy/field_reference
StatusText: error
ResponseText: 
ReadyState: 0

**Your setup:**
 - Scratchpad URL: https://arachnids.myspecies.info
 - Browser: safari, same on firefox

**Impact**
Repeatedly happening. It's made me unwilling to update or expand on the website multiple times before.

**Comment by therobyouknow** [comment]
linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6500

**Comment by therobyouknow** [comment]
I've spoke with our infrastructure team and one of the actions we have identified is a server software upgrade which can help address these performance issues.
There are other things we'd want to consider as well.
Will update with regard to scheduling this update and further measures.
Thank you,
Rob Davis,
Research Software Engineer, Natural History Museum, London

**Comment by BarryWarrington** [comment]
My site is down too.

**Comment by therobyouknow** [comment]
linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6504

**Comment by BarryWarrington** [comment]
When using my desktop or iPad, my site doesn’t load at all or only loads the home page and no other pages load up from there.

However, if I access my site via my mobile phone (using the home wifi), the site loads up absolutely fine! Unfortunately, I can’t really work on my site via my phone so hopefully the current outage will be resolved soon.

**Comment by therobyouknow** [comment]
linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6505

**Comment by therobyouknow** [comment]
Hello @sjl197 please advise if you continue to see issues or if things are better.

We've done some server upgrades and there has been an associated outage which is now resolved.  The server upgrades were to address many performance issues reported by site admins.

Since the upgrade, several other site admins are reporting good performance, and I would hope that you might be experiencing similar. But please feed back in any case.

Related ticket: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6505

**Comment by Archilegt** [comment]
This site is responding very fast from my side, the taxonomic tree expands correctly and all the main tabs are reachable.

**Comment by sjl197** [comment]
@therobyouknow 

Things indeed seem much better on this end. Both on Safari via MacBook and on iPad, the links and such are all acting sprightly. 

Else just on communication issues. Thanks for coming back on this thread and updating. I feel i've been made aware of activity in response and steps being taken, which is great from my "user" perspective.  I'm glad to say i've been seeing the feedback here (which you seem to prefer, and nicely that's getting forwarded to my email), but also on facebook and twitter. so thankyou for those combined. I've seen something on possible email mailing lists? If so, would you please add the two emails linked on page below to any email sendouts.  https://arachnids.myspecies.info/node/318

Thanks also to @Archilegt @BarryWarrington for supporting comments - from testing here, i find that both your websites (i.e. Barry's 6-legged ones, Carlos's many legged one) are also functioning very well. You both have more content than we (Aracnidos) have, so that's great. Else Barry - thanks for giving your shared sentiment of "makes the owner not want to work on it". With things now working, i'm re-motivated to put more into our Aracnidos page .

**Comment by BarryWarrington** [comment]
Thanks sjl197. Even though I’ve only had my site for a couple of years (it’s only been ‘live’ for a year), I think scratchpads are a fabulous resource and I don’t think enough people are aware of them.

The aim for my site is to have a resource, which is free to all of course, that covers all aspects of Agromyzidae meaning that no one has to spend hundreds of pounds on the literature needed to study the family. I have been approached in the past about producing a publication which would have no doubt been rather expensive but I turned it down as I hope my site, in time, will be the go to resource for British Agromyzidae. 

By having a site that works well and without issues is a massive help and by having Rob on board, it is making it much easier and more pleasant working on it.

**Comment by therobyouknow** [comment]
Thank you for all your feedback. My thanks to @benscott and our TS team who all played vital roles in working on the upgrades and associated fixes for issues arising.

With regard to @sjl197's comment:

>  I've seen something on possible email mailing lists? 

Thank you, yes we are looking into setting up one, to run alongside the existing communciations of here, on github, Facebook and twitter.
This ticket is our to do item for it: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6511

Thank you all again.

For this ticket here https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6503 I will close it on the basis of @sjl197's  feedback https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6503#issuecomment-1016011149 that their site is working better.

Please do re-open if you encounter issues, or raise a new ticket for anything else as usual.  Early observations by us and yourselfs suggest encouraging performance improvements, but we'll all keep an eye on it of course! Thank you.
