### ISSUE TITLE
server os upgrade - Thu 13 Jan 10am

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6505]
We believe this can help the outage issues.

Next steps: planning, scheduling and communication with Scratchpads user community - here.

**Describe the bug**

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.

**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?

**Anything else?**

**Comment by therobyouknow** [comment]
Scheduled for Thu 13 Jan 2022, from 10am.

**Comment by therobyouknow** [comment]
Community notified by email and on social media.

During the upgrade there may be some performance impact or outage.

**Comment by BarryWarrington** [comment]
Hi Rob,

I haven’t received an email. How long will the probable outage last?

Thanks,

Barry.

**Comment by therobyouknow** [comment]
Good morning @BarryWarrington 

Good question thank you! Which I'll answer below - will be useful to the community in general:

Summary answer: up to 1-2 minutes about 7 times spaced out during Thursday 

I'll be doing the upgrade server by server. We have 7 of 8 servers to run the upgrade on.

For each of the 7 servers we will need to do at least one restart which will mean that server will go offline for about 1 to 2 minutes.

I'd also advise on not doing any content changes / updates to your site on Thursday. We run backups routinely but we may not pick up the most recent changes done on the day. I'll create a separate ticket to raise awareness of this.

**Comment by therobyouknow** [comment]
Linking separate issue about content freeze: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6506

Updating on other channels: Facebook group, email distribution list (need to check all recipients present).  Will also do on twitter.

**Comment by BarryWarrington** [comment]
Ok, thanks Rob. I’ll keep off the site tomorrow then.

**Comment by therobyouknow** [comment]
We are currently troubleshooting some issues arising from the server upgrade. We are observing at least several sites are down at the moment.

**Comment by BarryWarrington** [comment]
Yep, mines currently down but was loading ok around 3pm.

**Comment by therobyouknow** [comment]
Good morning. We're still working on restoring. The main problem identified so far is that several of our servers used for site databases aren't running their database software as we expect - fixing this is expected to help with sites coming back online.

The upgrade had affected the ability for site database software to start on serveral of our servers.

**Comment by therobyouknow** [comment]
I'm working on reinstalling the database software. It would appear that our overall upgrade has upset the database software. We have backed up the database content for sites, but at the moment expect a reinstall not to require use of the backup. update within 1 hour.

**Comment by therobyouknow** [comment]
We're looking at further steps to restore more things back to how they were.

**Comment by BarryWarrington** [comment]
Does that mean there are aspects of the sites that have changed (for the
worse)?

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.

**Comment by therobyouknow** [comment]
Hello Barry, no I wouldn't think so.    Restoring things takes time so we try to minimise that time by identifying things like server settings that were changed by the upgrade, putting them back to how they were before the upgrade. If we need to restore more settings then we will do that. 

As regards sites themselves, the content should be unaffected, as we've have used a backup taken just before the upgrade was started, and we advised on a content freeze during the day Thursday. https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6506

In terms of server performance some of the upgrade has gone through OK on other servers, so there may be some benefit to be had in terms of speed, even though there are servers where it wasn't successful this time.

**Comment by BarryWarrington** [comment]
Ok, thanks Rob.

You mention that there may be some benefit to be had in terms of speed - I
thought this was one of the main reasons for carrying out the upgrade, to
stop the frustrating time it takes to load pages? So there's a chance the
sites will remain to take time to load etc?

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info

**Comment by therobyouknow** [comment]
We've some very early and small amount of information that sites that are up and running which are not on affected servers, are running faster. But we'd need more examples of that to come to a positive conclusion.

The priority at the moment is getting the sites back online.  After that, we would want to see how performance might have improved following the servers we did upgrade successfully. And after fixing the other servers where there were problems with the upgrade, we'd want to review what happened to prevent it for the future. And then plan for another upgrade should the familiar performance issues persist (for some sites).

**Comment by BarryWarrington** [comment]
Ah, ok, thanks Rob. Fingers crossed they're back up and running soon enough!

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info

**Comment by therobyouknow** [comment]
We're working on a further fix of the server software.  I'm not sure at this stage of the next update today.

**Comment by therobyouknow** [comment]
This will be resumed on Monday. We have several things to do to fix this issue.

**Comment by therobyouknow** [comment]
Good morning. Resuming work to restore Scratchpads.

**Comment by BarryWarrington** [comment]
Great, thanks. Hopefully they'll be up again soon as I have plenty to
update on there.

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.

**Comment by therobyouknow** [comment]
Thank you Barry.

Barry + others on here:
We're aiming to have some sites up and running by end of today though there is some uncertainty as to timescale and amount of sites.  My apologies for this outage. I will always update as and when we know more.

**Comment by Archilegt** [comment]
Thank you for your work, Rob! I'm following this thread and crossing fingers. :-)

**Comment by therobyouknow** [comment]
We're getting closer to having some sites up and running, after much further deeper analysis to get to the root causes of the outage. With the understanding of the root causes found so far, we are now implementing solutions to help get the sites up and running.

**Comment by therobyouknow** [comment]
Good morning! We're resuming getting your sites up and running.

Some actions have been implemented to help the servers start their software more reliably and keep it running.

**Comment by BarryWarrington** [comment]
Great, thanks Rob. Once it's back on, are we safe to start working on them
as I have loads to do!

Regards,

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.

**Comment by therobyouknow** [comment]
@BarryWarrington - your site is up:

![image](https://user-images.githubusercontent.com/1080646/149944913-f6158bc5-9c17-4db6-b71e-774904f42a8a.png)


Everyone + Barry:
Update: good news - sites are coming back up. Checks on a small number so far indicate up and running. Please feedback on your site.

Thank you to @benscott and our TS team for troubleshooting.

**Comment by BarryWarrington** [comment]
Mine too - seems very quick with no issues detected yet! Many thanks Rob.

Barry.
National Agromyzidae Recording Scheme Organiser
https://agromyzidae.myspecies.info <http://agromyzidae.myspecies.info>
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.
