### ISSUE TITLE
[DUPLICTE of #6447] Request for new password unsuccessful (newly created scratchpad)

### ISSUE THREAD

**Issue by gerwinC** [NaturalHistoryMuseum/scratchpads2#6507]
**Description of Bug:**
Very similar to [6466](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6466) / [6465](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6465)
When attempting to use the one-time login for my newly created Scratchpad, on Friday, 7th Jan. 2022, one-time login was not successful (maybe the problem was influenced by very slow responses from the scratchpad server). When trying again I saw a message "You have tried to use a one-time login link that has expired. Please request a new one using the form below." Then I tried several times to request a new password (on Friday, and Sunday), but did not receive an e-mail. 
**My scratchpad URL:**
http://cotoneastretum.myspecies.info
**Impact:**
It is impossible for me to access my scratchpad.

Can you please create a password for me and send it directly to my email address?

**Comment by therobyouknow** [comment]
thanks @gerwinC  I will look into this for you. 

I'm upgrading the scratchpad servers at the moment - see https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6505 and https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6506 with the aim to improve scratchpads performance.

Once this is complete later today I can come back to you. I will look forward to helping you @gerwinC

**Comment by gerwinC** [comment]
Hi again, 
are there any updates? I did not receive an e-mail with password and still cannot access my new scratchpad. 
Regards, G.

**Comment by Archilegt** [comment]
@therobyouknow , this is the same case as with Davide Dal Pos and Gontran Sonet. To solve the problem quickly, just create a password yourself, like 123 or anything, and send it to the admin via normal email, using the admin email address registered in the platform.
Regards,
C

**Comment by Archilegt** [comment]
@gerwinC , once that you regain access, we can meet online and I can guide you to quickly set up your site.

**Comment by therobyouknow** [comment]
hello @gerwinC aer you able to login today?  

If not, I can reset your password you and advise you of the new password so you can login.

Beyond that, there is a  general known issue with email passwort reset which we need to fix, related https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447

**Comment by gerwinC** [comment]
Hello Rob,

Thank you for your message. I still cannot login because it was not  
possible to use the one-time login sent to me  on 7th Jan. The  
one-time login isn't available any more: "You have tried to use a  
one-time login link that has expired. Please request a new one using  
the form below."

I requested a new password via the web form several times in January,  
and tried again today (15 minutes ago), but never received an e-mail  
(in spite of messages "Further instructions have been sent to your  
e-mail address"). Maybe the only solution is for you to reset my  
password and advise me of the new password?

Regards
Gerwin



Quoting therobyouknow ***@***.***>:

**Comment by Quote2106** [comment]
The issue still exists.
I would need a new request password mail for my own account.

**Comment by therobyouknow** [comment]
hello @gerwinC and @quote2106 I will look into this for you.

**Comment by therobyouknow** [comment]
@gerwinC new password emailed to you.

**Comment by tsrsilva** [comment]
Hi @therobyouknow the issue still persists. I have been trying to request a new password for myself, but the system is not sending any e-mails to my address. I am the maintainer of one Scratchpads page that is still in development (https://strumigenys.myspecies.info/).

**Comment by therobyouknow** [comment]
I'm pleased to advise that the password email facility should now be working, following initial testing. More detail here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447#issuecomment-1138610498

**Comment by therobyouknow** [comment]
I am now tracking this problem in this issue https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447 

This helps me centralise the tracking of the same problems so that I can more quickly record my investigation to progress the solution and for other developers to find where I've got to to be able to contribute as well.

Therefore I am closing this issue #6507 because it is being tracked in #6447, but don't worry I am still working on the problem and tracking it in #6447.

Thank you very much for raising it. 

Please always continue to raise an issue if you see a problem. If it appears to be the same as an existing issue I will mark it as such as a duplicate and link it to the existing issue.  

Don't worry - I'm very happy to hear about new issues - I always want to hear about them. 

My marking as duplicate is just part of the standard process of understanding a problem to provide a solution as soon as possible.
