### ISSUE TITLE
Not able to expand taxonomy

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6508]
**Describe the bug**
The [+] link to expand a taxonomy item doe snot work.

**To Reproduce**
Click on any [+] to expand the taxonomy on https://bio.acousti.ca/classification/dendropsophus

**Your setup:**
 - Scratchpad URL: bio.acousti.ca
 - Browser: Safari/Firefox 

**Impact**
Excessive use of search works for me - not practical for other users.

**Comment by BarryWarrington** [comment]
FWIW, mine expands ok.

**Comment by Archilegt** [comment]
In Myriatrix it expands ok.
@therobyouknow, are the https settings of bio.acousti.ca synced correctly across the application servers?

**Comment by edwbaker** [comment]
This seems resolved and the site much faster now (perhaps AJAX timeout?). Will close and keep an eye on it.

**Comment by therobyouknow** [comment]
Thank you @edwbaker 

It's possible that the server upgrade and additional fixes for the associated outage have helped with this.

Linking: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6505

Certainly, re-open if same issue seen again or raise another ticket if different issue seen.

For now, thank you for closing the ticket.
