### ISSUE TITLE
BioVel is gone

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6512]
@edwbaker, the BioVel (http://www.biovel.eu/) infrastructure seems to be gone. Someone should notify the responsible people. It seems that the domain could be bought by anyone. There should be a BioVel copy safely archived somewhere for permanent reference. Please, keep me in the loop for updates on this matter. Thanks!

**Comment by Archilegt** [comment]
I see. It seems that it is migrated to http://biovelportal.vliz.be/ but the documentation at https://www.re3data.org/repository/r3d100011697 is still pointing to https://www.biovel.eu/
@edwbaker, is the new link good for updating your Scratchpad BioVel link?

**Comment by edwbaker** [comment]
As far as I know the only site that used Biovel (apart from proofs of concept) was bio.acousti.ca. This functionality (acoustic analysis) is being transferred to a new project which at some point will need to be linked into the Scratchpad and the Biovel functionality removed.

Unless there are other users of Biovel it seems that this functionality could be removed without any loss of current functionality. I am not sure of the sustainability plans for Biovel - the last information I had was the service was going to be shut down. I guess the service could potentially be replicated either at NHM if there is a demonstrated need.

@therobyouknow - at some point in the past @benscott and I discussed moving the 'wildsound' module which provides this custom functionality for bio.acousti.ca out of the Scratchpads tree into it's own repository so I could do this work (no other sites use this module). This is probably still the easiest way forward unless you have better ideas?

**Comment by edwbaker** [comment]
The person to contact in the first instance for an update would be Alex Hardisty, or possibly Matthias Obst as LifewatchSweden took on maintenance of the project (around 2017?).

@therobyouknow - happy to get an update if you'd like me to, or I can pass you contact details on NHM Teams.

**Comment by Archilegt** [comment]
With SysTax.org down, many taxonomic datasets and files will need to be rescued and given a new home. From the bioacoustic side, one potential user of Scratchpads and BioVel related workflows would be DORSA - A "Virtual Museum" of German Orthoptera Collections, which has its data unreachable because of the SysTax.org outage. I already wrote Klaus Riede to see what could be done and I am waiting for his reply. 

SysTax.org Myriapoda and Onychophora data can be rehoused in Myriatrix. However, we need to restore the functionality of the specimen module. For a long time it has not been possible to import the "collector" and "identified by" fields in specimen datasets, making importing large datasets impossible because the "people" don't exist in the Scratchpads database and it is unthinkable to create profiles one by one, which also requires creating emails for thousands of dead people.
Linking #6169

**Comment by edwbaker** [comment]
I know Klaus - if he wants to get in touch and discuss this I'd be happy to hear form him.

**Comment by therobyouknow** [comment]
Good morning. Assigned myself this ticket - reading through your comments and will then work out what I can help with (possibly re-assigning if needed or de-assigning depending on what needs doing).

**Comment by edwbaker** [comment]
Happy to provide some background on BioVel and the integration we did (it was about 6-7 years ago now if memory serves) if useful.

**Comment by Archilegt** [comment]
Perfect. I can also go quickly through the "person" problems in the specimen module. What about meeting us three online on Wednesday afternoon, 1:00 PM your time? I can schedule a meeting in Zoom.

**Comment by Archilegt** [comment]
@edwbaker, sorry that I wasn't clear. I was expecting that you could provide "some historical context for things" like the EoL agents file, as you were involved with its implementation in Scratchpads, and as you already offered checking your notes on this long ago. That information would be helpful to understand what got wrong in using EoL agents for filling DarwinCore fields. In your 2014 paper (https://doi.org/10.3897/BDJ.2.e1039) I don't find an explanation on intended use of EoL agents for populating Scratchpads specimen module data. If the functionality of the specimen module is to be recovered, we need to disentangle the EoL agents from the DarwinCore fields, and for that we need to understand how they were linked in the first place.

@therobyouknow, in any case I'm available on Wednesday for a quick explanation on the "collector" and "identifiedBy" fields, how are they malfunctioning at the moment, and how are they supposed to work.

**Comment by Archilegt** [comment]
Hi @therobyouknow . No worries. We can plan better for next week. This specimen module issue is important because it is on the general track of bringing back the publication module. The specimen data import into the publication module is working, but we need the specimen data into Scratchpads first, which is what is not working at the moment. Most papers which could potentially use the SP publication module will have a "Material examined" section, which is meant to be assembled from specimen tables. Seamless creation of those specimen tables is what we are seeking to restore.
I am at UTC/GMT +2 hours. Friday Feb 4th, at my 10-12, is booked. The rest of the week is flexible. Just hit me up, via email if desired.

**Comment by edwbaker** [comment]
@therobyouknow - the wildsound module is in part pretty specific, and builds on the Scratchpads implementation. So just breaking it out into it's own NHM repo for now seems to make the most sense? Perhaps with the longer term goal of separating it into more generally useful parts, and parts related to acoustics within the Scratchpads environment?

**Comment by therobyouknow** [comment]
@edwbaker Yes - github  repo for wildsound sounds fine.  Managing github repositories within repositories is a consideration - but this is not uncommon and git provides for things like this with sub module structuring which I can look into and see where and when we would want to do this.  Always the aim to minimise the steps to get to the goal of course. Thank you.

**Comment by edwbaker** [comment]
@therobyouknow - sure, let me know if you need anything from me.
