### ISSUE TITLE
Urgent : Cannot log in anymore

### ISSUE THREAD

**Issue by gsonet** [NaturalHistoryMuseum/scratchpads2#6514]
dear Scratchpad team,
I cannot log in to the scratchpad that I am managing:
https://jemu.myspecies.info/scratchpads-front?destination=scratchpads-front

I use it regularly (did not forget the password), 
have the same problem on Firefox and Chrome
It already occured in the past because of a configuration that you were able to fix.
Can you solve this ASAP?
THANK YOU VERY MUCH!

**Comment by therobyouknow** [comment]
Apologies for not coming to this earlier. Looking into this now.

**Comment by therobyouknow** [comment]
Good morning @gsonet 

With my usual Super User tools I am able to test logging into accounts and I have been able to login as yourself as per routine checks, as user Gontran Scott. 

![image](https://user-images.githubusercontent.com/1080646/151336635-15e28a1e-c443-4d69-a121-b73b014e8732.png)

On that basis, I think your user account is running as normal. However I appreciate you've not been able to login with your account looking OK I would turn my attention to possible technical issues on our side for example the Firewall Vince mentioned or something else.

Thinking about technical issues on our side stopping you from logging in, we did observe outages/poor site performance incidents during Wednesday - tracked here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6515  Although these were picked up Wednesday, it could be possible that these had started on Tuesday for some sites, perhaps including yours which stopped you from logging in.

On the basis that the above outage/poor performance for at least some sites as passed, and that I can login, can you check you can now log in?

Can advise me what you were seeing when you attempted to login earlier this week?   This would be useful in our analysis of the difficulties logging in as well our analysis of Wednesday's outage/poor performance to take measures to prevent this for the future.

**Comment by gsonet** [comment]
Thank you very much for looking at our problem!
I still cannot log in. Error message: Sorry, unrecognized username or
password. Have you forgotten your password?
<https://jemu.myspecies.info/user/password?name=Gontran%20Sonet>
All the best,
Gontran

Le jeu. 27 janv. 2022 à 11:16, therobyouknow ***@***.***> a
écrit :

**Comment by therobyouknow** [comment]
With the continuing login not working that you have advising me on, I will look into this futher for you now.  I might first consider seeing if resetting the password and advising you of it to re-try the login.

**Comment by gsonet** [comment]
I do not get reaction when I try to reset my password.
I mean, when I ask for a new password, I get " Further instructions have
been sent to your e-mail address." but do not receive any email (also not
in my spams)


Le jeu. 27 janv. 2022 à 11:41, therobyouknow ***@***.***> a
écrit :

**Comment by Archilegt** [comment]
@therobyouknow , this is the same case as with Davide Dal Pos and others. To solve the problem quickly, just create a password yourself, like 123 or anything, and send it to the admin via normal email, using the admin email address registered in the platform.

But yes, at some point we need the system to be able to send emails out again.

**Comment by therobyouknow** [comment]
Closing issue - @gsonet is now able to log in.

However, the email sending problem still remains, which includes password resets - linking: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447

**Comment by therobyouknow** [comment]
I'm pleased to advise that the password email facility should now be working, following initial testing. More detail here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447#issuecomment-1138610498
