### ISSUE TITLE
vacation/holiday of maintainer - back on Monday 28 March 2022

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6537]
for your info - when I'm back next week, I will look forward to:
- progressing with plans for improving performance reliability
- planning for the next release for bug fixes and features
- planning further along for new platform over coming year or so

**Comment by therobyouknow** [comment]
Related: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6526#issuecomment-1065757634

**Comment by Archilegt** [comment]
Have a good one, @therobyouknow ! :-)
