### ISSUE TITLE
Access Denied for Publication Module

### ISSUE THREAD

**Issue by GrazingScientist** [NaturalHistoryMuseum/scratchpads2#6542]
**Describe the bug**
According to my admin (@Archilegt), I have the "contributor" and "editor" right on the Publication Module in his Scratchpads instance. Also, I have the rights of "editing & comment"ing on an example manuscript. However, when I click any button in the Publication section ("Taxonomic paper (Pensoft Writing Tool)", "View", or "Add"), I get an "Access denied".

**To Reproduce**
As not administrator for the instance: In the top black menu, click "Content". In the loaded menu got to the "Publications" section and click any link in there.

**Screenshots**

**Your setup:**
 - Scratchpad URL: https://myriatrix.myspecies.info
 - Browser: I could produce this error with both Firefox 99 and Chromium 101.

**Impact**
I would like to present the module to colleagues in the BIOfid context. So, for me, this has some urgency.

**Comment by Archilegt** [comment]
Hi, @therobyouknow 
Could you please take a look at this? Adrian tells me that he will have to postpone his presentation, which was planned for tomorrow.

**Comment by therobyouknow** [comment]
Hello @GrazingScientist (and thank you also @Archilegt )

To check my understanding, your user is not able to access https://myriatrix.myspecies.info/publication/1#overlay-context=  is that right?

( Click 'Content', scroll down to Publications and click 'Taxonomic paper (Pensoft Writing Tool) )

![image](https://user-images.githubusercontent.com/1080646/166664355-c02a8a7f-a5d2-4813-aa80-17389982b975.png)


I have adjusted the permissions for editor and contributor now be able to 'View Publications':

https://myriatrix.myspecies.info/admin/people/permissions

Before:

![image](https://user-images.githubusercontent.com/1080646/166663500-9649f85f-37ea-42db-94cd-b321987a4189.png)


After:

![image](https://user-images.githubusercontent.com/1080646/166664131-21b3b05a-e110-44e5-bf4f-ea73d1262e4a.png)

**Comment by therobyouknow** [comment]
My above solution hasn't worked when I tested it.  I logged in as you, and can see the 'Access Denied' message.

The only solution I can offer at the moment is to make you an admin @GrazingScientist . @Archilegt is this OK for me to do?

This suggestion is based on my current belief that the Access Denied message is based on user role, in this case 'maintainer' rather than any particular permissions of any role.  The finer granularity of permissions is always preferable.

**Comment by Archilegt** [comment]
Hi, @therobyouknow 
Many thanks for checking this out and testing it. Yes, please, make @GrazingScientist an admin. I would have done it myself, but some time ago the visibility of the "maintainer" checkbox in users' profiles vanished. As a maintainer, I am not able to see the checkbox anymore and that is why I cannot designate other maintainers myself.
