### ISSUE TITLE
Pages not displaying correctly again

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6563]
**Describe the bug**

Home page looks good, but species pages do not,  E.G. https://mormyrids.myspecies.info/en/taxonomy/term/283

**To Reproduce**
See above link.

**Screenshots**

**Your setup:**
 browser independent.

**Impact**

Renders Scrathpad useless.

**Anything else?**

Eat more beets. They're good for you!   And thanks for looking into this.

**Comment by therobyouknow** [comment]
How is this looking for you now? @jpsullivan65 

This is what I see on: https://mormyrids.myspecies.info/en/taxonomy/term/283

![image](https://user-images.githubusercontent.com/1080646/177311930-90139eeb-f61e-4c58-9af4-b7e26045b197.png)

It looks OK but please advise.

Sorry about the issue you advised on earlier.  One possibility is that it was related to the recent outage: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6566

**Comment by jpsullivan65** [comment]
Things have been working fine lately.  Thanks.

**Comment by therobyouknow** [comment]
Thank you @jpsullivan65 
Closing for now, but please certainly re-raise this issue or anything else if there are problems.  Sorry for the delay in responding.
