### ISSUE TITLE
species pages not displaying correctly

### ISSUE THREAD

**Issue by jpsullivan65** [NaturalHistoryMuseum/scratchpads2#6576]
**Describe the bug**
Species pages not displaying correctly for past week or more.

**To Reproduce**
See for example: https://mormyrids.myspecies.info/en/taxonomy/term/485
**Screenshots**

**Your setup:**
 - Scratchpad URL: 
 - Browser:

**Impact**
Renders Scratchpad largely useless/

**Anything else?**
![Screen Shot 2022-08-02 at 10 44 15 PM](https://user-images.githubusercontent.com/21112349/182512970-440b5731-db85-46f1-a2d8-f8ae3570ddf8.jpg)

**Comment by therobyouknow** [comment]
**ongoing analysis**

Confirming I can see this.

Examining the network tab of the browser dev tools,  red listing of css and js items, error seems to be mixed protocol (http/https).

No changes have been made by me that could cause this.

This kind of problem has happened before and has been intermittent. However, I would not yet know why the mixed protocol would be an intermittent issue.

**Comment by jpsullivan65** [comment]
Pages are displaying correctly this morning. Would be good to know what causes this.  Closing.
