### ISSUE TITLE
Fix NCBI

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6594]
possibly shares same root cause as 

https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6564

**Comment by Archilegt** [comment]
Fix how? NCBI is working as intended. If it doesn't show results for a taxon, that is because the taxon name is not recorded in the [NCBI taxonomy](https://www.ncbi.nlm.nih.gov/taxonomy) or recorded with a different name.

NCBI has Myriapoda and Myriapoda in Myriatrix correctly displays NCBI results.
https://myriatrix.myspecies.info/taxonomy/term/6460/descriptions

![image](https://user-images.githubusercontent.com/60008120/193273240-7c60bf88-9019-4062-b6ff-7b4891cdb35b.png)

**Comment by therobyouknow** [comment]
Thank you @Archilegt closing this ticket on that basis. But I will ooen a new ticket for documentation specifically to provide more info on how ncbi works with taxonomy terms.

I can confirm that NCBI works, using a taxonomy term word that is known to be recognised. 



https://staging.myspecies.info/admin/structure/taxonomy/lice/add

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1080646/202170916-1b9d89ac-0066-41d1-95b5-8c20b4388f76.png">

then look for it in the terms list


<img width="958" alt="image" src="https://user-images.githubusercontent.com/1080646/202171619-013e5332-2b0d-4d0c-b5c6-b244ad59de66.png">

click the descriptions tab and observe that ncbi data loads

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1080646/202171945-53e01f7b-8ec8-4679-87ac-330bc560324a.png">


I also did another one, using ACANTHACEAE from https://training.myspecies.info/taxonomy/term/3674/descriptions and observed that ncbi data shown


here's the training site where i got the ACANTHACEAE term from which shows the ncbi working:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1080646/202173324-fa88c83d-a645-4449-b7ae-ff5161b6b7c2.png">


and here's my site with the ACANTHACEAE term added, with ncbi working there

<img width="946" alt="image" src="https://user-images.githubusercontent.com/1080646/202168759-3178c4e9-f52a-41dc-b993-03c2797c49f9.png">


and here's look up on ncbi itself

<img width="957" alt="image" src="https://user-images.githubusercontent.com/1080646/202173603-a084e5fd-cfaa-4173-a7b3-f5b2a4e1ff8d.png">

**Comment by therobyouknow** [comment]
res
