### ISSUE TITLE
 Error in editing a Bibliography element - sphingidae.myspecies.info/node/16939 - Ian Kitching

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6595]
From: Ian Kitching
Sent: 27 September 2022 09:01

Subject: Error in editing a Bibliography element

 I have found that if I try to add a taxon name to the Taxonomic Name field of Boisduval (1875) (https://sphingidae.myspecies.info/node/16939), I receive the following error message. However, if I add a genus name to the Keywords (the genera are keywords), then it is successfully added to the Taxonomic Name list. This issue seems only to affect this reference. I would have tried reporting this through “Issues” but clicking on that side tab does nothing, it won’t open. So that is another problem.

**Comment by Archilegt** [comment]
Double-check how he is using spaces and parentheses. The use (or not) of parentheses when filling names in the Taxonomic Name field was not implemented in an intuitive manner.

**Comment by therobyouknow** [comment]
Next steps for:
- follow instructions and try to create locally
- try character combinations as per @Archilegt's suggestion

1 hour to do above steps and follow up with Ben.

**Comment by therobyouknow** [comment]
resuming working on this now.

> - follow instructions and try to create locally
> - try character combinations as per @Archilegt's suggestion

**Comment by therobyouknow** [comment]
**ongoing analysis, attempt to reproduce**

Going through Ian Kitchings starting comment taken from his email dated 27 September 2022 9:01am, describing the issue:

> I have found that if I try to add a taxon name to the Taxonomic Name field of Boisduval (1875) (https://sphingidae.myspecies.info/node/16939), I receive the following error message. 

What "following error message", please?  Your description doesn't then go on to say what this error message is.

When you say "I have found that if I try to add a taxon name to the Taxonomic Name field of Boisduval (1875)", you are referring to:

![image](https://user-images.githubusercontent.com/1080646/202512011-90a12532-0a5c-49f8-b79b-e37f1fc8d7f1.png)

correct?

![image](https://user-images.githubusercontent.com/1080646/202512375-07b7d2c5-2e35-44a1-82f3-20b831f3e0d4.png)

If so, then if I add a term, by starting to type, e.g. letter 'r' and picking from the list as so...

![image](https://user-images.githubusercontent.com/1080646/202513256-303c9884-5e39-4ec0-a522-253fa17ef042.png)

and saving, then that term is at the end of the list of terms in the Taxonomy Name field:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/1080646/202513591-bab55371-794a-4063-9a8e-d7e6eb213351.png">

Therefore I cannot recreate your issue where you saw an error when you added a term to the Taxonomy Name field.

Can you tell me what specific term you attempted to add? and I will try again with that.

Then in a further email, dated Fri 30 September 2022 1:48pm, you said:

> Dear Robert,
> 
>                       I am now getting the same error with a different reference (https://sphingidae.myspecies.info/node/19807). I suspect it is because I have hit a limit on the number of Taxonomic Names I can associate with a particular reference via the Taxonomic name box. But it still appears that I can add genera via the Keywords. So it may not be a limit on the total number of names per reference but on the total number of names in the box. Is this likely?

The same questions apply:

1 - please tell me what specific taxon name you were attempting to enter
2 - please tell me what error you saw

**Comment by Archilegt** [comment]
I confirm the above are the right questions that Ian needs to reply to solve this issue. Thank you for the follow up, Rob.

**Comment by therobyouknow** [comment]
Ian has responded - thank you.

Confirming I can reproduce Ian's issue 

> I get as far as typing in just , G (no Enter or Return) and get this:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1080646/202689341-7128b049-7556-48d7-9ed2-8b1bac1dd19e.png">

**other comments**

I will look at the following from Ian as well.  Being able to reproduce the same problem above is at least enough for me to recognise that there is a repeatable issue and work on a solution.

Ian also says:

> This is the other reference that I know shows the same error ([https://sphingidae.myspecies.info/node/19807](https://sphingidae.myspecies.info/node/19807#)):

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1080646/202690120-3bc5159d-3134-48a4-aa95-d790b35a0b9e.png">

> Again, there are a lot of Taxonomic names. Trying to add another gets:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/1080646/202690317-1de2c91d-f272-40e8-b5ce-73392c515208.png">

> It does not happen with any other reference to my knowledge, but none has as many taxonomic names as this one.
> 
> The one with the next most Taxonomic names is probably https://sphingidae.myspecies.info/node/20461:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/1080646/202690480-69444d3e-093d-48ef-8bde-e0d7ef8c37e8.png">

> Trying to add another name here would succeed:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1080646/202690623-fae017f9-886e-4b2e-b2c7-43715f7a6e8b.png">

**Comment by therobyouknow** [comment]
**ongoing analysis, issue not seen on local**

On local, if I attempt to add Ian's term `Griseosphinx`, I don't see the AJAX error.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1080646/202723316-5e68f02f-ef5c-4284-8fe0-0c9c02d6eebb.png">

And I can save it and it appears in the Taxonomix name list:

**Comment by therobyouknow** [comment]
**ongoing analysis, the other node where Ian saw the issue**

Again, on my local setup, I am not seeing this issue. But did see it on live.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1080646/202727015-135a5c91-6917-4ee4-87cb-9b2c0dec5f26.png">

**Comment by therobyouknow** [comment]
**ongoing analysis, dev notes - console log error 404**

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/1080646/202729751-8bd0d32c-f629-47e6-bb0e-7920c92f4ba5.png">


https://sphingidae.myspecies.info/index.php?q=taxonomy/autocomplete/field_taxonomic_name/Sphingidae%20%5B18%5D%2C%20Acosmeryx%20%5B271%5D%2C%20Sphingonaepiopsis%20%5B2567%5D%2C%20Sphingonaepiopsis%20pumilio%20%5B2578%5D%2C%20Acherontiina%20%5B5514%5D%2C%20Xylophanes%20depuiseti%20%5B2946%5D%2C%20Xylophanes%20%5B2909%5D%2C%20Hippotion%20velox%20%5B1270%5D%2C%20Hippotion%20%5B1204%5D%2C%20Marumba%20echephron%20%5B5636%5D%2C%20Agnosia%20orneus%20%5B357%5D%2C%20Agnosia%20%5B353%5D%2C%20Meganoton%20nyctiphanes%20%5B1900%5D%2C%20Meganoton%20%5B1890%5D%2C%20Euryglottis%20aper%20%5B1087%5D%2C%20Euryglottis%20%5B1083%5D%2C%20Gnathothlibus%20astyanor%20%5B5648%5D%2C%20Gnathothlibus%20%5B1114%5D%2C%20Macroglossum%20mitchellii%20%5B1578%5D%2C%20Macroglossum%20%5B1503%5D%2C%20Macroglossum%20corythus%20%5B1531%5D%2C%20Macroglossum%20gyrans%20%5B1551%5D%2C%20Macroglossum%20prometheus%20%5B1600%5D%2C%20Macroglossum%20aquila%20%5B1514%5D%2C%20Macroglossum%20avicula%20%5B1518%5D%2C%20Macroglossum%20assimilis%20%5B1516%5D%2C%20Macroglossum%20belis%20%5B1520%5D%2C%20Macroglossum%20bombylans%20%5B1523%5D%2C%20Macroglossum%20micacea%20%5B1574%5D%2C%20Macroglossum%20divergens%20%5B5209%5D%2C%20Macroglossum%20hirundo%20%5B1555%5D%2C%20Macroglossum%20passalus%20%5B1595%5D%2C%20Macroglossum%20regulus%20%5B1606%5D%2C%20Macroglossum%20sitiene%20%5B1611%5D%2C%20Macroglossum%20trochilus%20%5B1625%5D%2C%20Macroglossum%20troglodytus%20%5B46%5D%2C%20Psilogramma%20increta%20%5B2405%5D%2C%20Psilogramma%20%5B2382%5D%2C%20Perigonia%20lefebvraei%20%5B2163%5D%2C%20Perigonia%20%5B2155%5D%2C%20Perigonia%20%5B5169%5D%2C%20Perigonia%20passerina%20%5B2170%5D%2C%20Deidamia%20%5B856%5D%2C%20Daphnusa%20%5B838%5D%2C%20Daphnusa%20ailanti%20%5B840%5D%2C%20Acosmeryx%20socrates%20%5B286%5D%2C%20Acosmeryx%20sericeus%20%5B282%5D%2C%20Acosmeryx%20shervillii%20%5B283%5D%2C%20Amphimoea%20walkeri%20%5B492%5D%2C%20Amphimoea%20%5B490%5D%2C%20Acherontia%20styx%20%5B265%5D%2C%20Acherontia%20%5B261%5D%2C%20Acherontia%20lachesis%20%5B208%5D%2C%20Clanis%20%5B726%5D%2C%20Cocytius%20duponchel%20%5B5749%5D%2C%20Cocytius%20%5B757%5D%2C%20Elibia%20linigera%20%5B894%5D%2C%20Elibia%20%5B891%5D%2C%20Lophostethus%20%5B1489%5D%2C%20Megacorma%20obliqua%20%5B1889%5D%2C%20Megacorma%20%5B1887%5D%2C%20Nyceryx%20continua%20%5B2035%5D%2C%20Nyceryx%20%5B2027%5D%2C%20Nyceryx%20nictitans%20%5B2054%5D%2C%20Paonias%20myops%20%5B2139%5D%2C%20Paonias%20%5B2132%5D%2C%20Xylophanes%20eumedon%20%5B2955%5D%2C%20Trogolegnum%20pseudambulyx%20%5B2894%5D%2C%20Trogolegnum%20%5B2892%5D%2C%20Temnora%20plagiata%20%5B2742%5D%2C%20Temnora%20%5B2681%5D%2C%20Smerinthus%20saliceti%20%5B2557%5D%2C%20Smerinthus%20%5B2541%5D%2C%20Temnora%20murina%20%5B2732%5D%2C%20Temnora%20zantus%20%5B2780%5D%2C%20Aleuron%20chloroptera%20%5B377%5D%2C%20Aleuron%20%5B373%5D%2C%20Theretra%20cajus%20%5B2799%5D%2C%20Theretra%20%5B2793%5D%2C%20Theretra%20rhesus%20%5B2875%5D%2C%20Atemnora%20westermannii%20%5B541%5D%2C%20Atemnora%20%5B539%5D%2C%20Marumba%20dyras%20%5B1847%5D%2C%20Marumba%20%5B1836%5D%2C%20Nephele%20aequivalens%20%5B1994%5D%2C%20Nephele%20%5B1990%5D%2C%20Nephele%20densoi%20%5B2001%5D%2C%20Manduca%20paphus%20%5B5953%5D%2C%20Manduca%20%5B1660%5D%2C%20Manduca%20%5B3087%5D%2C%20Protambulyx%20astygonus%20%5B2335%5D%2C%20Protambulyx%20%5B2333%5D%2C%20Madoryx%20plutonius%20%5B1651%5D%2C%20Madoryx%20%5B1642%5D%2C%20Nyceryx%20nephus%20%5B2052%5D%2C%20Isoparce%20cupressi%20%5B1391%5D%2C%20Isoparce%20%5B1388%5D%2C%20Adhemarius%20daphne%20%5B291%5D%2C%20Adhemarius%20%5B287%5D%2C%20Isognathus%20menechus%20%5B1373%5D%2C%20Isognathus%20%5B1362%5D%2C%20Xylophanes%20aglaor%20%5B2914%5D%2C%20Xylophanes%20anubus%20%5B2919%5D%2C%20Xylophanes%20chiron%20%5B2928%5D%2C%20Xylophanes%20epaphus%20%5B2953%5D%2C%20Xylophanes%20isaon%20%5B2981%5D%2C%20Xylophanes%20maculator%20%5B2998%5D%2C%20Xylophanes%20pistacina%20%5B3016%5D%2C%20Batocnema%20coquerelii%20%5B565%5D%2C%20Batocnema%20%5B561%5D%2C%20Cephonodes%20virescens%20%5B6026%5D%2C%20Cephonodes%20%5B658%5D%2C%20Hippotion%20geryon%20%5B1234%5D%2C%20Hippotion%20echeclus%20%5B1228%5D%2C%20Manduca%20pellenia%20%5B1786%5D%2C%20Angonyx%20%5B519%5D%2C%20Panogena%20%5B2118%5D%2C%20Callionima%20%5B588%5D%2C%20Ambulyx%20%5B388%5D%2C%20Ambulyx%20%5B4655%5D%2C%20Ambulyx%20%5B5172%5D%2C%20Ambulyx%20%5B5173%5D%2C%20Ambulyx%20%5B5174%5D%2C%20Cautethia%20%5B618%5D%2Cg

And if I click on that URL: 

<img width="953" alt="image" src="https://user-images.githubusercontent.com/1080646/202730257-1ad535a2-05d2-4131-9b8d-7c846bba9db9.png">

The firewall appears to have blocked this URL call. Which would explain why my local worked (which doesn't have the NHM firewall).

**Comment by therobyouknow** [comment]
**ongoing analysis, remedying issue and implementation comment for future**

I'll contact our infrastructure team about adjusting the firewall so that this issue can be resolved.

What's happening is that when a new term is added, all of the terms are sent to the server all at once, which is triggering the firewall to think it's suspicious. It's the way that `Taxonomic name` field is implemented in code I'm afraid. I think this would be very involved to try to change how that works. I'm hoping that the quicker solution is to adjust the firewall.

And I would say that the implementation of `Taxonomic name` field could be better: all the terms are being submitted as well as the new one, in a very long URL. Ideally we'd only want to just submit the new term by itself!

**Comment by therobyouknow** [comment]
**firewall change follow up**

Fix in put in place. I will test in a few minutes once it is has been applied.

Hi Rob,

I’ve increased the limit to 5120, should come through in around 5 mins. We do already have SQL injection detection on generally so that should be ok.

Can you test and let me know?

--

Thank you: Maybe e.g. 5120 or 6400 for a nice computery number?!    The problem URL had 4342 characters.  I would suppose we will eventually hit this issue again if it gets longer, it depends on what the user want s to do. The other length I'd suggest would be no upper limit.

Additional suggestions if possible: If we want to harden security on it, e.g. avoid sql injection etc, then add following conditions for letting through at 5120 or 6400 or no upper limit length character URL:
that the URL includes the string: `/index.php?q=taxonomy/autocomplete/field_taxonomic_name/` are upper and lower case letters, percentage (%) and numbers
I know you'd be able to advise if the firewall has conditional logic and regex to match the above conditions to check them. In any case, the key thing would be to increase the character limit to 5120, 6400 or no upper limit.

Thank you,
Rob


--


Hi Rob,

The issue here is to do with the query length, we’ve got the WAF set to a maximum query length of 4096 for the URL. What number would you like it increased to?

Thanks,

**Comment by therobyouknow** [comment]
**Early indication that firewall adjustment fixes this issue**

Repeat of [previous test](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6595#issuecomment-1320085081) now passed, see:

![image](https://user-images.githubusercontent.com/1080646/208096250-971382c0-ce09-4e1b-8da2-63d304c2a828.png)

**Comment by therobyouknow** [comment]
Full test indicates working. Final part of completing this issue is to get user to also confirm fixed on their side.

Autocomplete now shows when attempt user steps, instead of the [error](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6595#issuecomment-1319850566)
![image](https://user-images.githubusercontent.com/1080646/208100244-d55003c2-4c1b-4af4-8fb5-e0cae8bf0f92.png)

![image](https://user-images.githubusercontent.com/1080646/208100487-7490737a-a8ed-47e5-b2ce-46451b341aec.png)

**Comment by therobyouknow** [comment]
This ticket is ready to be closed but I will keep it open when we review the sprint again.

> From: Ian Kitching 
> Sent: 16 December 2022 13:19
> 
>  
> Dear Robert,
> 
>                       I have successfully added a species to each of the two references that were previously causing problems. So all looks well in the world. Thank you for your help in resolving this problem.
> 
>  
> 
> Cheers,
> 
>  
> 
> Ian

**Comment by therobyouknow** [comment]
Closing ticket as per last comment this is solved. 

Solution is firewall adjustment, therefore no scratchpads software code change or release.
