### ISSUE TITLE
How-to request: Export the data to an excel-flile

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6600]
- Added by [Stephan Imhof](https://mhp.myspecies.info/user/2)
- Scratchpad: [Mycoheterotrophic Plants](https://mhp.myspecies.info)

### Description:

Hello,
I would like to handle my data in an excel-file. How can I export the taxonomy, best would be only the accepted species, into a csv or similar file type?
My scratchpad is mhp.myspecies.info
Thanks for any hint,
Best wishes,
Stephan

**Comment by Archilegt** [comment]
Hello Stephan,
Please, read this tutorial: https://scratchpads.readthedocs.io/en/latest/export/exporting-data.html

**Comment by StephanImhof** [comment]
Dear Archilegt,
sorry for the late response, I just discovered your comment by chance...
I checked the tutorial you suggested already, but could not make use of it. The excel file exported just give me the headers, and in a second cheet the possible data, but not the combination of both. Is there a possibility to have all accepted names in the column of 'accepted names', the rank in 'Rank' and synonyms in 'Syonyms'? I attach the file which I received.
[TEMPLATE-import_into_mycoheterotrophic_plants_xls.xls](https://github.com/NaturalHistoryMuseum/scratchpads2/files/9901074/TEMPLATE-import_into_mycoheterotrophic_plants_xls.xls)
Thanks for answering,
Stephan

**Comment by therobyouknow** [comment]
Hi Stephan, 
Thank you for getting in touch and your email about this issue.

I will check my own notes on how to run the export and get back to you. I agree it's not completely obvious!
Rob

**Comment by Archilegt** [comment]
Hi, Stephan,
Please, note that there are two Excel files available for download. You most likely downloaded the "Excel template file for this import." You need the second Excel, named "Excel template file for updating data already present on your site." See the last line of text in the screenshot below.

![image](https://user-images.githubusercontent.com/60008120/199481607-2288a37c-b5ec-4034-931d-a204b824be1f.png)

**Comment by therobyouknow** [comment]
Hi @StephanImhof ! Yes @Archilegt has the solution.  

In summary the export is available from https://mhp.myspecies.info/admin/import when you are logged in as your user.  It sounds counter-intuitive, doesn't it?  With the page being about 'import' when actually it's an export you want to do.

As @Archilegt says, use the Excel option. The export facility is only available as Excel. But once loaded into Excel or compatible program, or Google Docs, the you can export the Excel file as a csv.

Here are my screenshots of my successfully following the steps below. In the end, I got a file containing a list of the Mycoheterotrophic Plant species.

![image](https://user-images.githubusercontent.com/1080646/199554711-0b40866b-8824-4fed-b7ca-d0ae729a2289.png)

![image](https://user-images.githubusercontent.com/1080646/199554788-d70bd1c3-597f-4746-be83-616c0e40806d.png)

![image](https://user-images.githubusercontent.com/1080646/199555041-df9ffa2b-7c30-4d71-bf2e-d4be523e6c53.png)

![image](https://user-images.githubusercontent.com/1080646/199555127-bc5518e1-1ee1-4fbf-a384-b9571b297e7b.png)

![image](https://user-images.githubusercontent.com/1080646/199555169-47aabe7d-cb56-4168-987f-ad09eafb0094.png)

![image](https://user-images.githubusercontent.com/1080646/199555232-ea6724ac-5cd5-4a44-93b7-1bdafccd4b4a.png)

**Comment by therobyouknow** [comment]
@StephanImhof advised in email that they can use these steps so I will close the ticket.

> now I know how to export the taxonomy.

> Hey Rob,
> I will keep your instructions safely in order to not forget the steps.
> Thank you!
> Stephan


Related further query about something similar: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6601
