### ISSUE TITLE
test issue when not logged in

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6614]
- Added by [Scratchpad Team](https://myriatrix.myspecies.info/user/1)
- Scratchpad: [Myriatrix](https://myriatrix.myspecies.info)

### Description:

test issue when not logged in

**Comment by therobyouknow** [comment]
test complete, closing.

**Comment by Archilegt** [comment]
@therobyouknow, this has been like that already for many years. You can also see it working regularly, as there are quite a few issues that are posted directly from active Scratchpads and not by GitHub user accounts. Who requested this feature as new and when?

**Comment by therobyouknow** [comment]
@Archilegt it was requested in this ticket: https://github.com/NaturalHistoryMuseum/scratchpads-evolution/issues/15

You're right, it does work: raising a github issue from a Scratchpads logged in user on a site.

The ticket also talked about further integration beyond that, which I think should be considered for the next Scratchpads platform, so I've moved it into the Scratchpads Evolution project and I've given reasons why in that same ticket, as a comment.
