### ISSUE TITLE
More WAF issues?

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6616]
![Screenshot 2022-12-08 at 15 50 11](https://user-images.githubusercontent.com/929684/206493895-7424df12-21be-4616-ae54-6593fb2aef58.png)

Getting this while trying to do some typical stuff on BioAcoustica - caused by the web application firewall?

**Comment by edwbaker** [comment]
Incidentally, this happened when I was submitting a form which had Chinese characters - not sure that should be suspicious though.

**Comment by therobyouknow** [comment]
Yes sorry about that!

Can you advise me on the particular steps you were doing just before it happened.

I was able to trace another problem to the firewall, using the steps they gave me: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6595#issuecomment-1320094594  and as a result I've advised our firewall folks to make adjustments.

If I can get some further information about your steps then I am thinking I could ask them to adjust the firewall for those also.

**Comment by therobyouknow** [comment]
P.S. were you still able to do what you needed to do:  Granted, a firewall notice came up though it asked for some input a bit like a captcha form to check user authenticity. Did you enter the captcha and were you able to proceed?  How often does it happen?  If it's more than a one-off then I think that would push the case to adjust the firewall.

**Comment by edwbaker** [comment]
I was approving some user accounts, and had a few tabs open.

Entering the captcha did nothing - just gave me the same captcha page back with a new one to complete (tried about 10 times).

The site is currently completely down so I can't check anything...

**Comment by therobyouknow** [comment]
@edwbaker following your steps: I've created 2 accounts robtest and robtest2 via the usual registration process.  I've logged in as admin to check them. So far no firewall issue.

Can you check now please?
