### ISSUE TITLE
New scratchpads site not activated

### ISSUE THREAD

**Issue by jakovosdemetriou** [NaturalHistoryMuseum/scratchpads2#6619]
Hi and happy new year,

I recently applied to create a new scratchpads for the "Ants of Cyprus". I got a response email that the site has been created but when I try to access it or set passwords I get the following message:

https://antsofcyprus.myspecies.info/
Not Found
The requested URL / was not found on this server.
Apache Server at antsofcyprus.myspecies.info Port 80

What can I do to activate the site?

All the best,

Jakovos

**Comment by therobyouknow** [comment]
Can you try now @jakovosdemetriou please.  We've done some housekeeping on our servers to help ensure new sites now activate.

**Comment by therobyouknow** [comment]
@jakovosdemetriou 
your site looks up and running now:

https://antsofcyprus.myspecies.info

![image](https://user-images.githubusercontent.com/1080646/212048426-12a736ba-616d-4943-9c9c-a038caf3ecf3.png)

**Comment by jakovosdemetriou** [comment]
Fantastic! Many thanks. 

I managed to enter the one time login link but I have issues in logging-in. This is the same issue I had with another Scratchpads I worked on. Specifically, some data were not saved and I could not log in with the passwords I set. 
I have requested new passwords but nothing is sent to my email. Although the message "Further instructions have been sent to your e-mail address" nothing is found in spam, junk, bin, inbox etc. 
In the other Scratchpads I worked on a colleague changed my password from his profile but here, where I am the only contributor this cannot be done. What can I do? How can one see what username and password were.
As far as I know, my username is correct. Regarding the password I typed it twice so it must be correct but does not log in.
Since request new password does not do the trick I also got this:
"Sorry, there have been more than 5 failed login attempts for this account. It is temporarily blocked. Try again later or request a new password."

Hehe...sorry for the long text. It is just that I have dealt with the same problem in the past and ALWAYS have it.

**Comment by therobyouknow** [comment]
I will email you your password today. Sorry about the issue here.  You're right - I remember other folks having some issues here in the past. I refer to that as well as your issue to see what we can do to improve this.

**Comment by therobyouknow** [comment]
Password reset sent to both your accounts. Let me know how you get on.

Closing ticket.

**Comment by jakovosdemetriou** [comment]
Working! Many many thanks! :-D

**Comment by therobyouknow** [comment]
Future improvement task for me:
Is this related: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/5715
