### ISSUE TITLE
Upcoming release 2.11 notes and testing - information ticket

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6620]
This ticket informational purposes to capture testing notes and other notes on prep for release. Usual release process documentation also to follow, e.g. changelog, tag etc.

code tested: https://github.com/NaturalHistoryMuseum/scratchpads2/tree/rob/release-sprint-2022-11-14-to-2022-11-21-5

Following code changes, as per done in https://github.com/orgs/NaturalHistoryMuseum/projects/34

- https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501 - missing tabs - [**testing passed**](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6620#issuecomment-1377400635) on staging.myspecies.info
- https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6564 - uicn api (their api down atm) - [**testing passed**](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6620#issuecomment-1377502187) on staging.myspecies.info
- https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6583 - cache clearing for darwin code export - [**testing passed**](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6620#issuecomment-1378887253) on staing.myspecies.info
- https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6612 - update Drupal to 7.94 (from 7.82) - [**expecting to designate as pass**](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6620#issuecomment-1379159659) - staging.myspecies.info is functional without observed issue and above tests pass

Apart from above, other tickets shown as done don't have code changes. e.g. they are firewall changes etc.

**Comment by therobyouknow** [comment]
Notes on testing steps: 
- https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501#issuecomment-1326061917


further notes to be added here and subsequently for test results.

**Comment by therobyouknow** [comment]
**Notes on testing steps**

**IUCN**

Now back online so will try testing this. Will need to ensure taxonomy term is recognised by IUCN so will copy one from a "real" site where I know it worked.

Updates here to follow.

**Comment by therobyouknow** [comment]
**Clear cache so that latest Darwin Core export always downloaded (i.e. not cached copy) - testing notes**

**Comment by therobyouknow** [comment]
**Test update Drupal core to 7.94**
( https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6612 )

Well, the fact that the other tests passed and that the site is running, various admin pages and public visible pages gives a good indication of no issues.

May be inclined to deem this as a pass too on the basis of above.

Would suggest releasing release with this core update to high profile very active site users first and get feedback before proceeding onto further site releases.

**Comment by therobyouknow** [comment]
Testing checked by Ben as well.

Therefore release in progress: https://github.com/NaturalHistoryMuseum/scratchpads2/releases/tag/2.11

**Comment by benscott** [comment]
Closing - this release caused a few issues and sites have been rolled back to 2.10.1.

**Comment by Archilegt** [comment]
The UICN Red List API is gone again.
