### ISSUE TITLE
500 error when change to sphingidae.myspecies.info content [DUPLICATE of #6621]

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6622]
Seen when editing and save a change to the title of https://sphingidae.myspecies.info/node/17804.

**Comment by therobyouknow** [comment]
This is an intermittent and recurring issue.

Initial observations suggest the issue temporarily resolves after a cache clear - an action I did for Ian yesterday and he reported operation now working.

**Comment by therobyouknow** [comment]
Questions for Ian to provide answers to if he can please:

> Hello again Ian,
> few more questions for further information:
> 
> Is it one particular page where you are editing the  Biblio reference - i.e. https://sphingidae.myspecies.info/node/17804/edit
> Or it other pages too?
> And are you adding a new biblio reference or changing an existing one  (I've highlighted in the page the area for he biblio references)
> and what is the text you are attempting to enter?
> I have a copy of your site set up on my lab setup (local personal setup) to probe (techiespeak: "xdebug") and run diagnostics.  The above information will help me with getting to the bottom of the problem.
> 
> It is an intermittent issue, I've been able to add a new reference successfully.
> 
> The saving biblio reference works just after a cache clear.
> 
> Can you tell me if you were doing other things on the site before you edited?  That's not a problem of course, but it could help me with clues as to where to probe my copy of your site I'm analysing.
> 
> Thanks Ian, please let me know about the above.
> 
> Rob
>

**Comment by therobyouknow** [comment]
From analysis so far of our custom module code, modules I am focusing in on to determine root cause or rule out are:
- `sites/all/modules/custom/scratchpads/scratchpads_biblio_autocomplete_tweak/scratchpads_biblio_autocomplete_tweak.module`
- `sites/all/modules/custom/scratchpads/scratchpads_biblio`
I'm going on the premise that Drupal Core update to 7.94 has changed some data structures or database table or fields and these custom Scratchpads modules make an assumption about what to expect with regard to these.


For info, updating to Drupal core 7.94 from (7.82) had these following database updates items as seen when running `drush updb`

```
Performed update: system_update_7085                                                                                                                  [ok]
Performed update: user_update_7020
```

We could consider rolling back to our previous version of Drupal but then that older code base would not be in sync with the updated database.

**Comment by therobyouknow** [comment]
I should add, I'm not able to recreate the error Ian saw on my local personal setup, after trying several times.

That is not a comment on the existence of the error, rather than I'm still trying to recreate the scenario.

**Comment by therobyouknow** [comment]
Response from Ian so far tom 5 questions and then a further 2 from me

> Thank you Ian,
> that is useful to know your answers so far to help my troubleshooting to solve the issue.
> 
> What is the new reference that works? Can you tell me the URL where that reference is? Or is it the same page as befor:
> By my question about what you were doing before, I meant on the site itself. So my refined question on that would be: Before the error, were you doing anything else on the site itself before you edited? Like look at other pages on the site, or editing them, or doing
> 
> Rob
> 
> From: Ian Kitching
>  
> Hi Rob,
> 
>            I have been trying to edit various different references to add data to empty fields. I can add data to the various fields - a URL under “Locators”, an alphanumeric number in “Other numbers” under “Identifiers”, and a start page under “Publication”. Whether I try all these or just one, the error comes up when I try to save. I even get it if I don’t make any changes, just go in as if I was going to edit then immediately try to save. I tried clearing the cache  - cached web content only, not cookies and site data – but that didn’t work.
> 
>  
> 
> I have been doing various things beforehand, as I keep trying every now and then. So emails, editing Word files, commenting on PDFs, there is nothing consistent there. Indeed, yesterday when I tried at home, it was the first thing I did after booting up, firing up Firefox and launching the website.
> 
> 
> That said, of course, I have just tried now on a completely new reference and, guess what, it works fine.
> 
> Cheers,
> 
> Ian

**Comment by therobyouknow** [comment]
Another thing I will look at is comparing the release code bases between 2.11.1  (which Ian's site runs on and the previous release.)

**Comment by therobyouknow** [comment]
Attempted roll back to 2.10.1. Fatal error seen, same/similar as Ian's. Rolled back to 2.11.1 and site now back online.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1080646/214280528-c872e681-3a76-4f52-89ed-1929b93ea315.png">

**Comment by therobyouknow** [comment]
No errors in database logs on live production following attempt at : 2.11.1 -> 2.10.1 -> 2.11.1 (with re-run of database update)


![image](https://user-images.githubusercontent.com/1080646/214284423-898400ab-dd6d-4628-b872-d2cb883115a2.png)

Will now attempt to reproduce error on personal "local" setup copy of site.

**Comment by therobyouknow** [comment]
Couldn't recreate issue on local:
- latest master (with 2.11.1)
- imported ian's site's db
- drush updb
- then checked out 2.10.1
- site fine on web browser inspection
- drush cc all to clear cache to see if this would help expose the error
  - drush broken as a result of downgrade. possibly seen this on live production too.
- stuck at this point because can't use drush to enable watchdog/db logs. but perhaps i'll try to enable this before the downgrade step if i re-run these steps

now also looking at creating a clone site ( githubissue6622.myspecies.info ) of ian's site to study downgrade on production issues and capture it there

but get_cache fatal error on attempt to create this

I'm not logged in to get.scrtachpads.org (which is the right thing to do). see here:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1080646/214306673-78aee47e-ee8c-44dc-8297-72e63a983b11.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1080646/214306846-98a5467e-075b-4b66-bfbf-e119090043c3.png">

**Comment by therobyouknow** [comment]
Details from Ian has to how to recreate/reproduce - for my own issue recreation:

**Wed 18 Jan 2pm**

>                I have just been trying to edit a literature reference on the Sphingidae scratchpad but on trying to save, I encountered an “unexpected error”. I powered down my laptop then on restarting, I logged out but on trying to log back in again, I got another unexpected error (see below). Any idea what is going on? I can’t post an issue as I can’t log in.
> 
> <img width="726" alt="image" src="https://user-images.githubusercontent.com/1080646/214316419-027115be-9085-49a0-8e3c-aa0204cc4489.png">
> 
> Intermittent: Wed 18 Jan 2:51pm "Would you believe that all is now OK? I managed to load the front page, log in and then edit and save a change to the title of https://sphingidae.myspecies.info/node/17804." ... Thu 19 Jan 11:03am "The error is back again" Thu 19 Jan 2:04pm "Thanks, but it is behaving itself again. It’s almost as if the site won’t work at a particular time of day. I have no idea what is going on." Fri 20 Jan 7:16am "I checked at home and on my personal laptop and still get the error (still there this morning) so it can't be anything to do with the NHM systems."


**More detail email, Fri 20 Jan 351pm**

Hi Rob,

>            I have been trying to edit various different references to add data to empty fields. I can add data to the various fields - a URL under “Locators”, an alphanumeric number in “Other numbers” under “Identifiers”, and a start page under “Publication”. Whether I try all these or just one, the error comes up when I try to save. I even get it if I don’t make any changes, just go in as if I was going to edit then immediately try to save. I tried clearing the cache  - cached web content only, not cookies and site data – but that didn’t work.
> 
> I have been doing various things beforehand, as I keep trying every now and then. So emails, editing Word files, commenting on PDFs, there is nothing consistent there. Indeed, yesterday when I tried at home, it was the first thing I did after booting up, firing up Firefox and launching the website.

> 

That said, of course, I have just tried now on a completely new reference and, guess what, it works fine.


**From email from Ian on Mon 23 Jan, 856pm:**

> Another few observations that might help narrow things down maybe. I have been able to add data to several Taxonomy fields of Manduca bergarmatipes ([https://sphingidae.myspecies.info/taxonomy/term/1678](https://sphingidae.myspecies.info/taxonomy/term/1678#)) - Reference, Type data, Taxonomic notes. I was also able to edit the data associated with the images (changing the weight associated with the image). However, when I tried to edit the associated reference (https://sphingidae.myspecies.info/node/17251), that is when the error appears on trying to save. I then tried editing the Description - deleting the content of General description and Diagnostic description, and editing the map,but got the error message there too. However, I am at a loss to see the common threads.

**Comment by therobyouknow** [comment]
My recreation attempts

**1. Wed 18 Jan 2pm**

Edit: https://sphingidae.myspecies.info/node/17804 adding new biblio reference. Save.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1080646/214322986-89282e42-353c-42e5-bcf0-4d598cb772a0.png">

Site OK

<img width="870" alt="image" src="https://user-images.githubusercontent.com/1080646/214324008-c409cc02-fefd-4496-95e8-abde98f16aa3.png">


Now onto: **2. More detail email, Fri 20 Jan 351pm**

**Comment by therobyouknow** [comment]
> Just a note to say that I'm having similar problems on fungi.myspecies.info when I try to use the autocomplete function on the Taxonomic Name field when adding metadata to images....

thank you @Paul-Cannon for advising.

**Comment by therobyouknow** [comment]
Using information [above](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6622#issuecomment-1402019299) to recreate issue seen.

**2 More detail email, Fri 20 Jan 351pm** just is informational

now attempting test recreation item **3 From email from Ian on Mon 23 Jan, 856pm**

Got firewall page

<img width="870" alt="image" src="https://user-images.githubusercontent.com/1080646/214334899-85b64ad7-458d-4d09-9d63-667ed1ee0f89.png">

**Comment by therobyouknow** [comment]
**Fault found**

Error seen when editing the list of terms in the Taxonomic Name field

![image](https://user-images.githubusercontent.com/1080646/214338893-6feb40ff-8d77-4fa7-b7f4-6e0fddff625f.png)


<img width="868" alt="image" src="https://user-images.githubusercontent.com/1080646/214338356-2cbab3f3-5426-4bf5-b4f2-1ce7688157c4.png">

Here's the resultant URL that gets called when I type `L` to add a new term beginning with 
 `L`: https://sphingidae.myspecies.info/taxonomy/autocomplete/field_taxonomic_name/Afrosphinx%20amabilis%20%5B352%5D%2C%20Afrosphinx%20%5B350%5D%2C%20Manduca%20%5B1660%5D%2C%20Manduca%20%5B3087%5D%2C%20Sphingidae%20%5B18%5D%2C%20Nephele%20%5B1990%5D%2C%20Macroglossum%20%5B1503%5D%2C%20Nephele%20charoba%20%5B4484%5D%2C%20Cephonodes%20novebudensis%20%5B678%5D%2C%20Cephonodes%20%5B658%5D%2C%20Macroglossum%20queenslandi%20%5B5943%5D%2C%20Amorpha%20juglandis%20%5B481%5D%2C%20Amorpha%20%5B479%5D%2C%20Amorpha%20%5B4054%5D%2C%20Coelonia%20solani%20%5B779%5D%2C%20Coelonia%20%5B773%5D%2C%20Neopolyptychus%20consimilis%20%5B1979%5D%2C%20Neopolyptychus%20%5B1970%5D%2C%20l

**Comment by therobyouknow** [comment]
**Related database query error**

https://sphingidae.myspecies.info/admin/reports/event/51181

![image](https://user-images.githubusercontent.com/1080646/214342638-1303202c-75e9-48ac-b980-fcf4ee48aa65.png)


`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 10 OFFSET 0' at line 10: SELECT v.name AS vocab_name, t.tid AS tid, t.name AS name, t.vid AS vid FROM {taxonomy_term_data} t INNER JOIN {taxonomy_vocabulary} v ON t.vid = v.vid INNER JOIN {taxonomy_term_hierarchy} h ON h.tid = t.tid WHERE (t.name NOT IN (:db_condition_placeholder_0, :db_condition_placeholder_1, :db_condition_placeholder_2, :db_condition_placeholder_3, :db_condition_placeholder_4, :db_condition_placeholder_5, :db_condition_placeholder_6, :db_condition_placeholder_7, :db_condition_placeholder_8, :db_condition_placeholder_9, :db_condition_placeholder_10, :db_condition_placeholder_11, :db_condition_placeholder_12, :db_condition_placeholder_13, :db_condition_placeholder_14, :db_condition_placeholder_15, :db_condition_placeholder_16, :db_condition_placeholder_17)) AND (t.vid IN (:db_condition_placeholder_18)) AND (t.name LIKE :db_condition_placeholder_19 ESCAPE '\\') UNION SELECT v.name AS vocab_name, t.tid AS tid, t.name AS name, t.vid AS vid FROM {taxonomy_term_data} t INNER JOIN {taxonomy_vocabulary} v ON t.vid = v.vid INNER JOIN {taxonomy_term_hierarchy} h ON h.tid = t.tid WHERE (t.name NOT IN (:db_condition_placeholder_20, :db_condition_placeholder_21, :db_condition_placeholder_22, :db_condition_placeholder_23, :db_condition_placeholder_24, :db_condition_placeholder_25, :db_condition_placeholder_26, :db_condition_placeholder_27, :db_condition_placeholder_28, :db_condition_placeholder_29, :db_condition_placeholder_30, :db_condition_placeholder_31, :db_condition_placeholder_32, :db_condition_placeholder_33, :db_condition_placeholder_34, :db_condition_placeholder_35, :db_condition_placeholder_36, :db_condition_placeholder_37)) AND (t.vid IN (:db_condition_placeholder_38)) AND (t.name LIKE :db_condition_placeholder_39 ESCAPE '\\') LIMIT 10 OFFSET 0 UNION SELECT v.name AS vocab_name, t.tid AS tid, t.name AS name, t.vid AS vid FROM {taxonomy_term_data} t INNER JOIN {taxonomy_vocabulary} v ON t.vid = v.vid INNER JOIN {taxonomy_term_hierarchy} h ON h.tid = t.tid WHERE (t.name NOT IN (:db_condition_placeholder_40, :db_condition_placeholder_41, :db_condition_placeholder_42, :db_condition_placeholder_43, :db_condition_placeholder_44, :db_condition_placeholder_45, :db_condition_placeholder_46, :db_condition_placeholder_47, :db_condition_placeholder_48, :db_condition_placeholder_49, :db_condition_placeholder_50, :db_condition_placeholder_51, :db_condition_placeholder_52, :db_condition_placeholder_53, :db_condition_placeholder_54, :db_condition_placeholder_55, :db_condition_placeholder_56, :db_condition_placeholder_57)) AND (t.vid IN (:db_condition_placeholder_58)) AND (t.name LIKE :db_condition_placeholder_59 ESCAPE '\\') LIMIT 10 OFFSET 0 LIMIT 10 OFFSET 0; Array ( [:db_condition_placeholder_0] => Afrosphinx amabilis [352] [:db_condition_placeholder_1] => Afrosphinx [350] [:db_condition_placeholder_2] => Manduca [1660] [:db_condition_placeholder_3] => Manduca [3087] [:db_condition_placeholder_4] => Sphingidae [18] [:db_condition_placeholder_5] => Nephele [1990] [:db_condition_placeholder_6] => Macroglossum [1503] [:db_condition_placeholder_7] => Nephele charoba [4484] [:db_condition_placeholder_8] => Cephonodes novebudensis [678] [:db_condition_placeholder_9] => Cephonodes [658] [:db_condition_placeholder_10] => Macroglossum queenslandi [5943] [:db_condition_placeholder_11] => Amorpha juglandis [481] [:db_condition_placeholder_12] => Amorpha [479] [:db_condition_placeholder_13] => Amorpha [4054] [:db_condition_placeholder_14] => Coelonia solani [779] [:db_condition_placeholder_15] => Coelonia [773] [:db_condition_placeholder_16] => Neopolyptychus consimilis [1979] [:db_condition_placeholder_17] => Neopolyptychus [1970] [:db_condition_placeholder_18] => 4 [:db_condition_placeholder_19] => l [:db_condition_placeholder_20] => Afrosphinx amabilis [352] [:db_condition_placeholder_21] => Afrosphinx [350] [:db_condition_placeholder_22] => Manduca [1660] [:db_condition_placeholder_23] => Manduca [3087] [:db_condition_placeholder_24] => Sphingidae [18] [:db_condition_placeholder_25] => Nephele [1990] [:db_condition_placeholder_26] => Macroglossum [1503] [:db_condition_placeholder_27] => Nephele charoba [4484] [:db_condition_placeholder_28] => Cephonodes novebudensis [678] [:db_condition_placeholder_29] => Cephonodes [658] [:db_condition_placeholder_30] => Macroglossum queenslandi [5943] [:db_condition_placeholder_31] => Amorpha juglandis [481] [:db_condition_placeholder_32] => Amorpha [479] [:db_condition_placeholder_33] => Amorpha [4054] [:db_condition_placeholder_34] => Coelonia solani [779] [:db_condition_placeholder_35] => Coelonia [773] [:db_condition_placeholder_36] => Neopolyptychus consimilis [1979] [:db_condition_placeholder_37] => Neopolyptychus [1970] [:db_condition_placeholder_38] => 4 [:db_condition_placeholder_39] => l% [:db_condition_placeholder_40] => Afrosphinx amabilis [352] [:db_condition_placeholder_41] => Afrosphinx [350] [:db_condition_placeholder_42] => Manduca [1660] [:db_condition_placeholder_43] => Manduca [3087] [:db_condition_placeholder_44] => Sphingidae [18] [:db_condition_placeholder_45] => Nephele [1990] [:db_condition_placeholder_46] => Macroglossum [1503] [:db_condition_placeholder_47] => Nephele charoba [4484] [:db_condition_placeholder_48] => Cephonodes novebudensis [678] [:db_condition_placeholder_49] => Cephonodes [658] [:db_condition_placeholder_50] => Macroglossum queenslandi [5943] [:db_condition_placeholder_51] => Amorpha juglandis [481] [:db_condition_placeholder_52] => Amorpha [479] [:db_condition_placeholder_53] => Amorpha [4054] [:db_condition_placeholder_54] => Coelonia solani [779] [:db_condition_placeholder_55] => Coelonia [773] [:db_condition_placeholder_56] => Neopolyptychus consimilis [1979] [:db_condition_placeholder_57] => Neopolyptychus [1970] [:db_condition_placeholder_58] => 4 [:db_condition_placeholder_59] => %l% ) in scratchpads_taxonomic_name_field_autocomplete() (line 306 of /var/aegir/platforms/scratchpads-2.11.1/sites/all/modules/custom/scratchpads/scratchpads_taxonomic_name_field/scratchpads_taxonomic_name_field.module).`

**Comment by therobyouknow** [comment]
> Just a note to say that I'm having similar problems on fungi.myspecies.info when I try to use the autocomplete function on the Taxonomic Name field when adding metadata to images....

Yes looks like same issue as Ian's and [Barry's](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6621) and possibly also on: https://phthiraptera.myspecies.info

**Comment by therobyouknow** [comment]
@Paul-Cannon please try https://fungi.myspecies.info/ now - I've changed the site software version to the earlier release 2.10.1

**Comment by therobyouknow** [comment]
This ticket is a duplicate of #6621 and therefore further actions will be logged there.  This ticket will therefore be closed.

**Comment by Paul-Cannon** [comment]
Yes, seems to work fine now. Just going out, will test more thoroughly later, but looking good. Thank you for your help

Paul
